import {useState} from 'react';
import {UserCheck,Plus,Pencil} from 'lucide-react';
import {listarCRM,criarCRM,editarCRM} from './crm-api.js';
import {acessoCRM} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
export default function AgentesChatwoot({usuario,db}){
 const admin=acessoCRM(usuario).admin,[form,setForm]=useState(null);
 const m=useModulo(()=>admin?listarCRM('integracao_crm_agentes'):Promise.resolve([]),[usuario?.id],['crm']);
 if(!admin)return null;
 const novo=()=>setForm({instalacao:m.dados?.[0]?.instalacao||'',conta_id:m.dados?.[0]?.conta_id||'',agente_id:'',usuario_id:''});
 return <section className="crm-painel"><h2>Agentes do Chatwoot</h2><p>Os agentes abaixo já estão associados aos comerciais do Integração. Contatos sem agente mapeado ficam disponíveis à administração para distribuição.</p><EstadoModulo modulo={m}/>
 {m.dados&&<><div className="crm-grade">{m.dados.map(a=><article className="crm-card" key={a.id}><h3><UserCheck size={18} aria-hidden="true"/> {db.usuarios.find(u=>u.erpRef===a.usuario_id)?.nome||'Comercial vinculado'}</h3><p>Associação configurada · Agente {a.agente_id} · Conta {a.conta_id}</p><p className="ajuda" style={{overflowWrap:'anywhere'}}>{a.instalacao}</p><button className="btn" onClick={()=>setForm({id:a.id,instalacao:a.instalacao,conta_id:a.conta_id,agente_id:a.agente_id,usuario_id:a.usuario_id})}><Pencil size={15} aria-hidden="true"/>Editar associação</button></article>)}</div>{!m.dados.length&&<p>Nenhum agente associado ainda.</p>}<button className="btn" onClick={novo}><Plus size={16} aria-hidden="true"/>Adicionar associação</button></>}
 {form&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();const {id,...data}=form;if(await m.executar(()=>id?editarCRM('integracao_crm_agentes',id,data):criarCRM('integracao_crm_agentes',data)))setForm(null);}}><h3>{form.id?'Editar':'Adicionar'} associação</h3>{[['instalacao','Identificador da instalação'],['conta_id','ID da conta'],['agente_id','ID do agente']].map(([key,label])=><CampoCRM nome={label} key={key}><input className="inp" required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} pattern={key==='instalacao'?undefined:'[0-9]+'}/></CampoCRM>)}<CampoCRM nome="Comercial no Integração"><select className="inp" required value={form.usuario_id} onChange={e=>setForm({...form,usuario_id:e.target.value})}><option value="">Selecione</option>{db.usuarios.filter(u=>u.ativo&&u.tipoERP==='Comercial').map(u=><option key={u.id} value={u.erpRef}>{u.nome}</option>)}</select></CampoCRM><div className="crm-acoes"><button className="btn btn-primario" disabled={m.ocupado}>Salvar associação</button><button className="btn" type="button" onClick={()=>setForm(null)}>Cancelar</button></div></form>}</section>;
}
