import {useState} from 'react';
import {listarCRM,criarCRM,editarCRM} from './crm-api.js';
import {acessoCRM} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
export default function Andamentos({db,usuario}) {
 const acesso=acessoCRM(usuario),[nucleo,setNucleo]=useState(''),[form,setForm]=useState(null),[instrucao,setInstrucao]=useState(''),[habilitado,setHabilitado]=useState(false),[promptAberto,setPromptAberto]=useState(false);
 const m=useModulo(async()=>{const [itens,prompts]=await Promise.all([listarCRM('processos_kanban_andamentos'),acesso.pos?listarCRM('integracao_nucleo_ia'):Promise.resolve([])]);return {itens,prompts};},[usuario?.id]);
 const ref=n=>n.externo?.kanbanId||n.id;
 const nome=id=>{const n=db.nucleos.find(n=>ref(n)===id);return n?`${n.codigo} ${n.nome||''}`:'Núcleo';};
 const novo=()=>setForm({processo_id:nucleo,status:'Documental',status_operacional:'Em andamento',descricao_cliente:'',observacao_interna:'',previsao:'',orientacao_ia:'',visivel_ia:false,data_atualizacao:new Date().toLocaleDateString('en-CA')});
 return <div className="contem largo"><div className="cabeca"><div><h1>Andamentos</h1><p>Histórico dos núcleos e informações autorizadas para atendimento.</p></div>{acesso.pos&&<button className="btn btn-primario" onClick={novo}>Registrar andamento</button>}</div><EstadoModulo modulo={m}/><CampoCRM nome="Núcleo"><select className="inp" value={nucleo} onChange={e=>{setNucleo(e.target.value);setPromptAberto(false);}}><option value="">Todos os núcleos</option>{db.nucleos.map(n=><option key={n.id} value={ref(n)}>{n.codigo} {n.nome}</option>)}</select></CampoCRM>
 {nucleo&&acesso.pos&&<button className="btn" onClick={()=>{const p=m.dados?.prompts.find(p=>p.id===nucleo);setInstrucao(p?.instrucao||'');setHabilitado(p?.habilitado||false);setPromptAberto(true);}}>Instruções da IA deste núcleo</button>}
 {promptAberto&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(()=>m.dados.prompts.some(p=>p.id===nucleo)?editarCRM('integracao_nucleo_ia',nucleo,{instrucao,habilitado}):criarCRM('integracao_nucleo_ia',{id:nucleo,instrucao,habilitado})))setPromptAberto(false);}}><h2>IA · {nome(nucleo)}</h2><CampoCRM nome="Instrução específica de atendimento"><textarea className="inp" value={instrucao} onChange={e=>setInstrucao(e.target.value)}/></CampoCRM><label><input type="checkbox" checked={habilitado} onChange={e=>setHabilitado(e.target.checked)}/> Autorizar consulta de andamentos pela IA</label><p>Somente a descrição ao cliente dos andamentos marcados como visíveis será disponibilizada. Observações internas ficam fora da resposta.</p><button className="btn btn-primario" disabled={m.ocupado}>Salvar instruções</button></form>}
 {form&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();const {id,...data}=form;data.previsao||=null;if(await m.executar(()=>id?editarCRM('processos_kanban_andamentos',id,data):criarCRM('processos_kanban_andamentos',{...data,origem:'Integração'})))setForm(null);}}><h2>{form.id?'Editar':'Registrar'} andamento</h2><CampoCRM nome="Núcleo"><select className="inp" required disabled={!!form.id} value={form.processo_id} onChange={e=>setForm({...form,processo_id:e.target.value})}><option value="">Selecione</option>{db.nucleos.map(n=><option key={n.id} value={ref(n)}>{n.codigo} {n.nome}</option>)}</select></CampoCRM>{[['status','Status'],['status_operacional','Situação operacional'],['data_atualizacao','Data'],['previsao','Previsão']].map(([k,label])=><CampoCRM nome={label} key={k}><input className="inp" type={['previsao','data_atualizacao'].includes(k)?'date':'text'} required={k!=='previsao'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></CampoCRM>)}{[['descricao_cliente','Descrição autorizada ao cliente'],['observacao_interna','Observação interna'],['orientacao_ia','Orientação da IA para este andamento']].map(([k,label])=><CampoCRM key={k} nome={label}><textarea className="inp" required={k==='descricao_cliente'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></CampoCRM>)}<label><input type="checkbox" checked={!!form.visivel_ia} onChange={e=>setForm({...form,visivel_ia:e.target.checked})}/> Visível para a IA de atendimento</label><div className="crm-acoes"><button className="btn btn-primario" disabled={m.ocupado}>Salvar andamento</button><button className="btn" type="button" onClick={()=>setForm(null)}>Cancelar</button></div></form>}
 {m.dados?.itens.filter(a=>!nucleo||a.processo_id===nucleo).sort((a,b)=>String(b.data_atualizacao).localeCompare(String(a.data_atualizacao))).map(a=><article className="crm-card" key={a.id}><h2>{nome(a.processo_id)}</h2><p>{a.status} · {a.status_operacional} · {a.data_atualizacao}</p><p>{a.descricao_cliente}</p>{a.previsao&&<p>Previsão: {a.previsao}</p>}<p>IA: {a.visivel_ia?'visível':'não autorizado'}</p>{acesso.pos&&<><p>Interno: {a.observacao_interna||'—'}</p><p>Orientação IA: {a.orientacao_ia||'—'}</p><button className="btn" onClick={()=>setForm(Object.fromEntries(['id','processo_id','status','status_operacional','descricao_cliente','observacao_interna','previsao','orientacao_ia','visivel_ia','data_atualizacao'].map(k=>[k,a[k]])))}>Editar andamento</button></>}</article>)}
 </div>;
}
