import {useState} from 'react';
import {Download,Archive,RotateCcw} from 'lucide-react';
import {listarCRM,rpcCRM} from './crm-api.js';
import {useModulo,EstadoModulo} from './modulo-ui.jsx';
import {normalizarCRM} from './crm-regras.js';
import {dataFollowup} from './crm-followup.js';
import {csvArquivo} from './crm-arquivo.js';
import FollowUpCRM from './FollowUpCRM.jsx';
function Registro({r,usuarios,m,nome,historico,atualizar}){
 const [aberto,setAberto]=useState(false),[destino,setDestino]=useState(''),[restaurar,setRestaurar]=useState(false);
 const d=r.dados;
 return <article className="crm-card crm-arquivo-card"><span className="crm-ficha-legenda">{r.restaurado_em?'Restaurado':'Arquivado'} · {d.municipio||d.lead_cidade||'Município não informado'}</span><h3>{d.lead_nome}</h3><p>{d.lead_telefone||'Telefone não informado'}</p><p>Responsáveis: {[d.responsavel_id,...(d.comerciais_adicionais||[])].filter(Boolean).map(nome).join(', ')}</p><p>Status anterior: {d.status}{d.valor_total!=null?` · R$ ${Number(d.valor_total).toLocaleString('pt-BR',{minimumFractionDigits:2})}`:''}</p><p><strong>Motivo:</strong> {r.motivo}</p><p className="ajuda">Arquivado em {dataFollowup(r.arquivado_em)} por {nome(r.arquivado_por)}</p>{r.restaurado_em&&<p className="ajuda">Restaurado em {dataFollowup(r.restaurado_em)} por {nome(r.restaurado_por)}</p>}
 <div className="crm-acoes"><button className="btn" onClick={()=>setAberto(a=>!a)}>{aberto?'Fechar histórico':'Consultar histórico'}</button>{!r.restaurado_em&&<button className="btn" disabled={m.ocupado} onClick={()=>setRestaurar(a=>!a)}><RotateCcw size={15}/>Retomar venda</button>}</div>
 {restaurar&&!r.restaurado_em&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(()=>rpcCRM('integracao_crm_arquivar_lead',{p_card:r.card_id,p_arquivar:false,p_responsavel:destino}))){setRestaurar(false);atualizar();}}}><label>Comercial para retomar a venda<select className="inp" aria-label="Comercial para retomar a venda" value={destino} required onChange={e=>setDestino(e.target.value)}><option value="">Selecione</option>{usuarios.filter(u=>u.ativo!==false&&u.tipoERP==='Comercial').map(u=><option key={u.id} value={u.erpRef||u.id}>{u.nome}</option>)}</select></label><p className="ajuda">O lead voltará como Cliente novo. Agende um novo FollowUp ao retomar o contato.</p><button className="btn btn-primario" disabled={m.ocupado||!destino}>Restaurar lead</button></form>}
 {aberto&&<div className="crm-arquivo-historico">{historico(r.card_id)}<FollowUpCRM card={{id:r.card_id}} usuarios={usuarios} atualizar={m.atualizar} encerrado mensagemEncerrado="Histórico preservado para consulta da diretoria."/>{(d.tarefas||[]).length>0&&<details><summary>Tarefas no momento do arquivamento ({d.tarefas.length})</summary>{d.tarefas.map(t=><p key={t.id}>{t.titulo} · {t.prazo} · {t.concluida?'Concluída':'Pendente ao arquivar'}</p>)}</details>}</div>}
 </article>;
}
export default function ArquivoCRM({usuarios,atualizar,historico}){
 const m=useModulo(()=>listarCRM('integracao_crm_arquivo'),[],['crm']),[busca,setBusca]=useState(''),[situacao,setSituacao]=useState('arquivados');
 const nome=id=>usuarios.find(u=>(u.erpRef||u.id)===id)?.nome||'Usuário registrado';
 const rows=(m.dados||[]).filter(r=>(situacao==='todos'||(situacao==='restaurados'?!!r.restaurado_em:!r.restaurado_em))&&normalizarCRM([r.dados.lead_nome,r.dados.lead_telefone,r.dados.municipio,r.dados.lead_cidade,r.motivo,nome(r.dados.responsavel_id)].join(' ')).includes(normalizarCRM(busca))).sort((a,b)=>b.arquivado_em.localeCompare(a.arquivado_em));
 function exportar(){const url=URL.createObjectURL(new Blob([csvArquivo(rows,nome)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`arquivo-crm-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="crm-arquivo"><div className="cabeca"><div><h2><Archive size={22}/>Arquivo do CRM</h2><p>Leads retirados da lista, preservados para consulta e futuras vendas.</p></div><button className="btn" disabled={!rows.length} onClick={exportar}><Download size={16}/>Exportar relatório</button></div><div className="crm-acoes"><input className="inp" aria-label="Buscar no arquivo do CRM" placeholder="Nome, telefone, município, responsável ou motivo" value={busca} onChange={e=>setBusca(e.target.value)}/><select className="inp" aria-label="Situação no arquivo" value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="arquivados">Arquivados</option><option value="restaurados">Restaurados</option><option value="todos">Todos os registros</option></select></div><EstadoModulo modulo={m}/>{m.dados&&<><p className="ajuda">{rows.length} registro(s). O relatório considera os filtros acima.</p><div className="crm-grade">{rows.map(r=><Registro key={r.id} r={r} usuarios={usuarios} m={m} nome={nome} historico={historico} atualizar={atualizar}/>)}</div>{!rows.length&&<p>Nenhum lead encontrado neste filtro.</p>}</>}</section>;
}
