import {useState} from 'react';
import {ShieldCheck,ChevronLeft,ChevronRight,RefreshCw} from 'lucide-react';
import {acessoCRM} from './crm-regras.js';
import {lerTabela} from './dados-compartilhados.js';
import {useModulo,EstadoModulo} from './modulo-ui.jsx';
import {mesAtualAcessos,mudarMes,limitesMes,linhasAcessos,horaAcesso} from './acessos-regras.js';
import './controle-acessos.css';
export default function ControleAcessos({usuario}){
 const admin=acessoCRM(usuario).admin;
 const [mes,setMes]=useState(mesAtualAcessos),[pessoa,setPessoa]=useState('');
 const m=useModulo(async()=>{if(!admin)return [];const {inicio,fim}=limitesMes(mes);return lerTabela('integracao_acessos','id,usuario_id,usuario_nome,evento,motivo,ocorrido_em',`&ocorrido_em=gte.${encodeURIComponent(inicio)}&ocorrido_em=lt.${encodeURIComponent(fim)}`);},[admin,mes,usuario?.id]);
 if(!admin)return null;
 const eventos=m.dados||[],linhas=linhasAcessos(eventos,mes,pessoa),usuarios=[...new Map(eventos.map(e=>[e.usuario_id,e.usuario_nome])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'));
 const filtrados=eventos.filter(e=>!pessoa||e.usuario_id===pessoa);
 const trocar=valor=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(valor)){setMes(valor);setPessoa('');}};
 return <section className="controle-acessos"><header><div><h2><ShieldCheck size={23}/>Controle de acessos</h2><p>Entradas e saídas por usuário e dia · horário de Brasília.</p></div><button className="btn" onClick={m.atualizar}><RefreshCw size={16}/>Atualizar</button></header><div className="acessos-filtros"><button className="btn" aria-label="Mês anterior" onClick={()=>trocar(mudarMes(mes,-1))}><ChevronLeft size={18}/></button><label>Mês de referência<input className="inp" type="month" value={mes} onChange={e=>trocar(e.target.value)}/></label><button className="btn" aria-label="Próximo mês" onClick={()=>trocar(mudarMes(mes,1))}><ChevronRight size={18}/></button><button className="btn" onClick={()=>trocar(mesAtualAcessos())}>Mês atual</button><label>Usuário<select className="inp" value={pessoa} onChange={e=>setPessoa(e.target.value)}><option value="">Todos os usuários</option>{usuarios.map(([id,nome])=><option key={id} value={id}>{nome}</option>)}</select></label></div><EstadoModulo modulo={m}/>{m.dados&&<><div className="acessos-resumo"><span><strong>{filtrados.filter(e=>e.evento==='login').length}</strong> logins</span><span><strong>{filtrados.filter(e=>e.evento==='logout').length}</strong> logouts</span><span><strong>{new Set(filtrados.map(e=>e.usuario_id)).size}</strong> usuários</span></div><div className="acessos-tabela"><table><caption>Acessos de {mes.split('-').reverse().join('/')}</caption><thead><tr><th scope="col">Dia</th><th scope="col">Usuário</th><th scope="col">Login · entradas</th><th scope="col">Logout · saídas</th></tr></thead><tbody>{linhas.map(l=><tr key={`${l.dia}:${l.usuario_id}`}><td>{l.dia.split('-').reverse().join('/')}</td><th scope="row">{l.nome}</th><td>{l.login.length?l.login.map(e=><span className="acesso-hora entrada" key={e.id}>{horaAcesso(e.ocorrido_em)}</span>):'—'}</td><td>{l.logout.length?l.logout.map(e=><span className="acesso-hora saida" key={e.id}>{horaAcesso(e.ocorrido_em)}{e.motivo==='inatividade'?' · Inatividade':''}</span>):'Sem saída registrada neste dia'}</td></tr>)}{!linhas.length&&<tr><td colSpan={4} className="acessos-vazio">Nenhum acesso registrado neste mês para o filtro selecionado.</td></tr>}</tbody></table></div></>}<p className="acessos-nota">Histórico disponível a partir da implantação deste controle. Saídas pelo botão Sair e por inatividade são registradas quando há conexão. Fechar a aba ou acessar no modo offline não confirma um logout. Ausência de saída não significa que o usuário está online.</p></section>;
}
