import {useState} from 'react';
import {ClipboardList,Plus,Trash2,Save} from 'lucide-react';
import {InfraestruturaPRF} from './FormulariosNucleoPRF.jsx';
import {SECOES_NUI,CAMPOS_MEDIDA,dadosNUI,salvarDadosNUI} from './dados-nui.js';
import './dados-nui.css';
function Campos({campos,dados,onChange,unidades,disabled}){
 return <div className="nui-campos">{campos.map(c=>c.tipo==='lista'?<div className="nui-largura" key={c.id}><Lista titulo={c.rotulo} campos={c.campos} itens={dados[c.id]||[]} onChange={v=>onChange({...dados,[c.id]:v})} unidades={unidades} disabled={disabled}/></div>:<label key={c.id} className={c.tipo==='textarea'?'nui-largura':''}>{c.rotulo}{c.tipo==='textarea'?<textarea className="inp" rows={3} disabled={disabled} value={dados[c.id]||''} onChange={e=>onChange({...dados,[c.id]:e.target.value})}/>:c.tipo==='unidade'?<select className="inp" disabled={disabled} value={dados[c.id]||''} onChange={e=>onChange({...dados,[c.id]:e.target.value})}><option value="">Sem vínculo selecionado</option>{dados[c.id]&&!unidades.some(u=>u.id===dados[c.id])&&<option value={dados[c.id]}>Unidade anteriormente vinculada</option>}{unidades.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select>:<input className="inp" type={c.tipo} disabled={disabled} value={dados[c.id]||''} onChange={e=>onChange({...dados,[c.id]:e.target.value})}/>}</label>)}</div>;
}
function Lista({titulo,campos,itens,onChange,unidades,disabled}){
 return <section className="nui-lista"><div className="nui-lista-cabeca"><h3>{titulo} <small>({itens.length})</small></h3>{!disabled&&<button type="button" className="btn btn-sm" onClick={()=>onChange([...itens,{id:crypto.randomUUID()}])}><Plus size={15}/>Adicionar</button>}</div>{!itens.length&&<p className="ajuda">Nenhum registro informado.</p>}{itens.map((item,i)=><div className="nui-item" key={item.id||i}><div className="nui-item-cabeca"><strong>Registro {i+1}{item.nome||item.numero?` · ${item.nome||item.numero}`:''}</strong>{!disabled&&<button type="button" className="btn btn-sm" aria-label={`Remover registro ${i+1} de ${titulo}`} onClick={()=>{if(window.confirm('Remover este registro? A remoção será aplicada ao salvar Dados NUI.'))onChange(itens.filter((_,j)=>j!==i));}}><Trash2 size={14}/>Remover</button>}</div><Campos campos={campos} dados={item} onChange={v=>onChange(itens.map((x,j)=>j===i?v:x))} unidades={unidades} disabled={disabled}/></div>)}</section>;
}
export default function DadosNUI({n,municipio,unidades,perm,mutar,setToast,objetos,instrumentos}){
 const [base,setBase]=useState(()=>dadosNUI(n)),[draft,setDraft]=useState(()=>dadosNUI(n)),[secao,setSecao]=useState('matriculas'),[salvando,setSalvando]=useState(false),[erro,setErro]=useState('');
 const pode=perm.estrutura||perm.prf||perm.juridico||perm.campo;
 const sujo=JSON.stringify(base)!==JSON.stringify(draft),grupo=SECOES_NUI.find(s=>s.id===secao);
 const set=(k,v)=>setDraft(d=>({...d,[k]:v}));
 const salvar=async()=>{if(!pode||salvando)return;setErro('');setSalvando(true);try{await mutar(db=>{const atual=db.nucleos.find(x=>x.id===n.id);if(!atual)throw new Error('Núcleo indisponível.');salvarDadosNUI(atual,base,draft);return db;},'Dados NUI atualizados',{nucleoId:n.id,municipioId:n.municipioId});setBase(structuredClone(draft));setToast('Dados NUI salvos. Os campos estão disponíveis para o PRF.');}catch(e){setErro(e.message);}finally{setSalvando(false);}};
 const listaOp=(k,titulo,opcoes)=><label>{titulo}<select className="inp" disabled={!pode} value={draft[k]||''} onChange={e=>set(k,e.target.value)}><option value="">Não informado</option>{draft[k]&&!opcoes.includes(draft[k])&&<option>{draft[k]}</option>}{opcoes.map(o=><option key={o}>{o}</option>)}</select></label>;
 return <section className="dados-nui"><header><div><h2><ClipboardList size={22}/>Dados NUI</h2><p>Informações do núcleo para composição do PRF.</p></div>{pode&&<button className="btn btn-primario" disabled={!sujo||salvando} onClick={salvar}><Save size={16}/>{salvando?'Salvando…':'Salvar Dados NUI'}</button>}</header>{erro&&<p role="alert" className="crm-erro">{erro}</p>}{!pode&&<p>Consulta dos dados do núcleo. Edição disponível às equipes responsáveis.</p>}<nav className="nui-secoes" aria-label="Seções dos Dados NUI">{SECOES_NUI.map((s,i)=><button key={s.id} className={`btn ${secao===s.id?'btn-primario':''}`} aria-pressed={secao===s.id} onClick={()=>setSecao(s.id)}><span>{i+1}</span>{s.titulo}</button>)}</nav><div className="nui-conteudo"><h2>{grupo.titulo}</h2><p className="ajuda">{grupo.descricao}</p>{grupo.listas.map(l=><Lista key={l.id} titulo={l.titulo} campos={l.campos} itens={draft[l.id]||[]} onChange={v=>set(l.id,v)} unidades={unidades} disabled={!pode}/>)}{secao==='medidas'&&<><Campos campos={CAMPOS_MEDIDA} dados={draft.medida||{}} onChange={v=>set('medida',v)} unidades={unidades} disabled={!pode}/><div className="nui-separador"><InfraestruturaPRF dados={draft.infra||{}} onChange={v=>set('infra',v)} disabled={!pode}/></div><h3>Situação e enquadramento</h3><div className="nui-campos">{listaOp('situacao','Situação',['Ativo','Suspenso','Cancelado','Concluído'])}{listaOp('modalidade','Modalidade predominante',['REURB-S','REURB-E','Mista'])}{listaOp('objeto','Objeto',objetos)}{listaOp('instrumento','Instrumento',instrumentos)}{listaOp('zona','Zona',['Área Urbana','Área Rural'])}{listaOp('macrozona','Macrozona',(municipio?.prf?.macrozonas||[]).map(m=>m.nome).filter(Boolean))}</div>{!municipio?.prf?.macrozonas?.length&&<p className="ajuda">Cadastre as macrozonas em Municípios → Dados do PRF para selecionar o vínculo.</p>}<Campos campos={[{id:'situacaoDescricao',rotulo:'Descrição da situação',tipo:'textarea'}]} dados={draft} onChange={setDraft} unidades={unidades} disabled={!pode}/></>}</div>{sujo&&<p role="status" className="nui-aviso">Há alterações não salvas. Salve antes de sair desta aba.</p>}</section>;
}
