const campo=(id,rotulo,tipo='text')=>({id,rotulo,tipo});
const texto=(id,rotulo)=>campo(id,rotulo,'textarea');
const proprietario=[campo('nome','Nome / razão social'),campo('cpfCnpj','CPF / CNPJ'),campo('registro','Registro / averbação'),campo('fracao','Fração / participação'),texto('qualificacao','Qualificação'),texto('observacoes','Observações')];
const unidade=[campo('unidadeId','Unidade vinculada','unidade'),texto('descricao','Descrição / justificativa'),texto('providencias','Providências')];
export const SECOES_NUI=[
 {id:'matriculas',titulo:'Matrículas de origem',descricao:'Matrículas, proprietários registrais e áreas remanescentes.',listas:[{id:'matriculas',titulo:'Matrículas',campos:[campo('numero','Número da matrícula'),campo('cartorio','Cartório / comarca'),campo('livro','Livro'),campo('dataCertidao','Data da certidão','date'),campo('area','Área registrada (m²)'),texto('descricao','Descrição registral'),texto('onus','Ônus / averbações'),{id:'proprietarios',rotulo:'Proprietários registrais',tipo:'lista',campos:proprietario},{id:'remanescentes',rotulo:'Áreas remanescentes',tipo:'lista',campos:[campo('nome','Identificação'),campo('area','Área (m²)'),campo('perimetro','Perímetro (m)'),texto('memorial','Memorial / descrição')]},texto('observacoes','Observações')]}]},
 {id:'dominial',titulo:'Cadeia dominial e especialização',descricao:'Histórico dominial e identificação expressa das unidades sem especialização.',listas:[{id:'proprietariosCadeiaDominial',titulo:'Cadeia dominial',campos:[...proprietario,campo('matricula','Matrícula de referência'),campo('data','Data do ato','date'),campo('titulo','Título / ato de aquisição')]},{id:'unidadesSemEspecializacao',titulo:'Unidades sem especialização',campos:unidade}]},
 {id:'usucapiao',titulo:'Áreas usucapidas',descricao:'Áreas reconhecidas e seus documentos de referência.',listas:[{id:'areasUsucapidas',titulo:'Áreas usucapidas',campos:[campo('nome','Identificação da área'),campo('unidadeId','Unidade vinculada','unidade'),campo('area','Área (m²)'),campo('matricula','Matrícula'),campo('beneficiario','Beneficiário'),campo('processo','Processo / procedimento'),campo('data','Data do reconhecimento','date'),texto('documento','Documento / referência'),texto('memorial','Memorial / descrição')]}]},
 {id:'equipe',titulo:'Equipe técnica e revisões',descricao:'Profissionais responsáveis e histórico das versões do PRF.',listas:[{id:'equipeTecnica',titulo:'Equipe técnica',campos:[campo('nome','Nome'),campo('profissao','Profissão'),campo('funcao','Função no PRF'),campo('conselho','Conselho profissional'),campo('registro','Registro profissional'),campo('art','ART / RRT / TRT'),campo('data','Data de emissão','date')]},{id:'versoes',titulo:'Revisões do PRF',campos:[campo('numero','Versão / revisão'),campo('data','Data','date'),campo('responsavel','Responsável'),texto('descricao','Alterações realizadas')]}]},
 {id:'restricoes',titulo:'Rodovias e cursos d’água',descricao:'Relacione as unidades atingidas e os estudos correspondentes.',listas:[{id:'unidadesAtingidasRodovia',titulo:'Unidades atingidas por rodovia',campos:[...unidade,campo('rodovia','Rodovia'),campo('orgao','Órgão responsável'),campo('faixaDominio','Faixa de domínio (m)'),campo('faixaNaoEdificavel','Faixa não edificável (m)'),campo('areaAtingida','Área atingida (m²)'),texto('estudo','Estudo / documento de referência')]},{id:'unidadesAtingidasCursoAgua',titulo:'Unidades atingidas por curso d’água',campos:[...unidade,campo('cursoAgua','Curso d’água'),campo('largura','Largura do curso (m)'),campo('faixaApp','Faixa de APP (m)'),campo('areaAtingida','Área atingida (m²)'),texto('estudo','Estudo ambiental / documento')]}]},
 {id:'medidas',titulo:'Medidas, infraestrutura e enquadramento',descricao:'Medidas propostas, infraestrutura e situação geral do núcleo.',listas:[]}
];
export const CAMPOS_MEDIDA=[campo('nome','Identificação da medida'),campo('tipo','Tipo de medida'),texto('descricao','Descrição'),campo('responsavel','Responsável'),campo('prazo','Prazo'),texto('fundamentacao','Fundamentação / estudo'),{id:'unidades',rotulo:'Unidades relacionadas',tipo:'lista',campos:unidade}];
export const CHAVES_NUI=[...SECOES_NUI.flatMap(s=>s.listas.map(l=>l.id)),'medida','infra','situacao','situacaoDescricao','modalidade','objeto','instrumento','macrozona','zona'];
export function dadosNUI(n){return Object.fromEntries(CHAVES_NUI.filter(k=>n[k]!==undefined).map(k=>[k,structuredClone(n[k])]));}
export function salvarDadosNUI(atual,base,draft){
 const mudancas=CHAVES_NUI.filter(k=>JSON.stringify(base[k])!==JSON.stringify(draft[k]));
 for(const k of mudancas)if(JSON.stringify(atual[k])!==JSON.stringify(base[k]))throw new Error('Este núcleo foi alterado por outra operação. Reabra Dados NUI antes de salvar.');
 for(const k of mudancas)atual[k]=structuredClone(draft[k]);
 return atual;
}
