import {useEffect,useRef,useState} from 'react';
import {BarChart3} from 'lucide-react';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {rpcCRM} from './crm-api.js';
import {diaPonto} from './ponto-api.js';
import {dataFollowup,horasFollowup} from './crm-followup.js';
import {tokenTempoReal} from './dados-compartilhados.js';
export default function DashboardCRM({usuarios}){
 const hoje=diaPonto(),[inicio,setInicio]=useState(hoje.slice(0,8)+'01'),[fim,setFim]=useState(hoje),[agente,setAgente]=useState(''),[sincronizando,setSincronizando]=useState(false),[aviso,setAviso]=useState(''),parar=useRef(false);
 useEffect(()=>()=>{parar.current=true;},[]);
 const valido=inicio&&fim&&fim>=inicio&&(new Date(fim)-new Date(inicio))/86400000<=366;
 const m=useModulo(()=>valido?rpcCRM('integracao_crm_dashboard',{p_inicio:inicio,p_fim:fim}):Promise.reject(Error('Selecione um período válido de até 366 dias.')),[inicio,fim],['crm']);
 const sincronizar=async()=>{if(sincronizando)return;setSincronizando(true);setAviso('Consultando mensagens das conversas já vinculadas ao CRM…');parar.current=false;let cursor=null,total=0;try{const token=await tokenTempoReal();if(!token)throw Error('Entre novamente na sua conta.');do{const r=await fetch('/api/crm-chatwoot-sincronizar',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({cursor}),signal:AbortSignal.timeout(120000)});const d=await r.json();if(!r.ok)throw Error(d.message||'Não foi possível atualizar o Chatwoot.');total+=d.mensagens;cursor=d.cursor;setAviso(`${total} mensagens conferidas.${cursor?' Continuando…':' Histórico registrado atualizado.'}`);}while(cursor&&!parar.current);if(cursor)setAviso(`Atualização interrompida após ${total} mensagens. Os registros já conferidos foram preservados.`);}catch(e){setAviso(e.message);}finally{setSincronizando(false);m.atualizar();}};
 const rows=(m.dados?.agentes||[]).filter(a=>!agente||a.id===agente),c=m.dados?.cobertura;
 return <section className="crm-dashboard"><header><h2><BarChart3 size={22}/> Dashboard comercial</h2><p>Resultados por comercial e acompanhamento dos próximos contatos.</p></header>
 <div className="crm-dashboard-filtros"><CampoCRM nome="Início do período"><input className="inp" type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></CampoCRM><CampoCRM nome="Fim do período"><input className="inp" type="date" value={fim} onChange={e=>setFim(e.target.value)}/></CampoCRM><CampoCRM nome="Comercial do dashboard"><select className="inp" value={agente} onChange={e=>setAgente(e.target.value)}><option value="">Todos os comerciais</option>{m.dados?.agentes.map(a=><option key={a.id} value={a.id}>{a.nome}{a.ativo?'':' (inativo)'}</option>)}</select></CampoCRM><button className="btn" onClick={m.atualizar}>Atualizar indicadores</button><button className="btn" disabled={sincronizando} onClick={sincronizar}>Conferir histórico no Chatwoot</button>{sincronizando&&<button className="btn" onClick={()=>{parar.current=true;setAviso('Parando após a página em andamento…');}}>Parar atualização</button>}</div>
 {aviso&&<p role="status">{aviso}</p>}<EstadoModulo modulo={m}/>
 {c&&<div className="crm-dashboard-cobertura"><strong>Chatwoot no período: {c.conversas} conversas · {c.mensagens} mensagens registradas</strong><p>{c.saidas_sem_autoria} mensagens de saída sem autoria confirmada · {c.humanas_sem_vinculo} mensagens humanas sem vínculo com usuário · {c.automaticas} automáticas. Última mensagem registrada: {dataFollowup(c.ultima_mensagem)}.</p><small>O painel considera o histórico disponível no Integração. “Conferir histórico” lê o Chatwoot e atualiza as conversas já vinculadas, sem enviar mensagens.</small></div>}
 <div className="crm-dashboard-grade">{rows.map(a=><article className="crm-dashboard-agente" key={a.id}><h3>{a.nome}{!a.ativo&&<small> · Inativo</small>}</h3><dl>{[
 ['Clientes na carteira',a.carteira],['Movimentações realizadas',a.movimentacoes],['Conversões em contrato',a.conversoes],['Clientes perdidos',a.perdas],['Conversão entre desfechos',Number(a.conversoes)+Number(a.perdas)?`${Math.round(100*a.conversoes/(Number(a.conversoes)+Number(a.perdas)))}%`:'—'],
 ['FollowUps feitos',a.followups_feitos],['Feitos no prazo',a.no_prazo],['Tempo médio de FollowUp',horasFollowup(a.tempo_medio_horas)],['Atraso médio',horasFollowup(a.atraso_medio_horas)],['Pendentes agora',a.pendentes],['Atrasados agora',a.atrasados],['Clientes sem próximo prazo',a.sem_followup],['Atendimentos no Chatwoot',a.atendimentos_chatwoot],['Mensagens humanas enviadas',a.mensagens_enviadas],['Conversas da carteira',a.conversas_carteira],['Atendimentos manuais',a.atendimentos_manuais]
 ].map(([n,v])=><div key={n} className={n==='Atrasados agora'&&Number(v)>0?'crm-dashboard-alerta':''}><dt>{n}</dt><dd>{v}</dd></div>)}</dl></article>)}</div>
 {m.dados&&!rows.length&&<p>Nenhum comercial cadastrado neste filtro.</p>}
 <details className="crm-dashboard-definicoes"><summary>Como os indicadores são calculados</summary><p>Movimentações: mudanças de etapa realizadas pelo comercial no período. Conversões e perdas: clientes distintos por evento, atribuídos ao responsável principal no momento da mudança. Contrato → Cliente ativo não conta como nova conversão. A taxa usa conversões ÷ (conversões + perdas); um cliente recuperado pode constar nos dois resultados do período.</p><p>FollowUps feitos e tempos médios usam quem registrou a conclusão. Tempo médio: agendamento até conclusão; atraso médio inclui zero para conclusões no prazo. Pendentes, atrasados e carteira mostram a situação atual. Clientes compartilhados aparecem na carteira de cada responsável.</p><p>Atendimento Chatwoot: conversa distinta em que o comercial enviou mensagem humana e pública no período, identificado pelo ID do remetente. Mensagens automáticas, notas internas e autores desconhecidos não contam como atendimento do comercial. Conversas da carteira incluem todos os autores e podem aparecer em mais de uma carteira.</p></details>
 {m.dados&&<section className="crm-dashboard-movimentos"><h3>Últimas movimentações no período</h3><p className="ajuda">Até 100 movimentações mais recentes; os indicadores acima consideram todo o período.</p>{m.dados.movimentacoes.filter(x=>!agente||x.autor_id===agente).map((x,i)=><article key={`${x.registro_id}-${x.created_at}-${i}`}><strong>{x.nome||x.lead_nome||'Cliente'}</strong><span>{x.anterior} → {x.atual}</span><small>{dataFollowup(x.created_at)} · {usuarios.find(u=>(u.erpRef||u.id)===x.autor_id)?.nome||'Sistema / usuário registrado'}</small></article>)}</section>}
 </section>;
}
