import {useState} from 'react';
import {Landmark,Pencil,FileDown,Upload,ChevronRight,Check,RefreshCw} from 'lucide-react';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {lerTabela} from './dados-compartilhados.js';
import {rpcCRM} from './crm-api.js';
import {permissoes} from './permissoes.js';
import {dinheiro,dataFinanceira,valorReal,validarLinhaBoleto} from './financeiro-regras.js';
import {relatorioFinanceiroPDF} from './financeiro-pdf.js';
import ImportarFinanceiro from './ImportarFinanceiro.jsx';
import './financeiro.css';
const hoje=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
function Resumo({itens}){itens=itens.filter(p=>p.status!=='Cancelado');return <div className="fin-resumo">{[['Parcelas',itens.length],['Previsto',dinheiro(itens.reduce((s,p)=>s+valorReal(p),0))],['Recebido',dinheiro(itens.reduce((s,p)=>s+Number(p.valor_liquidado||0),0))],['Pagas',itens.filter(p=>p.status==='Pago').length]].map(([n,v])=><div className="card" key={n}><span>{n}</span><strong>{v}</strong></div>)}</div>;}
export function FinanceiroCliente({p,usuario}){
 const id=p.financeiroRef||p.cliente_id,operar=permissoes(usuario).financeiro;
 const m=useModulo(async()=>{if(!id)return {cliente:null,parcelas:[]};const [cs,parcelas]=await Promise.all([lerTabela('fin_receb_clientes','*',`&id=eq.${id}`),lerTabela('fin_receb_parcelas','*',`&cliente_id=eq.${id}&ativo=eq.true`)]);return {cliente:cs[0],parcelas:parcelas.sort((a,b)=>a.vencimento.localeCompare(b.vencimento)||a.numero-b.numero)};},[id],['financeiro','clientes']);
 const [editar,setEditar]=useState(null),[importar,setImportar]=useState(false),[erro,setErro]=useState(''),[vencimentoEntrada,setVencimentoEntrada]=useState('');
 if(!id)return <p className="ajuda">Este morador ainda não possui vínculo financeiro. Vincule o cadastro existente antes de registrar pagamentos.</p>;
 const parcelas=m.dados?.parcelas||[];
 return <section className="fin-cliente"><div className="fin-cabeca"><div><h2><Landmark size={22}/> Financeiro do cliente</h2><h3 style={{fontSize:20,fontWeight:700,marginTop:8}}>{m.dados?.cliente?.nome}</h3><p>{m.dados?.cliente?.codigo}</p><p>Mesmas parcelas e baixas do Financeiro Integral · {operar?'Acesso operacional':'Somente consulta'}</p></div><div className="fin-acoes"><button className="btn" onClick={m.atualizar}><RefreshCw size={16}/>Atualizar</button><button className="btn" disabled={!m.dados?.cliente} onClick={async()=>{try{const doc=await relatorioFinanceiroPDF(m.dados.cliente,parcelas);doc.save(`financeiro-${m.dados.cliente.codigo||id}.pdf`);}catch(e){setErro(e.message);}}}><FileDown size={16}/>Gerar relatório PDF</button>{operar&&<button className="btn" onClick={()=>setImportar(true)}><Upload size={16}/>Enviar boletos ou carnê</button>}</div></div>
 <EstadoModulo modulo={m}/>{erro&&<p role="alert">{erro}</p>}<Resumo itens={parcelas}/>
 {importar&&<ImportarFinanceiro modo="boletos" cliente={m.dados?.cliente} fechar={()=>setImportar(false)} salvo={()=>{setImportar(false);m.atualizar();}}/>}
 {editar&&<EditarParcela parcela={editar} ocupado={m.ocupado} cancelar={()=>setEditar(null)} salvar={async dados=>{if(await m.executar(()=>rpcCRM('integracao_financeiro_editar',{p_id:editar.id,p_versao:editar.versao,p_dados:dados})))setEditar(null);}}/>}
 <div className="rolagem"><table className="tab fin-tabela"><thead><tr>{['Parcela / entrada','Vencimento','Valor base','Juros','Multa','Valor real','Valor pago','Pagamento','Boleto','Ações'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{parcelas.map(a=><tr key={a.id}><td>{a.tipo==='Entrada'?'Entrada':`Parcela ${a.numero}`}</td><td>{dataFinanceira(a.vencimento)}</td><td>{dinheiro(a.valor_previsto)}</td><td>{dinheiro(a.juros)}</td><td>{dinheiro(a.multa)}</td><td>{dinheiro(valorReal(a))}</td><td>{dinheiro(a.valor_liquidado)}</td><td>{a.status}<small>{dataFinanceira(a.pago_em)}</small></td><td className="fin-codigo">{a.linha_digitavel||a.nosso_numero||a.documento||'Não informado'}</td><td>{operar&&<div className="fin-acoes"><button className="btn btn-sm" disabled={m.ocupado} aria-label={`Editar parcela ${a.numero}`} onClick={()=>setEditar(a)}><Pencil size={15}/></button><button className="btn btn-sm" disabled={m.ocupado} onClick={()=>{if(a.status==='Pago'){if(confirm('Desmarcar esta parcela como paga? A alteração será compartilhada com o Financeiro Integral.'))m.executar(()=>rpcCRM('integracao_financeiro_editar',{p_id:a.id,p_versao:a.versao,p_dados:{status:'Pendente',pago_em:null,valor_liquidado:0}}));}else setEditar({...a,status:'Pago',pago_em:hoje(),valor_liquidado:valorReal(a)});}}><Check size={15}/>{a.status==='Pago'?'Desmarcar pago':'Marcar pago'}</button></div>}</td></tr>)}</tbody></table></div>
 {m.dados&&!parcelas.length&&<p>Nenhuma parcela cadastrada no Financeiro Integral para este cliente.</p>}
 {Number(m.dados?.cliente?.valor_entrada)>0&&!parcelas.some(a=>a.tipo==='Entrada')&&<p className="ajuda">Entrada prevista no contrato: {dinheiro(m.dados.cliente.valor_entrada)}. Não há lançamento identificado como Entrada; classifique a parcela correspondente pelo lápis, após conferir.{operar&&<span className="fin-acoes"><label>Vencimento da entrada<input className="inp" type="date" value={vencimentoEntrada} onChange={e=>setVencimentoEntrada(e.target.value)}/></label><button className="btn" disabled={!vencimentoEntrada||m.ocupado} onClick={()=>{if(confirm("Cadastrar a entrada como uma cobrança separada? Confirme que esse valor não está incluído em outra parcela, para não duplicar a cobrança."))m.executar(()=>rpcCRM("integracao_financeiro_criar_entrada",{p_cliente:id,p_valor:Number(m.dados.cliente.valor_entrada),p_vencimento:vencimentoEntrada}));}}>Cadastrar entrada separada</button></span>}</p>}
 </section>;
}
function EditarParcela({parcela,ocupado,cancelar,salvar}){
 const [form,setForm]=useState(()=>Object.fromEntries(['vencimento','valor_previsto','juros','multa','linha_digitavel','status','pago_em','valor_liquidado','tipo'].map(k=>[k,parcela[k]??(['juros','multa','valor_liquidado'].includes(k)?0:'')]))),[erro,setErro]=useState('');const campo=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <form className="card fin-editor" onSubmit={e=>{e.preventDefault();setErro('');if(form.linha_digitavel&&!validarLinhaBoleto(form.linha_digitavel)){setErro('Confira a linha digitável bancária de 47 dígitos. Os dígitos verificadores não conferem.');return;}salvar({...form,...Object.fromEntries(['valor_previsto','juros','multa','valor_liquidado'].map(k=>[k,Number(form[k])])),pago_em:form.pago_em||null});}}><h3>Editar parcela {parcela.numero}</h3><div className="fin-campos"><CampoCRM nome="Tipo"><select className="inp" value={form.tipo} onChange={e=>campo('tipo',e.target.value)}><option>Parcela</option><option>Entrada</option></select></CampoCRM><CampoCRM nome="Vencimento"><input className="inp" type="date" required value={form.vencimento} onChange={e=>campo('vencimento',e.target.value)}/></CampoCRM>{[['valor_previsto','Valor base (R$)'],['juros','Juros (R$)'],['multa','Multa (R$)'],['valor_liquidado','Valor pago (R$)']].map(([k,n])=><CampoCRM key={k} nome={n}><input className="inp" type="number" min="0" step="0.01" required value={form[k]} onChange={e=>campo(k,e.target.value)}/></CampoCRM>)}<CampoCRM nome="Situação"><select className="inp" value={form.status} onChange={e=>campo('status',e.target.value)}>{['Pendente','Pago','Parcial','Inadimplente','Cancelado'].map(s=><option key={s}>{s}</option>)}</select></CampoCRM><CampoCRM nome="Data do pagamento"><input className="inp" type="date" required={form.status==='Pago'} value={form.pago_em||''} onChange={e=>campo('pago_em',e.target.value)}/></CampoCRM></div><CampoCRM nome="Linha digitável do boleto"><input className="inp" value={form.linha_digitavel} onChange={e=>campo('linha_digitavel',e.target.value)}/></CampoCRM><p>Valor real: {dinheiro(valorReal(form))} (valor base + juros + multa).</p>{erro&&<p role="alert">{erro}</p>}<div className="fin-acoes"><button className="btn btn-primario" disabled={ocupado}>Salvar parcela</button><button className="btn" type="button" onClick={cancelar}>Cancelar</button></div></form>;
}
export default function Financeiro({db,usuario}){
 const [mes,setMes]=useState(()=>hoje().slice(0,7)),[municipio,setMunicipio]=useState(''),[remessa,setRemessa]=useState(null),[nucleo,setNucleo]=useState(null),[cliente,setCliente]=useState(null),[importar,setImportar]=useState(false);
 const operar=permissoes(usuario).financeiro;
 const m=useModulo(async()=>{const [ano,mm]=mes.split('-').map(Number),fim=new Date(Date.UTC(ano,mm,1)).toISOString().slice(0,10);const rows=[];for(let offset=0;;offset+=500){const parte=await rpcCRM('integracao_financeiro_resumo?order=municipio_id,remessa_id,nucleo_id&limit=500&offset='+offset,{p_inicio:mes+'-01',p_fim:fim});rows.push(...parte);if(parte.length<500)return rows;}},[mes],['financeiro','clientes']);
 const rows=(m.dados||[]).filter(r=>(!municipio||r.municipio_id===municipio)&&(remessa===null||String(r.remessa_id||'')===remessa)&&(nucleo===null||r.nucleo_id===nucleo));
 const grupo=municipio?(remessa===null?'remessa_id':'nucleo_id'):'municipio_id',somas=new Map();for(const r of rows){const id=String(r[grupo]||''),v=somas.get(id)||{id,clientes:0,parcelas:0,pagas:0,previsto:0,recebido:0};for(const k of ['clientes','parcelas','pagas','previsto','recebido'])v[k]+=Number(r[k]||0);somas.set(id,v);}
 const nome=id=>grupo==='municipio_id'?db.municipios.find(x=>x.id===id)?.nome||'Município':grupo==='remessa_id'?db.remessas.find(x=>x.id===id)?.titulo||db.remessas.find(x=>x.id===id)?.codigo||`Remessa ${db.remessas.find(x=>x.id===id)?.numero||'sem vínculo'}`:id?db.nucleos.find(x=>x.id===id)?.nome||'Núcleo não identificado':'Sem núcleo';
 return <div className="contem largo"><div className="fin-cabeca"><div><h1>Financeiro</h1><p>Recebimentos compartilhados com o Financeiro Integral · {operar?'Acesso operacional':'Somente consulta'}</p></div>{operar&&<button className="btn btn-primario" onClick={()=>setImportar(true)}><Upload size={17}/>Importar relatório de pagamentos</button>}</div><div className="fin-acoes"><CampoCRM nome="Competência"><input className="inp" type="month" required value={mes} onChange={e=>{if(e.target.value)setMes(e.target.value);}}/></CampoCRM><button className="btn" onClick={()=>{setMunicipio('');setRemessa(null);setNucleo(null);setCliente(null);}}>Municípios</button>{municipio&&<button className="btn" onClick={()=>{setRemessa(null);setNucleo(null);setCliente(null);}}>{db.municipios.find(x=>x.id===municipio)?.nome}<ChevronRight size={14}/>Remessas</button>}{remessa!==null&&<button className="btn" onClick={()=>{setNucleo(null);setCliente(null);}}>Núcleos</button>}{nucleo!==null&&<button className="btn" onClick={()=>setCliente(null)}>Clientes</button>}</div><EstadoModulo modulo={m}/><div className="fin-resumo">{[["Parcelas",rows.reduce((s,r)=>s+Number(r.parcelas),0)],["Previsto",dinheiro(rows.reduce((s,r)=>s+Number(r.previsto),0))],["Recebido",dinheiro(rows.reduce((s,r)=>s+Number(r.recebido),0))],["Pagas",rows.reduce((s,r)=>s+Number(r.pagas),0)]].map(([n,v])=><div className="card" key={n}><span>{n}</span><strong>{v}</strong></div>)}</div>
 {importar&&<ImportarFinanceiro modo="pagamentos" fechar={()=>setImportar(false)} salvo={()=>{setImportar(false);m.atualizar();}}/>}
 {cliente?<FinanceiroCliente key={cliente.id} p={{financeiroRef:cliente.id}} usuario={usuario}/>:nucleo!==null?<ClientesFinanceiro municipio={municipio} remessa={remessa} nucleo={nucleo} abrir={setCliente}/>:<div className="rolagem"><table className="tab"><thead><tr>{['Local','Clientes','Parcelas','Pagas','Previsto','Recebido'].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{[...somas.values()].sort((a,b)=>nome(a.id).localeCompare(nome(b.id),'pt-BR')).map(r=><tr key={r.id}><td><button className="btn" onClick={()=>{if(!municipio)setMunicipio(r.id);else if(remessa===null)setRemessa(r.id);else setNucleo(r.id);}}>{nome(r.id)}<ChevronRight size={15}/></button></td><td>{r.clientes}</td><td>{r.parcelas}</td><td>{r.pagas}</td><td>{dinheiro(r.previsto)}</td><td>{dinheiro(r.recebido)}</td></tr>)}</tbody></table></div>}
 </div>;
}
function ClientesFinanceiro({municipio,remessa,nucleo,abrir}){
 const m=useModulo(async()=>{const cs=await lerTabela('fin_receb_clientes','id,nome,codigo,municipio_id,remessa_id',`&ativo=eq.true&municipio_id=eq.${municipio}&remessa_id=${remessa?'eq.'+remessa:'is.null'}`),extras=[];for(let i=0;i<cs.length;i+=50)extras.push(...await lerTabela('integracao_moradores','referencia_id,nucleo:dados->>nucleoId',`&colecao=eq.processos&referencia_id=in.(${cs.slice(i,i+50).map(c=>c.id).join(',')})`));const mapa=new Map(extras.map(e=>[e.referencia_id,e.nucleo||'']));return cs.filter(c=>(mapa.get(c.id)||'')===nucleo);},[municipio,remessa,nucleo],['clientes']);return <><EstadoModulo modulo={m}/><div className="fin-clientes">{m.dados?.map(c=><button className="card fin-cliente-link" key={c.id} onClick={()=>abrir(c)}><strong>{c.nome}</strong><span>{c.codigo}</span><ChevronRight size={18}/></button>)}</div></>;
}
