import {useEffect,useRef,useState} from 'react';
import {Clock,Check,Download} from 'lucide-react';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {ponto,idPonto,diaPonto,horaPonto,duracaoPonto,jornadaAtual,relatorioPonto} from './ponto-api.js';
import {acessoCRM} from './crm-regras.js';
import './folha-ponto.css';
import SolicitacoesPonto,{PedirCorrecaoPonto} from './SolicitacoesPonto.jsx';
import {usePontoLocal} from './use-ponto-local.js';
const diasSemana=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
export function JornadaPonto({alvo}){
 const id=idPonto(alvo),m=useModulo(()=>jornadaAtual(id),[id],['ponto']);
 const [editar,setEditar]=useState(false),[form,setForm]=useState(null),[erro,setErro]=useState('');
 if(!/^[0-9a-f-]{36}$/i.test(id))return <p className="ajuda">Vincule o usuário ao ERP para configurar o ponto.</p>;
 const atual=m.dados?.[0];
 const abrir=()=>{setForm({vinculo:atual?.vinculo||'Contrato',vigencia:diaPonto(),dias:atual?.dias||[1,2,3,4,5],entrada:atual?.entrada?.slice(0,5)||'08:00',saida:atual?.saida?.slice(0,5)||'17:00',intervalo:atual?.intervalo??60});setErro('');setEditar(true);};
 const campo=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <section className="ponto-jornada"><EstadoModulo modulo={m}/>{m.dados&&<><div className="flex flex-wrap gap-2 items-center"><strong>Vínculo: {atual?.vinculo||'Não configurado'}</strong><button className="btn btn-sm" onClick={abrir}>Configurar CLT / Contrato</button></div>{atual&&<p className="ajuda">Desde {atual.vigencia.split('-').reverse().join('/')} · {atual.dias.map(d=>diasSemana[d]).join(', ')} · {atual.entrada.slice(0,5)}–{atual.saida.slice(0,5)} · intervalo {atual.intervalo} min</p>}</>}
 {editar&&<form className="ponto-form" aria-label={`Jornada de ${alvo.nome}`} onSubmit={async e=>{e.preventDefault();setErro('');if(!form.dias.length||form.saida<=form.entrada){setErro('Selecione os dias e uma saída após a entrada, no mesmo dia.');return;}if(await m.executar(()=>ponto('jornada',{usuario_id:id,...form,intervalo:Number(form.intervalo)})))setEditar(false);}}>
 <CampoCRM nome="Vínculo"><select className="inp" aria-label="Vínculo" value={form.vinculo} onChange={e=>campo('vinculo',e.target.value)}><option>CLT</option><option>Contrato</option></select></CampoCRM>
 <CampoCRM nome="Válido a partir de"><input className="inp" required type="date" min={diaPonto()} value={form.vigencia} onChange={e=>campo('vigencia',e.target.value)}/></CampoCRM>
 <fieldset><legend>Dias da semana</legend><div className="ponto-dias">{diasSemana.map((d,i)=><label key={d}><input type="checkbox" checked={form.dias.includes(i)} onChange={e=>campo('dias',e.target.checked?[...form.dias,i].sort():form.dias.filter(x=>x!==i))}/>{d}</label>)}</div></fieldset>
 <div className="ponto-campos"><CampoCRM nome="Entrada prevista"><input className="inp" type="time" required value={form.entrada} onChange={e=>campo('entrada',e.target.value)}/></CampoCRM><CampoCRM nome="Saída prevista"><input className="inp" type="time" required value={form.saida} onChange={e=>campo('saida',e.target.value)}/></CampoCRM><CampoCRM nome="Intervalo total (minutos)"><input className="inp" type="number" min="0" max="1439" required value={form.intervalo} onChange={e=>campo('intervalo',e.target.value)}/></CampoCRM></div>
 <p className="ajuda">A jornada prevista desconta o intervalo. O tempo trabalhado usa apenas os pares de batidas. Mudanças preservam as jornadas anteriores; se já houve batida hoje, escolha uma vigência futura.</p>
 {erro&&<p role="alert">{erro}</p>}<div className="flex gap-2"><button className="btn btn-primario" disabled={m.ocupado}>Salvar vínculo e jornada</button><button className="btn" type="button" onClick={()=>setEditar(false)}>Cancelar</button></div></form>}
 </section>;
}
export function BaterPonto({usuario}){
 const m=usePontoLocal(usuario);
 if(m.dados.estado?.jornada?.vinculo!=='CLT'&&!m.dados.fila.length)return null;
 return <section className="card ponto-home"><div><h2><Clock size={22}/>Meu ponto</h2><p>Registre a entrada e cada saída e retorno, incluindo café e almoço. Horário de Brasília.</p></div>
 <button className="btn btn-primario" disabled={m.ocupado} onClick={m.bater}>Bater ponto — {m.proximo}</button>
 <p role="status">{m.dados.fila.length?`${m.dados.fila.length} marcação(ões) salva(s) neste aparelho, aguardando envio.`:'Marcações sincronizadas.'}{!m.online?' Sem internet: você pode continuar batendo ponto.':''}</p>
 {m.dados.fila.length>0&&<><button className="btn" disabled={!m.online} onClick={m.enviar}>Enviar marcações agora</button><ul>{m.dados.fila.map(b=><li key={b.pedido}>{new Date(b.ocorrido_em).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})} · {b.tipo==='entrada'?'Entrada':'Saída'} {horaPonto(b.ocorrido_em)} — pendente</li>)}</ul></>}
 {m.erro&&<p role="alert">{m.erro} {m.dados.fila.length?'As marcações pendentes continuam guardadas neste aparelho.':''}</p>}
 <div className="ponto-batidas">{m.batidas.map((b,i)=><span key={b}>{i%2?'Saída':'Entrada'} {horaPonto(b)}</span>)}</div>
 <p className="ajuda">Acesse sua conta neste aparelho antes de sair para campo. O envio ocorre com o Integração aberto e conectado, na mesma conta. Não limpe os dados do navegador enquanto houver marcações pendentes.</p></section>;
}
function AcaoPonto({acao,usuarioId,fechar,salvar}){
 const [motivo,setMotivo]=useState(''),[minutos,setMinutos]=useState(''),[horas,setHoras]=useState((acao.dia.batidas||[]).map(h=>horaPonto(h).slice(0,5)).join('\n')),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false);
 const titulo=acao.tipo==='decidir'?(acao.aprovada?'Aprovar horas extras':'Recusar horas extras'):acao.tipo==='revisar'?'Regularizar batidas':'Ajustar banco de horas';
 return <section className="card ponto-acao" role="region" aria-label={titulo}><h3>{titulo} · {acao.dia.dia.split('-').reverse().join('/')}</h3><form className="ponto-form" onSubmit={async e=>{e.preventDefault();setErro('');setOcupado(true);try{
 const dados={usuario_id:usuarioId,dia:acao.dia.dia,motivo,assinatura:acao.dia.assinatura,aprovada:acao.aprovada};
 if(acao.tipo==='revisar'){const lista=horas.split(/\s+/).filter(Boolean);if(lista.length%2||lista.some(h=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(h)))throw new Error('Informe pares de horários HH:MM, em ordem.');dados.batidas=lista.map(h=>`${acao.dia.dia}T${h}:00-03:00`);}
 if(acao.tipo==='ajustar'){dados.minutos=Number(minutos);if(!Number.isInteger(dados.minutos)||!dados.minutos||Math.abs(dados.minutos)>1440)throw new Error('Informe minutos inteiros entre −1440 e 1440, diferentes de zero.');}
 await ponto(acao.tipo,dados);salvar();}catch(e){setErro(e.message);}finally{setOcupado(false);}}}>
 {acao.tipo==='revisar'&&<><CampoCRM nome="Entradas e saídas, um horário por linha"><textarea className="inp" rows={6} value={horas} onChange={e=>setHoras(e.target.value)}/></CampoCRM><p className="ajuda">Exemplo: 08:00, 12:00, 13:00, 17:00, cada um em uma linha. As batidas originais permanecem no histórico. Uma revisão exige nova decisão sobre horas extras.</p></>}
 {acao.tipo==='ajustar'&&<CampoCRM nome="Minutos de crédito (+) ou débito (−)"><input className="inp" required type="number" value={minutos} onChange={e=>setMinutos(e.target.value)}/></CampoCRM>}
 <CampoCRM nome="Justificativa"><textarea className="inp" minLength={5} required value={motivo} onChange={e=>setMotivo(e.target.value)}/></CampoCRM>{erro&&<p role="alert" className="msg-erro">{erro}</p>}<div className="flex gap-2"><button className="btn btn-primario" disabled={ocupado||motivo.trim().length<5}>Confirmar</button><button type="button" className="btn" onClick={fechar} disabled={ocupado}>Cancelar</button></div></form></section>;
}
export default function FolhaPonto({usuario,db}){
 const admin=acessoCRM(usuario).admin,meuId=idPonto(usuario),usuarios=db.usuarios.filter(u=>u.erpRef),[selecionada,setPessoa]=useState(meuId),[versaoPedidos,setVersaoPedidos]=useState(0),[mes,setMes]=useState(()=>diaPonto().slice(0,7)),[acao,setAcao]=useState(null);
 const pessoa=admin?selecionada:meuId;
 const m=useModulo(()=>relatorioPonto(pessoa,mes),[pessoa,mes],['ponto']);
 const alvo=usuarios.find(u=>u.erpRef===pessoa)||(pessoa===meuId?usuario:null),dias=m.dados?.dias||[],somar=k=>dias.reduce((s,d)=>s+Number(d[k]||0),0);
 const csv=()=>{const linhas=[['Dia','Previsto (min)','Trabalhado (min)','Extra pendente (min)','Extra aprovado (min)','Extra recusado (min)','Ajuste (min)','Saldo (min)','Situação'],...dias.map(d=>[d.dia,d.previsto,d.trabalhado,d.pendente_extra,d.aprovado,d.rejeitado,d.ajuste,d.saldo,d.incompleto?'Batidas incompletas':d.fechado?'Fechado':'Em andamento'])];const url=URL.createObjectURL(new Blob(['\ufeff'+linhas.map(l=>l.join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`folha-ponto-${pessoa}-${mes}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="folha-ponto"><header><h2><Clock size={24}/>{admin?'Folha Ponto':'Minha Folha Ponto'}</h2><p>Jornadas, batidas, aprovação de horas extras e banco de horas · horário de Brasília.</p></header><div className="ponto-campos">{admin&&<CampoCRM nome="Funcionário"><select className="inp" aria-label="Funcionário" value={pessoa} onChange={e=>{setPessoa(e.target.value);setAcao(null);}}>{usuarios.map(u=><option key={u.erpRef} value={u.erpRef}>{u.nome}{!u.ativo?' (inativo)':''}</option>)}</select></CampoCRM>}<CampoCRM nome="Mês"><input className="inp" type="month" max={diaPonto().slice(0,7)} value={mes} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){setMes(e.target.value);setAcao(null);}}}/></CampoCRM><button className="btn" onClick={m.atualizar}>Atualizar relatório</button><button className="btn" disabled={!dias.length} onClick={csv}><Download size={15}/>Baixar CSV</button></div>
 {admin&&alvo&&<details className="card ponto-config"><summary>Vínculo e jornada de {alvo.nome}</summary><JornadaPonto key={pessoa} alvo={alvo}/></details>}
 <EstadoModulo modulo={m}/>{m.dados&&<><div className="ponto-resumo">{[['Trabalhado',somar('trabalhado')],['Extra pendente',somar('pendente_extra')],['Extra aprovado',somar('aprovado')],['Saldo anterior',m.dados.saldo_anterior],['Saldo do mês',somar('saldo')],['Banco acumulado',m.dados.saldo_anterior+somar('saldo')]].map(([nome,valor])=><div className="card" key={nome}><span>{nome}</span><strong className={valor<0?'ponto-negativo':''}>{duracaoPonto(valor,/Saldo|Banco/.test(nome))}</strong></div>)}</div>
 <p className="ajuda">Extras incluem o trabalho fora do horário e o que excede a jornada diária. Somente extras aprovadas entram no banco. Dias incompletos ou em andamento não geram déficit; feriados, férias e abonos devem ser registrados como ajustes justificados. Saldo inicial zero a partir da primeira vigência.</p>
 {acao?.tipo==='solicitar'&&<PedirCorrecaoPonto key={pessoa+acao.dia.dia} dia={acao.dia} fechar={()=>setAcao(null)} salvar={()=>{setAcao(null);setVersaoPedidos(v=>v+1);}}/>}
 {admin&&acao&&acao.tipo!=='solicitar'&&<AcaoPonto key={acao.tipo+acao.dia.dia+acao.aprovada} acao={acao} usuarioId={pessoa} fechar={()=>setAcao(null)} salvar={()=>{setAcao(null);m.atualizar();}}/>}
 <div className="rolagem"><table className="tab ponto-tabela"><caption>Relatório de {alvo?.nome} · {mes}</caption><thead><tr>{['Dia','Entradas / saídas','Previsto','Trabalhado','Extra pendente','Aprovada / recusada','Saldo','Ações'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{dias.map(d=><tr key={d.dia}><td>{d.dia.split('-').reverse().join('/')}<small>{d.incompleto?'Batidas incompletas':!d.fechado?'Em andamento':d.vinculo||'Sem jornada'}</small></td><td><div className="ponto-batidas">{d.batidas.map((b,i)=><span key={b}>{i%2?'S':'E'} {horaPonto(b)}</span>)}</div>{d.originais?.some(b=>b.origem&&b.origem!=='servidor')&&<details><summary>Marcações do aparelho</summary>{d.originais.filter(b=>b.origem!=='servidor').map(b=><p key={b.hora}>{b.tipo} · {horaPonto(b.hora)} · {b.origem==='offline'?'Sem internet':'Registrada no aparelho'} · recebida em {new Date(b.recebido_em).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>)}</details>}{d.revisao&&<details><summary>Batidas revisadas</summary><p>{d.revisao.motivo}</p><p>Originais: {d.originais.map(b=>`${b.tipo} ${horaPonto(b.hora)}`).join(' · ')||'Sem batidas'}</p></details>}</td><td>{duracaoPonto(d.previsto)}</td><td>{duracaoPonto(d.trabalhado)}</td><td>{duracaoPonto(d.pendente_extra)}</td><td>{duracaoPonto(d.aprovado)} / {duracaoPonto(d.rejeitado)}</td><td className={d.saldo<0?'ponto-negativo':''}>{duracaoPonto(d.saldo,true)}{d.ajuste!==0&&<small>Ajuste: {duracaoPonto(d.ajuste,true)}</small>}</td><td><div className="ponto-acoes">{admin&&d.extra>0&&d.fechado&&!d.incompleto&&<><button className="btn btn-sm" onClick={()=>setAcao({tipo:'decidir',aprovada:true,dia:d})}>Aprovar extra</button><button className="btn btn-sm" onClick={()=>setAcao({tipo:'decidir',aprovada:false,dia:d})}>Recusar extra</button></>}{admin&&d.dia<diaPonto()&&<button className="btn btn-sm" onClick={()=>setAcao({tipo:'revisar',dia:d})}>Regularizar batidas</button>}{admin&&<button className="btn btn-sm" onClick={()=>setAcao({tipo:'ajustar',dia:d})}>Ajustar banco</button>}{pessoa===meuId&&d.dia<diaPonto()&&<button className="btn btn-sm" onClick={()=>setAcao({tipo:'solicitar',dia:d})}>Solicitar alteração</button>}</div></td></tr>)}</tbody></table></div>{!dias.length&&<p>Nenhuma jornada ou movimentação neste período. {admin?'Configure o vínculo e a vigência para iniciar.':'Peça à Diretoria para conferir seu vínculo e sua jornada.'}</p>}
 <details className="card ponto-config"><summary>Histórico de decisões, ajustes e regularizações</summary>{[...m.dados.decisoes.map(x=>({...x,tipo:x.aprovada?'Extra aprovada':'Extra recusada'})),...m.dados.ajustes.map(x=>({...x,tipo:'Ajuste de banco'})),...m.dados.revisoes.map(x=>({...x,tipo:'Regularização'}))].sort((a,b)=>b.criado_em.localeCompare(a.criado_em)).map(x=><p key={x.id}>{x.dia} · {x.tipo}{x.minutos!=null?` · ${duracaoPonto(x.minutos,true)}`:''} · {x.motivo} · {usuarios.find(u=>u.erpRef===x.autor)?.nome||'Administrador'} · {new Date(x.criado_em).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>)}</details>
 </>}
 <p className="ajuda">Correções podem ser solicitadas para dias anteriores a hoje, após o envio das batidas offline. A aprovação preserva as marcações originais e recalcula o relatório; eventuais horas extras continuam sujeitas à aprovação.</p>
 <SolicitacoesPonto key={pessoa+mes} usuario={usuario} usuarioId={pessoa} mes={mes} usuarios={usuarios} versao={versaoPedidos} aoDecidir={m.atualizar}/>
 </section>;
}
