import {useEffect,useRef,useState} from 'react';
import {listarCRM,criarCRM,editarCRM,rpcCRM} from './crm-api.js';
import {acessoCRM,normalizarCRM} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {enviarArquivoSemanal,abrirArquivoSemanal} from './dados-compartilhados.js';
import './semanal.css';
import {historicoMunicipal} from './semanal-regras.js';
const MESES=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
function JanelaSemanal({titulo,onFechar,children}) {
 const ref=useRef(null);
 useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close();},[]);
 return <dialog ref={ref} className="semanal-dialogo" aria-label={titulo} onCancel={e=>{e.preventDefault();onFechar();}}><button className="btn semanal-fechar" aria-label="Fechar janela" onClick={onFechar}>×</button>{children}</dialog>;
}
const refNucleo=n=>n?.externo?.kanbanId||n?.id;
export default function GestaoSemanal({db,usuario,municipioId}) {
  const acesso=acessoCRM(usuario),now=new Date();
  const [mes,setMes]=useState(now.getMonth()+1),[ano,setAno]=useState(now.getFullYear()),[busca,setBusca]=useState(''),[selecionado,setSelecionado]=useState(null),[form,setForm]=useState(null),[texto,setTexto]=useState(''),[arquivo,setArquivo]=useState(null),[motivo,setMotivo]=useState('');
  const [semanaSelecionada,setSemanaSelecionada]=useState(null),[exclusao,setExclusao]=useState(null);
  const m=useModulo(async()=>{
    if(!acesso.pos)return {};
    const [municipios,semanas,registros,arquivos,pedidos]=await Promise.all(['municipios','semanas','registros','arquivos','exclusoes'].map(t=>listarCRM(`integracao_semanal_${t}`)));
    return {municipios,semanas,registros,arquivos,pedidos};
  },[usuario?.id],['semanal','clientes']);
  if(!acesso.pos)return <div className="contem"><h1>Gestão Semanal</h1><p>Acesso restrito ao Pós-Protocolo e à administração.</p></div>;
  const nome=id=>{const c=db.municipios.find(x=>x.id===id);return c?`${c.nome}/${c.uf}`:'Município';};
  const nomeCard=c=>db.municipios.some(x=>x.id===c?.municipio_id)?nome(c.municipio_id):`${c?.origem_dados?.nome||'Município'}/${c?.origem_dados?.estado||''}`;
  const nucleoNome=id=>{const n=db.nucleos.find(n=>refNucleo(n)===id);return n?`${n.codigo} ${n.nome||''}`:'';};
  const lista=(m.dados?.municipios||[]).filter(x=>x.ativo&&(!municipioId||x.municipio_id===municipioId)&&normalizarCRM(`${nomeCard(x)} ${nucleoNome(x.nucleo_id)}`).includes(normalizarCRM(busca)));
  const semanaDe=c=>m.dados?.semanas.find(s=>s.municipio_id===c.id&&s.ano===ano&&s.mes===mes&&s.semana===c.semana_padrao);
  const obterSemana=async c=>{const existente=c.id===selecionado&&semanaSelecionada?m.dados?.semanas.find(s=>s.id===semanaSelecionada):semanaDe(c);if(existente)return existente;try{return (await criarCRM('integracao_semanal_semanas',{municipio_id:c.id,ano,mes,semana:c.semana_padrao}))[0];}catch(e){const rows=await listarCRM('integracao_semanal_semanas',`&municipio_id=eq.${c.id}&ano=eq.${ano}&mes=eq.${mes}&semana=eq.${c.semana_padrao}`);if(rows[0])return rows[0];throw e;}};
  const atual=selecionado&&m.dados?.municipios.find(c=>c.id===selecionado),semana=atual&&(semanaSelecionada?m.dados?.semanas.find(s=>s.id===semanaSelecionada):semanaDe(atual));
  const historico=historicoMunicipal(m.dados,atual?.municipio_id||municipioId,atual?.id);
  const abrirDetalhes=(c,s=null)=>{setTexto('');setArquivo(null);setSemanaSelecionada(s?.id||null);setSelecionado(c.id);};
  const pedirExclusao=c=>{setSelecionado(null);setMotivo('');setExclusao(c);};
  const excluir=async()=>{
    const pedidos=await listarCRM('integracao_semanal_exclusoes',`&municipio_id=eq.${exclusao.id}&status=eq.pendente`);
    const pedido=pedidos[0]||(await criarCRM('integracao_semanal_exclusoes',{municipio_id:exclusao.id,motivo:motivo.trim()}))[0];
    if(acesso.admin)await rpcCRM('integracao_semanal_decidir',{pedido:pedido.id,aprovar:true});
  };
  const registro=r=><article className="crm-mensagem" key={r.id}><p className="semanal-periodo">{MESES[r.semana.mes-1]} / {r.semana.ano} · Semana {r.semana.semana}{!r.semana.card.ativo?' · Retirado do quadro':''}</p><p className="semanal-relato">{r.comentario}</p><span className="ajuda">{new Date(r.created_at).toLocaleString('pt-BR')} · {db.usuarios.find(u=>u.erpRef===r.created_by)?.nome||r.origem_dados?.autor_nome||'Equipe'}</span>{municipioId&&!atual&&<button className="btn btn-sm" onClick={()=>abrirDetalhes(r.semana.card,r.semana)}>Detalhes da semana</button>}</article>;
  const anexo=a=><article className="crm-mensagem" key={a.id}><button className="btn" onClick={()=>m.executar(async()=>{const url=await abrirArquivoSemanal(a.caminho);window.open(url,'_blank','noopener,noreferrer');})}>{a.nome}</button><p className="ajuda">{MESES[a.semana.mes-1]} / {a.semana.ano} · Semana {a.semana.semana}</p></article>;
  const adicionar=s=>setForm({municipio_id:municipioId||'',nucleo_id:'',andamento_id:'',semana_padrao:s,telefone:'',observacoes:''});
  const editar=c=>{setSelecionado(null);setForm(Object.fromEntries(['id','municipio_id','nucleo_id','andamento_id','semana_padrao','telefone','observacoes'].map(k=>[k,c[k]??''])));};
  const historicoPagina=historicoMunicipal(m.dados,municipioId);
  const concluidos=lista.filter(c=>semanaDe(c)?.concluido).length;
  return <div className="contem largo semanal-pagina"><div className="cabeca"><div><h1>{municipioId?`Andamentos · ${nome(municipioId)}`:'Gestão semanal de municípios'}</h1><p>{municipioId?'Registros e arquivos compartilhados com a Gestão Semanal, de todos os meses.':'O mês é dividido em 4 semanas. O município se repete na mesma semana nos meses seguintes.'}</p></div><button className="btn btn-primario" onClick={()=>adicionar(1)}>Adicionar município</button></div>
    {municipioId&&m.dados&&<section className="semanal-historico-municipal"><h2>Histórico do município</h2><div className="semanal-historico-colunas"><div>{historicoPagina.registros.map(registro)}{!historicoPagina.registros.length&&<p>Nenhum andamento registrado.</p>}</div><div><h3>Arquivos do município</h3>{historicoPagina.arquivos.map(anexo)}{!historicoPagina.arquivos.length&&<p className="ajuda">Nenhum arquivo registrado.</p>}</div></div><h2>Gestão semanal deste município</h2></section>}
    {exclusao&&<JanelaSemanal titulo="Excluir município do quadro" onFechar={()=>setExclusao(null)}><h2>{acesso.admin?'Excluir do quadro':'Solicitar exclusão'} · {nomeCard(exclusao)}</h2><p>O município sai da recorrência semanal. O cadastro e todo o histórico de registros e arquivos são preservados em Andamentos.</p><EstadoModulo modulo={m}/><form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(excluir))setExclusao(null);}}><CampoCRM nome="Motivo da exclusão"><textarea className="inp" required value={motivo} onChange={e=>setMotivo(e.target.value)}/></CampoCRM><div className="crm-acoes"><button className="btn btn-perigo" disabled={m.ocupado||!motivo.trim()}>{acesso.admin?'Confirmar exclusão do quadro':'Enviar solicitação à administração'}</button><button className="btn" type="button" onClick={()=>setExclusao(null)}>Cancelar</button></div></form></JanelaSemanal>}
    <div className="semanal-filtros"><CampoCRM nome="Ano"><select className="inp" value={ano} onChange={e=>setAno(Number(e.target.value))}>{Array.from({length:7},(_,i)=>now.getFullYear()-3+i).map(a=><option key={a} value={a}>{a}</option>)}</select></CampoCRM><CampoCRM nome="Mês"><select className="inp" value={mes} onChange={e=>setMes(Number(e.target.value))}>{MESES.map((nome,i)=><option key={nome} value={i+1}>{nome}</option>)}</select></CampoCRM><CampoCRM nome="Buscar"><input className="inp" type="search" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Município, projeto ou núcleo"/></CampoCRM><button className="btn" onClick={m.atualizar} disabled={m.ocupado}>Atualizar</button></div>
    {m.dados&&<div className="semanal-totais" aria-live="polite"><div><strong>{lista.length}</strong><span>município(s) recorrente(s)</span></div><div><strong>{concluidos}</strong><span>concluído(s) neste mês</span></div><div><strong>{lista.length-concluidos}</strong><span>pendente(s) neste mês</span></div></div>}
    <EstadoModulo modulo={m}/>
    {form&&<JanelaSemanal titulo={form.id?'Editar município':'Adicionar município'} onFechar={()=>setForm(null)}><EstadoModulo modulo={m}/><form className="crm-form" onSubmit={async e=>{e.preventDefault();const {id,...data}=form;data.nucleo_id||=null;data.andamento_id||=null;if(await m.executar(()=>id?editarCRM('integracao_semanal_municipios',id,data):criarCRM('integracao_semanal_municipios',data)))setForm(null);}}>
      <h2>{form.id?'Editar':'Adicionar'} município</h2><CampoCRM nome="Município"><select className="inp" required value={form.municipio_id} onChange={e=>setForm({...form,municipio_id:e.target.value,nucleo_id:'',andamento_id:''})}><option value="">Selecione</option>{db.municipios.map(x=><option key={x.id} value={x.id}>{x.nome}/{x.uf}</option>)}</select></CampoCRM>
      <CampoCRM nome="Núcleo"><select className="inp" value={form.nucleo_id} onChange={e=>setForm({...form,nucleo_id:e.target.value,andamento_id:''})}><option value="">Sem vínculo</option>{db.nucleos.filter(n=>n.municipioId===form.municipio_id).map(n=><option key={n.id} value={refNucleo(n)}>{n.codigo} {n.nome}</option>)}</select></CampoCRM>
      <CampoCRM nome="Andamento vinculado"><select className="inp" value={form.andamento_id||''} onChange={e=>setForm({...form,andamento_id:e.target.value})}><option value="">Sem andamento específico</option>{(db.nucleos.find(n=>refNucleo(n)===form.nucleo_id)?.andamentos||[]).map(a=><option key={a.id} value={a.id}>{a.status} · {a.descricaoCliente}</option>)}</select></CampoCRM>
      <CampoCRM nome="Semana recorrente"><select className="inp" value={form.semana_padrao} onChange={e=>setForm({...form,semana_padrao:Number(e.target.value)})}>{[1,2,3,4].map(s=><option key={s} value={s}>Semana {s}</option>)}</select></CampoCRM>
      <CampoCRM nome="Telefone"><input className="inp" value={form.telefone||''} onChange={e=>setForm({...form,telefone:e.target.value})}/></CampoCRM><CampoCRM nome="Observações"><textarea className="inp" value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})}/></CampoCRM><div className="crm-acoes"><button className="btn btn-primario" disabled={m.ocupado}>Salvar</button><button className="btn" type="button" onClick={()=>setForm(null)}>Cancelar</button></div></form></JanelaSemanal>}
    {m.dados&&<div className="semanal-quadro">{[1,2,3,4].map(s=>{const cards=lista.filter(c=>c.semana_padrao===s).sort((a,b)=>nomeCard(a).localeCompare(nomeCard(b),'pt-BR'));return <section key={s} className="semanal-coluna"><header><div><p>{MESES[mes-1]} / {ano}</p><h2>Semana {s}</h2><span>{cards.length} município(s)</span></div><button className="btn btn-primario btn-sm" onClick={()=>adicionar(s)}>+ Município</button></header><div className="semanal-cards">{cards.map(c=>{const w=semanaDe(c),feito=!!w?.concluido;return <article className={`semanal-card ${feito?'concluido':'pendente'}`} key={c.id}><div className="semanal-card-topo"><h3>{nomeCard(c)}</h3><button className="btn btn-sm" aria-label={`Editar ${nomeCard(c)}`} onClick={()=>editar(c)}>Editar</button></div>{!c.municipio_id&&<p className="semanal-revisao">Vínculo municipal em revisão</p>}{c.nucleo_id&&<p>{nucleoNome(c.nucleo_id)}</p>}<p>{feito?'Concluído':'Pendente'}</p><button className="semanal-detalhes" aria-label={`Detalhes de ${nomeCard(c)}`} onClick={()=>abrirDetalhes(c)}><span>{m.dados.registros.filter(r=>r.semana_id===w?.id).length} registro(s), {m.dados.arquivos.filter(a=>a.semana_id===w?.id).length} arquivo(s)</span><strong>Detalhes</strong></button><button className="btn btn-sm semanal-excluir" aria-label={`Excluir ${nomeCard(c)} do quadro`} onClick={()=>pedirExclusao(c)}>{acesso.admin?'Excluir do quadro':'Solicitar exclusão'}</button></article>;})}{!cards.length&&<p className="ajuda">Nenhum município nesta semana.</p>}</div></section>;})}</div>}
    {atual&&<JanelaSemanal titulo={`Detalhes de ${nomeCard(atual)}`} onFechar={()=>setSelecionado(null)}><EstadoModulo modulo={m}/><section className="semanal-conteudo">
      <p className="semanal-periodo">{MESES[(semana?.mes||mes)-1]} / {semana?.ano||ano} · Semana {semana?.semana||atual.semana_padrao}</p><h2>{nomeCard(atual)}</h2>
      <p>{atual.nucleo_id?nucleoNome(atual.nucleo_id):'Sem Projeto/Núcleo vinculado'}</p>
      {!atual.municipio_id&&<p className="semanal-revisao">Vínculo municipal em revisão. Confirme o município em Editar card.</p>}
      <p>{atual.telefone} {atual.observacoes}</p><p className="semanal-status">{!atual.ativo?'Retirado do quadro · histórico preservado':semana?.concluido?'Semana concluída':'Semana pendente'}</p>
      {atual.ativo&&<><div className="crm-acoes"><button className="btn" onClick={()=>editar(atual)}>Editar card</button><button className="btn" disabled={m.ocupado} onClick={()=>m.executar(async()=>{const s=await obterSemana(atual);await editarCRM('integracao_semanal_semanas',s.id,{concluido:!s.concluido,concluido_em:s.concluido?null:new Date().toISOString(),concluido_por:s.concluido?null:usuario.erpRef});})}>{semana?.concluido?'Reabrir semana':'Concluir semana'}</button><button className="btn btn-perigo" onClick={()=>pedirExclusao(atual)}>{acesso.admin?'Excluir do quadro':'Solicitar exclusão'}</button></div>
      <form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(async()=>{const s=await obterSemana(atual);await criarCRM('integracao_semanal_registros',{semana_id:s.id,comentario:texto.trim()});}))setTexto('');}}><CampoCRM nome="Novo registro / andamento"><textarea className="inp" rows={4} required placeholder="Registre contato, retorno, pendência ou providência desta semana." value={texto} onChange={e=>setTexto(e.target.value)}/></CampoCRM><button className="btn btn-primario" disabled={m.ocupado||!texto.trim()}>Adicionar registro</button></form>
      <form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(async()=>{const s=await obterSemana(atual);const caminho=await enviarArquivoSemanal(s.id,arquivo);await criarCRM('integracao_semanal_arquivos',{semana_id:s.id,nome:arquivo.name,caminho});}))setArquivo(null);}}><CampoCRM nome="Adicionar arquivo"><input type="file" onChange={e=>setArquivo(e.target.files[0]||null)}/></CampoCRM><button className="btn" disabled={m.ocupado||!arquivo}>Enviar arquivo</button></form></>}
      <div className="semanal-detalhe-colunas"><section><h3>Histórico desta semana</h3>{historico.registros.filter(r=>r.semana_id===semana?.id).map(registro)}{!historico.registros.some(r=>r.semana_id===semana?.id)&&<p className="ajuda">Nenhum registro nesta semana.</p>}</section>
      <section><h3>Histórico total do Núcleo/Projeto</h3>{!atual.nucleo_id&&<p className="ajuda">Nenhum Projeto/Núcleo vinculado.</p>}{(db.nucleos.find(n=>refNucleo(n)===atual.nucleo_id)?.andamentos||[]).map(a=><article className="crm-mensagem" key={a.id}><strong>{a.status}</strong><p className="semanal-relato">{a.descricaoCliente}</p></article>)}</section>
      <section><h3>Arquivos desta semana</h3>{historico.arquivos.filter(a=>a.semana_id===semana?.id).map(anexo)}{!historico.arquivos.some(a=>a.semana_id===semana?.id)&&<p className="ajuda">Nenhum arquivo nesta semana.</p>}</section></div>
      <details><summary>Histórico do município · todos os meses</summary>{historico.registros.map(registro)}{!historico.registros.length&&<p className="ajuda">Nenhum andamento registrado.</p>}<h3>Arquivos de todos os meses</h3>{historico.arquivos.map(anexo)}</details>
    </section></JanelaSemanal>}
    {acesso.admin&&m.dados?.pedidos.filter(p=>p.status==='pendente').map(p=><article className="crm-card" key={p.id}><h3>Solicitação de exclusão · {nome(m.dados.municipios.find(c=>c.id===p.municipio_id)?.municipio_id)}</h3><p>{p.motivo}</p><div className="crm-acoes">{[true,false].map(aprovar=><button className="btn" key={String(aprovar)} disabled={m.ocupado} onClick={()=>m.executar(()=>rpcCRM('integracao_semanal_decidir',{pedido:p.id,aprovar}))}>{aprovar?'Aprovar exclusão':'Recusar'}</button>)}</div></article>)}
  </div>;
}
