import {useState} from 'react';
import {listarCRM,criarCRM,editarCRM,rpcCRM} from './crm-api.js';
import {acessoCRM} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {enviarArquivoSemanal,abrirArquivoSemanal} from './dados-compartilhados.js';
const refNucleo=n=>n?.externo?.kanbanId||n?.id;
export default function GestaoSemanal({db,usuario,municipioId}) {
  const acesso=acessoCRM(usuario),now=new Date();
  const [mes,setMes]=useState(now.getMonth()+1),[ano,setAno]=useState(now.getFullYear()),[busca,setBusca]=useState(''),[selecionado,setSelecionado]=useState(null),[form,setForm]=useState(null),[texto,setTexto]=useState(''),[arquivo,setArquivo]=useState(null),[motivo,setMotivo]=useState('');
  const m=useModulo(async()=>{
    if(!acesso.pos)return {};
    const [municipios,semanas,registros,arquivos,pedidos]=await Promise.all(['municipios','semanas','registros','arquivos','exclusoes'].map(t=>listarCRM(`integracao_semanal_${t}`)));
    return {municipios,semanas,registros,arquivos,pedidos};
  },[usuario?.id]);
  if(!acesso.pos)return <div className="contem"><h1>Gestão Semanal</h1><p>Acesso restrito ao Pós-Protocolo e à administração.</p></div>;
  const nome=id=>db.municipios.find(x=>x.id===id)?.nome||'Município';
  const lista=(m.dados?.municipios||[]).filter(x=>x.ativo&&(!municipioId||x.municipio_id===municipioId)&&nome(x.municipio_id).toLowerCase().includes(busca.toLowerCase()));
  const semanaDe=c=>m.dados?.semanas.find(s=>s.municipio_id===c.id&&s.ano===ano&&s.mes===mes&&s.semana===c.semana_padrao);
  const obterSemana=async c=>{const existente=semanaDe(c);if(existente)return existente;try{return (await criarCRM('integracao_semanal_semanas',{municipio_id:c.id,ano,mes,semana:c.semana_padrao}))[0];}catch(e){const rows=await listarCRM('integracao_semanal_semanas',`&municipio_id=eq.${c.id}&ano=eq.${ano}&mes=eq.${mes}&semana=eq.${c.semana_padrao}`);if(rows[0])return rows[0];throw e;}};
  const atual=selecionado&&m.dados?.municipios.find(c=>c.id===selecionado),semana=atual&&semanaDe(atual);
  const historico=atual?(m.dados?.registros||[]).filter(r=>m.dados.semanas.some(s=>s.id===r.semana_id&&s.municipio_id===atual.id)).sort((a,b)=>b.created_at.localeCompare(a.created_at)):[];
  return <div className="contem largo"><div className="cabeca"><div><h1>{municipioId?'Atendimentos à prefeitura':'Gestão Semanal'}</h1><p>Municípios, retornos e providências por semana recorrente.</p></div><button className="btn btn-primario" onClick={()=>setForm({municipio_id:municipioId||'',nucleo_id:'',andamento_id:'',semana_padrao:1,telefone:'',observacoes:''})}>Adicionar município</button></div>
    <div className="crm-acoes"><input className="inp" aria-label="Buscar município" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar município"/><label>Mês<select className="inp" value={mes} onChange={e=>setMes(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2000,i,1).toLocaleDateString('pt-BR',{month:'long'})}</option>)}</select></label><label>Ano<input className="inp" type="number" min="2000" max="2200" value={ano} onChange={e=>setAno(Number(e.target.value))}/></label></div>
    <EstadoModulo modulo={m}/>
    {form&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();const {id,...data}=form;data.nucleo_id||=null;data.andamento_id||=null;if(await m.executar(()=>id?editarCRM('integracao_semanal_municipios',id,data):criarCRM('integracao_semanal_municipios',data)))setForm(null);}}>
      <h2>{form.id?'Editar':'Adicionar'} município</h2><CampoCRM nome="Município"><select className="inp" required value={form.municipio_id} onChange={e=>setForm({...form,municipio_id:e.target.value,nucleo_id:'',andamento_id:''})}><option value="">Selecione</option>{db.municipios.map(x=><option key={x.id} value={x.id}>{x.nome}/{x.uf}</option>)}</select></CampoCRM>
      <CampoCRM nome="Núcleo"><select className="inp" value={form.nucleo_id} onChange={e=>setForm({...form,nucleo_id:e.target.value,andamento_id:''})}><option value="">Sem vínculo</option>{db.nucleos.filter(n=>n.municipioId===form.municipio_id).map(n=><option key={n.id} value={refNucleo(n)}>{n.codigo} {n.nome}</option>)}</select></CampoCRM>
      <CampoCRM nome="Andamento vinculado"><select className="inp" value={form.andamento_id||''} onChange={e=>setForm({...form,andamento_id:e.target.value})}><option value="">Sem andamento específico</option>{(db.nucleos.find(n=>refNucleo(n)===form.nucleo_id)?.andamentos||[]).map(a=><option key={a.id} value={a.id}>{a.status} · {a.descricaoCliente}</option>)}</select></CampoCRM>
      <CampoCRM nome="Semana recorrente"><select className="inp" value={form.semana_padrao} onChange={e=>setForm({...form,semana_padrao:Number(e.target.value)})}>{[1,2,3,4].map(s=><option key={s} value={s}>Semana {s}</option>)}</select></CampoCRM>
      <CampoCRM nome="Telefone"><input className="inp" value={form.telefone||''} onChange={e=>setForm({...form,telefone:e.target.value})}/></CampoCRM><CampoCRM nome="Observações"><textarea className="inp" value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})}/></CampoCRM><div className="crm-acoes"><button className="btn btn-primario" disabled={m.ocupado}>Salvar</button><button className="btn" type="button" onClick={()=>setForm(null)}>Cancelar</button></div></form>}
    {m.dados&&<div className="crm-quadro">{[1,2,3,4].map(s=><section key={s} className="crm-coluna"><h2>Semana {s}</h2>{lista.filter(c=>c.semana_padrao===s).map(c=><article className="crm-card" key={c.id}><h3>{nome(c.municipio_id)}</h3><p>{db.nucleos.find(n=>refNucleo(n)===c.nucleo_id)?.codigo||'Sem núcleo'}</p><p>{semanaDe(c)?.concluido?'Concluído':'Pendente'}</p><button className="btn" onClick={()=>setSelecionado(c.id)}>Ver atendimentos</button></article>)}</section>)}</div>}
    {atual&&<section className="crm-card"><h2>{nome(atual.municipio_id)} · Semana {atual.semana_padrao}</h2><p>{atual.telefone} {atual.observacoes}</p><div className="crm-acoes"><button className="btn" onClick={()=>setForm(Object.fromEntries(['id','municipio_id','nucleo_id','andamento_id','semana_padrao','telefone','observacoes'].map(k=>[k,atual[k]])))}>Editar card</button><button className="btn" disabled={m.ocupado} onClick={()=>m.executar(async()=>{const s=await obterSemana(atual);await editarCRM('integracao_semanal_semanas',s.id,{concluido:!s.concluido,concluido_em:s.concluido?null:new Date().toISOString(),concluido_por:s.concluido?null:usuario.erpRef});})}>{semana?.concluido?'Reabrir':'Concluir semana'}</button><button className="btn" onClick={()=>setSelecionado(null)}>Fechar</button></div>
    <form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(async()=>{const s=await obterSemana(atual);await criarCRM('integracao_semanal_registros',{semana_id:s.id,comentario:texto});}))setTexto('');}}><CampoCRM nome="Contato, retorno ou providência"><textarea className="inp" required value={texto} onChange={e=>setTexto(e.target.value)}/></CampoCRM><button className="btn" disabled={m.ocupado||!texto.trim()}>Adicionar registro</button></form>
    <form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(async()=>{const s=await obterSemana(atual);const caminho=await enviarArquivoSemanal(s.id,arquivo);await criarCRM('integracao_semanal_arquivos',{semana_id:s.id,nome:arquivo.name,caminho});}))setArquivo(null);}}><CampoCRM nome="Anexo da semana"><input type="file" onChange={e=>setArquivo(e.target.files[0]||null)}/></CampoCRM><button className="btn" disabled={m.ocupado||!arquivo}>Enviar arquivo</button></form>
    {(m.dados.arquivos||[]).filter(a=>a.semana_id===semana?.id).map(a=><p key={a.id}><button className="btn" onClick={()=>m.executar(async()=>{const url=await abrirArquivoSemanal(a.caminho);window.open(url,'_blank','noopener,noreferrer');})}>{a.nome}</button></p>)}
    <h3>Histórico deste município/núcleo</h3>{historico.map(r=><article className="crm-mensagem" key={r.id}><span className="ajuda">{new Date(r.created_at).toLocaleString('pt-BR')}</span><p>{r.comentario}</p></article>)}
    <form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(()=>criarCRM('integracao_semanal_exclusoes',{municipio_id:atual.id,motivo})))setMotivo('');}}><CampoCRM nome="Motivo da solicitação de exclusão"><input className="inp" required value={motivo} onChange={e=>setMotivo(e.target.value)}/></CampoCRM><button className="btn" disabled={m.ocupado||!motivo.trim()||m.dados.pedidos.some(p=>p.municipio_id===atual.id&&p.status==='pendente')}>Solicitar exclusão à administração</button></form></section>}
    {acesso.admin&&m.dados?.pedidos.filter(p=>p.status==='pendente').map(p=><article className="crm-card" key={p.id}><h3>Solicitação de exclusão · {nome(m.dados.municipios.find(c=>c.id===p.municipio_id)?.municipio_id)}</h3><p>{p.motivo}</p><div className="crm-acoes">{[true,false].map(aprovar=><button className="btn" key={String(aprovar)} disabled={m.ocupado} onClick={()=>m.executar(()=>rpcCRM('integracao_semanal_decidir',{pedido:p.id,aprovar}))}>{aprovar?'Aprovar exclusão':'Recusar'}</button>)}</div></article>)}
  </div>;
}
