import {useState} from 'react';
import {MessageCircle,Plus,MapPin,ExternalLink,Pencil,Trash2,Clock,Send,Archive,RotateCcw} from 'lucide-react';
import {listarCRM,criarCRM,editarCRM} from './crm-api.js';
import {normalizarCRM} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {JanelaMarketing,MunicipioMarketing,RemoverMarketing,nomeMunicipio} from './marketing-ui.jsx';
export default function GruposMarketing({db,usuario}) {
 const [busca,setBusca]=useState(''),[form,setForm]=useState(null),[aberto,setAberto]=useState(null),[remover,setRemover]=useState(null),[arquivados,setArquivados]=useState(false),[texto,setTexto]=useState(''),[enviar,setEnviar]=useState(false);
 const m=useModulo(async()=>{const [grupos,atualizacoes,projetos]=await Promise.all(['grupos','atualizacoes','projetos'].map(t=>listarCRM(`integracao_marketing_${t}`)));return {grupos,atualizacoes,projetos};},[usuario.id]);
 const grupos=(m.dados?.grupos||[]).filter(g=>Boolean(g.ativo)!==arquivados&&normalizarCRM(`${g.nome} ${nomeMunicipio(db,g.municipio_id)}`).includes(normalizarCRM(busca)));
 const municipios=[...new Set([...grupos.map(g=>g.municipio_id),...(!arquivados&&!busca?(m.dados?.projetos||[]).filter(p=>p.ativo).map(p=>p.municipio_id||db.nucleos.find(n=>(n.externo?.kanbanId||n.id)===p.nucleo_id)?.municipioId):[])].filter(Boolean))].sort((a,b)=>nomeMunicipio(db,a).localeCompare(nomeMunicipio(db,b),'pt-BR'));
 const grupo=m.dados?.grupos.find(g=>g.id===aberto);
 const historico=(m.dados?.atualizacoes||[]).filter(a=>a.grupo_id===aberto).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const novo=municipio_id=>setForm({nome:'',municipio_id:municipio_id||'',link:'',descricao:'',status:'Em preparação'});
 const editar=g=>{setAberto(null);setForm({id:g.id,nome:g.nome,municipio_id:g.municipio_id,link:g.link||'',descricao:g.descricao||'',status:g.status});};
 return <section className="mkt-area"><div className="mkt-section-head"><div><h2>Grupos de WhatsApp</h2><p>Uma conversa próxima com cada município.</p></div><button className="btn btn-primario" onClick={()=>novo('')}><Plus size={17}/> Adicionar grupo</button></div>
  <div className="mkt-toolbar"><input className="inp" type="search" aria-label="Buscar grupo ou município" placeholder="Buscar grupo ou município…" value={busca} onChange={e=>setBusca(e.target.value)}/><button className={`btn ${arquivados?'btn-primario':''}`} onClick={()=>setArquivados(!arquivados)}><Archive size={16}/>{arquivados?'Ver grupos ativos':'Grupos removidos'}</button><button className="btn" onClick={m.atualizar}>Atualizar</button></div>
  <div className="mkt-nota"><Send size={18}/><span>Marque os progressos que poderão ser comunicados ao grupo. O envio automático por IA será conectado futuramente.</span></div><EstadoModulo modulo={m}/>
  <div className="mkt-kanban mkt-grupos-quadro">{municipios.map(id=><section className="mkt-coluna" key={id}><header><div><span className="mkt-eyebrow"><MapPin size={13}/> Município</span><h3>{nomeMunicipio(db,id)}</h3></div><span className="mkt-contagem">{grupos.filter(g=>g.municipio_id===id).length}</span></header><div className="mkt-coluna-corpo">{grupos.filter(g=>g.municipio_id===id).map(g=>{const h=m.dados.atualizacoes.filter(a=>a.grupo_id===g.id),pendentes=h.filter(a=>a.enviar_ao_grupo&&!a.enviado_em).length;return <article className="mkt-grupo-card" key={g.id}><div className="mkt-grupo-topo"><span className="mkt-whatsapp"><MessageCircle size={23}/></span><span className={`mkt-badge ${g.status==='Ativo'?'verde':g.status==='Pausado'?'cinza':'ambar'}`}>{g.status}</span></div><h4>{g.nome}</h4><p className="mkt-descricao">{g.descricao||'Comunicação e acompanhamento do município.'}</p><div className="mkt-card-indicadores"><span>{h.length} progresso(s)</span>{pendentes>0&&<span><Clock size={13}/> {pendentes} para comunicar</span>}</div><button className="btn mkt-card-abrir" onClick={()=>{setTexto('');setEnviar(false);setAberto(g.id);}}>Ver grupo e progressos</button>{arquivados&&<button className="btn" disabled={m.ocupado} onClick={()=>m.executar(()=>editarCRM('integracao_marketing_grupos',g.id,{ativo:true}))}><RotateCcw size={15}/> Restaurar grupo</button>}</article>;})}{!arquivados&&<button className="mkt-adicionar" onClick={()=>novo(id)}><Plus size={16}/> Adicionar grupo</button>}</div></section>)}</div>
  {m.dados&&!municipios.length&&<div className="mkt-vazio"><MessageCircle size={36}/><h3>{arquivados?'Nenhum grupo removido':'Organize seus grupos por município'}</h3><p>{busca?'Nenhum grupo encontrado para esta busca.':'Cadastre o primeiro grupo para acompanhar as comunicações e os progressos.'}</p>{!arquivados&&<button className="btn btn-primario" onClick={()=>novo('')}>Adicionar grupo</button>}</div>}
  {form&&<JanelaMarketing titulo={form.id?'Editar grupo':'Adicionar grupo'} fechar={()=>setForm(null)}><EstadoModulo modulo={m}/><form className="mkt-form" onSubmit={async e=>{e.preventDefault();const {id,...dados}=form;dados.nome=dados.nome.trim();dados.link=dados.link.trim()||null;if(await m.executar(()=>id?editarCRM('integracao_marketing_grupos',id,dados):criarCRM('integracao_marketing_grupos',dados)))setForm(null);}}><CampoCRM nome="Nome do grupo"><input className="inp" required maxLength={160} value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></CampoCRM><MunicipioMarketing db={db} value={form.municipio_id} onChange={v=>setForm({...form,municipio_id:v})}/><CampoCRM nome="Link de convite do WhatsApp (opcional)"><input className="inp" type="url" placeholder="https://chat.whatsapp.com/…" value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/></CampoCRM><CampoCRM nome="Status do grupo"><select className="inp" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Em preparação','Ativo','Pausado'].map(s=><option key={s}>{s}</option>)}</select></CampoCRM><CampoCRM nome="Descrição"><textarea className="inp" rows={3} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></CampoCRM><div className="mkt-form-acoes"><button type="button" className="btn" onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primario" disabled={m.ocupado}>Salvar grupo</button></div></form></JanelaMarketing>}
  {grupo&&<JanelaMarketing titulo={grupo.nome} fechar={()=>setAberto(null)}><EstadoModulo modulo={m}/><p className="mkt-eyebrow">{nomeMunicipio(db,grupo.municipio_id)} · {grupo.status}</p><p className="mkt-relato">{grupo.descricao}</p><div className="mkt-form-acoes">{grupo.link&&/^https:\/\/chat\.whatsapp\.com\//.test(grupo.link)&&<a className="btn" href={grupo.link} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/> Abrir WhatsApp</a>}{grupo.ativo&&<><button className="btn" onClick={()=>editar(grupo)}><Pencil size={16}/> Editar grupo</button><button className="btn btn-perigo" onClick={()=>{setAberto(null);setRemover(grupo);}}><Trash2 size={16}/> Remover grupo</button></>}</div>
    {grupo.ativo&&<form className="mkt-form mkt-progresso-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(()=>criarCRM('integracao_marketing_atualizacoes',{grupo_id:grupo.id,texto:texto.trim(),enviar_ao_grupo:enviar}))){setTexto('');setEnviar(false);}}}><CampoCRM nome="Registrar progresso"><textarea className="inp" required rows={4} maxLength={10000} value={texto} placeholder="O que avançou e pode ser comunicado aos moradores?" onChange={e=>setTexto(e.target.value)}/></CampoCRM><label className="mkt-check"><input type="checkbox" checked={enviar} onChange={e=>setEnviar(e.target.checked)}/> Marcar para futura comunicação ao grupo</label><p className="ajuda">O registro será salvo. Nenhuma mensagem será enviada nesta etapa.</p><button className="btn btn-primario" disabled={m.ocupado||!texto.trim()}>Salvar progresso</button></form>}
    <h3>Histórico de progressos</h3>{historico.map(a=><article className="mkt-historico" key={a.id}><span className={`mkt-badge ${a.enviado_em?'verde':a.enviar_ao_grupo?'ambar':'cinza'}`}>{a.enviado_em?'Enviado':a.enviar_ao_grupo?'Aguardando futura integração':'Registro interno'}</span><p className="mkt-relato">{a.texto}</p><small>{new Date(a.created_at).toLocaleString('pt-BR')} · {db.usuarios.find(u=>u.erpRef===a.created_by)?.nome||'Equipe'}</small></article>)}{!historico.length&&<p className="ajuda">Nenhum progresso registrado neste grupo.</p>}
  </JanelaMarketing>}
  {remover&&<RemoverMarketing titulo="grupo" modulo={m} fechar={()=>setRemover(null)} confirmar={()=>editarCRM('integracao_marketing_grupos',remover.id,{ativo:false})}/>}
 </section>;
}
