import {useState} from 'react';
import {lerTabela} from './dados-compartilhados.js';
import {rpcCRM} from './crm-api.js';
import {conciliarFinanceiro,dinheiro,dataFinanceira} from './financeiro-regras.js';
import {lerDocumentoFinanceiro} from './financeiro-importacao.js';
export default function ImportarFinanceiro({modo,cliente,fechar,salvo}){
 const [arquivo,setArquivo]=useState(null),[propostas,setPropostas]=useState(null),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState('');
 const selecionadas=(propostas||[]).filter(p=>p.selecionado&&!p.motivo);
 const analisar=async()=>{if(!arquivo)return;setErro('');setOcupado(true);setPropostas(null);try{const entradas=await lerDocumentoFinanceiro(arquivo,modo);if(!entradas.length)throw Error('Nenhum registro reconhecido. Confira a legibilidade do documento.');if(entradas.length>500)throw Error('Divida o relatório em arquivos de até 500 registros.');const filtro=cliente?`&id=eq.${cliente.id}`:'&ativo=eq.true';const [cs,ps]=await Promise.all([lerTabela('fin_receb_clientes','id,nome,codigo,cpf_cnpj',filtro),lerTabela('fin_receb_parcelas','*',cliente?`&cliente_id=eq.${cliente.id}&ativo=eq.true`:'&ativo=eq.true')]);setPropostas(conciliarFinanceiro(entradas,cs,ps,modo));}catch(e){setErro(e.message);}finally{setOcupado(false);}};
 const confirmar=async()=>{if(!selecionadas.length||ocupado)return;setOcupado(true);setErro('');try{await rpcCRM('integracao_financeiro_importar',{p_arquivo:arquivo.name,p_itens:selecionadas.map(p=>({id:p.parcela.id,versao:p.parcela.versao,dados:p.dados}))});salvo();}catch(e){setErro(`${e.message}. O arquivo e a conferência permanecem nesta tela. Se houve conflito, analise novamente antes de confirmar.`);}finally{setOcupado(false);}};
 return <section className="card fin-importacao" aria-label="Conferir importação financeira"><h2>{modo==='boletos'?'Boletos e carnês':'Relatório de pagamentos'}</h2><p>Confira cada cliente e vencimento antes de confirmar. Linhas ambíguas ou inválidas não serão gravadas.</p><p className="ajuda">PDF até 3 MB{modo==='pagamentos'?' ou CSV/Excel com nome, código/CPF, vencimento, valor_pago e data_pagamento':''}. Documentos PDF serão lidos pela IA.</p><input type="file" aria-label="Documento financeiro" accept={modo==='pagamentos'?'.pdf,.csv,.xlsx,.xls':'.pdf'} disabled={ocupado} onChange={e=>{setArquivo(e.target.files[0]);setPropostas(null);}}/><div className="fin-acoes"><button className="btn" disabled={!arquivo||ocupado} onClick={analisar}>{ocupado?'Processando…':'Analisar e conferir'}</button><button className="btn" disabled={ocupado} onClick={fechar}>Fechar</button></div>{erro&&<p role="alert">{erro}</p>}
 {propostas&&<><div className="rolagem"><table className="tab"><thead><tr><th>Confirmar</th><th>Cliente</th><th>Vencimento</th><th>{modo==='boletos'?'Linha digitável':'Valor pago'}</th><th>Conferência</th></tr></thead><tbody>{propostas.map((p,i)=><tr key={i}><td><input type="checkbox" aria-label={`Confirmar registro ${i+1}`} disabled={!!p.motivo||ocupado} checked={p.selecionado} onChange={e=>setPropostas(ps=>ps.map((a,n)=>n===i?{...a,selecionado:e.target.checked}:a))}/></td><td>{p.cliente?.nome||p.entrada.pagador}<small>{p.cliente?.codigo}</small></td><td>{dataFinanceira(p.entrada.vencimento)}</td><td className="fin-codigo">{modo==='boletos'?p.entrada.linha_digitavel:dinheiro(p.entrada.valor_liquidado)}</td><td>{p.motivo||`Parcela ${p.parcela.numero} encontrada — conferir`}</td></tr>)}</tbody></table></div><button className="btn btn-primario" disabled={!selecionadas.length||ocupado} onClick={confirmar}>Confirmar {selecionadas.length} {modo==='boletos'?'código(s)':'pagamento(s)'}</button></>}
 </section>;
}
