import {useState} from 'react';
import {listarCRM,criarCRM,editarCRM} from './crm-api.js';
import {acessoCRM,progressoMarketing} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
export default function JornadaMarketing({db,usuario}) {
 const acesso=acessoCRM(usuario),[busca,setBusca]=useState(''),[status,setStatus]=useState(''),[novo,setNovo]=useState(false),[nucleo,setNucleo]=useState(''),[notas,setNotas]=useState(''),[aberto,setAberto]=useState(null),[novaEtapa,setNovaEtapa]=useState(false);
 const m=useModulo(async()=>{if(!acesso.marketing)return {};const [etapas,projetos,progresso]=await Promise.all(['etapas','projetos','progresso'].map(t=>listarCRM(`integracao_marketing_${t}`)));return {etapas,projetos,progresso};},[usuario?.id],['marketing']);
 if(!acesso.marketing)return <div className="contem"><h1>Marketing</h1><p>Acesso restrito ao Marketing e à administração.</p></div>;
 const nucleoDe=id=>db.nucleos.find(n=>(n.externo?.kanbanId||n.id)===id);
 const titulo=p=>{if(p.municipio_id)return db.municipios.find(m=>m.id===p.municipio_id)?.nome||'Município';const n=nucleoDe(p.nucleo_id);return `${n?.codigo||''} ${n?.nome||'Núcleo'}`;};
 const resumo=p=>progressoMarketing(m.dados.etapas,m.dados.progresso.filter(r=>r.projeto_id===p.id));
 return <div className="mkt-jornada"><div className="cabeca"><div><h2>Jornada de comunicação</h2><p>Acompanhe cada fase do relacionamento com municípios e núcleos.</p></div><div className="crm-acoes"><button className="btn btn-primario" onClick={()=>setNovo(true)}>Vincular município ou núcleo</button><button className="btn" onClick={()=>setNovaEtapa(!novaEtapa)}>Cadastrar etapa</button></div></div><EstadoModulo modulo={m}/>
 <div className="crm-acoes"><input className="inp" aria-label="Buscar marketing" placeholder="Buscar município ou núcleo" value={busca} onChange={e=>setBusca(e.target.value)}/><select className="inp" aria-label="Status do marketing" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="pendente">Em andamento</option><option value="concluido">Concluídos</option></select></div>
 {novo&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await m.executar(()=>criarCRM('integracao_marketing_projetos',{nucleo_id:nucleo.startsWith('n:')?nucleo.slice(2):null,municipio_id:nucleo.startsWith('m:')?nucleo.slice(2):null,observacoes:notas}))){setNovo(false);setNotas('');}}}><CampoCRM nome="Município ou núcleo"><select className="inp" required value={nucleo} onChange={e=>setNucleo(e.target.value)}><option value="">Selecione</option><optgroup label="Municípios">{db.municipios.map(m=><option key={m.id} value={`m:${m.id}`}>{m.nome}</option>)}</optgroup><optgroup label="Núcleos">{db.nucleos.map(n=><option key={n.id} value={`n:${n.externo?.kanbanId||n.id}`}>{n.codigo} {n.nome}</option>)}</optgroup></select></CampoCRM><CampoCRM nome="Observações"><textarea className="inp" value={notas} onChange={e=>setNotas(e.target.value)}/></CampoCRM><div className="crm-acoes"><button className="btn btn-primario" disabled={m.ocupado}>Salvar</button><button type="button" className="btn" onClick={()=>setNovo(false)}>Cancelar</button></div></form>}
 {novaEtapa&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await m.executar(()=>criarCRM('integracao_marketing_etapas',{fase_numero:Number(f.get('fase_numero')),fase_nome:f.get('fase_nome'),codigo:f.get('codigo'),ordem:Number(f.get('ordem')),titulo:f.get('titulo'),descricao:f.get('descricao')})))setNovaEtapa(false);}}><h2>Etapa da jornada</h2>{[['fase_numero','Número da fase','number'],['fase_nome','Nome da fase','text'],['codigo','Código','text'],['ordem','Ordem','number'],['titulo','Título','text'],['descricao','Descrição','text']].map(([name,label,type])=><CampoCRM key={name} nome={label}><input className="inp" name={name} type={type} min={type==='number'?1:undefined} required={name!=='descricao'}/></CampoCRM>)}<button className="btn" disabled={m.ocupado}>Salvar etapa</button></form>}
 {m.dados&&!m.dados.etapas.length&&<p>Nenhuma etapa cadastrada. As etapas e os dados do CRM serão importados na fase de migração.</p>}
 {m.dados&&<div className="crm-grade">{m.dados.projetos.filter(p=>p.ativo&&titulo(p).toLowerCase().includes(busca.toLowerCase())).filter(p=>!status||(status==='concluido'?resumo(p).percentual===100:resumo(p).percentual<100)).map(p=>{const r=resumo(p);return <article className="crm-card" key={p.id}><h2>{titulo(p)}</h2><p>{r.fase}</p><progress className="crm-progresso" value={r.percentual} max="100"/><p>{r.concluidas}/{r.total} etapas · {r.percentual}%</p><button className="btn" onClick={()=>setAberto(p.id)}>Abrir jornada</button></article>;})}</div>}
 {aberto&&m.dados&&<section className="crm-card"><h2>{titulo(m.dados.projetos.find(p=>p.id===aberto))}</h2><p>{m.dados.projetos.find(p=>p.id===aberto)?.observacoes}</p><button className="btn" onClick={()=>setAberto(null)}>Fechar jornada</button>{[...new Set(m.dados.etapas.map(e=>e.fase_numero))].sort((a,b)=>a-b).map(f=><section key={f}><h3>{f} · {m.dados.etapas.find(e=>e.fase_numero===f).fase_nome}</h3>{m.dados.etapas.filter(e=>e.fase_numero===f).sort((a,b)=>a.ordem-b.ordem).map(e=>{const p=m.dados.progresso.find(p=>p.projeto_id===aberto&&p.etapa_id===e.id);return <article className="crm-mensagem" key={e.id}><strong>{e.codigo} · {e.titulo}</strong><p>{e.descricao}</p>{p?.observacao&&<p>{p.observacao}</p>}<p>{p?.concluida?`Concluída em ${new Date(p.concluida_em).toLocaleString('pt-BR')} por ${db.usuarios.find(u=>u.erpRef===p.concluida_por)?.nome||'Equipe'}`:'Pendente'}</p><button className="btn" disabled={m.ocupado} onClick={()=>m.executar(()=>{const data={concluida:!p?.concluida,concluida_em:p?.concluida?null:new Date().toISOString(),concluida_por:p?.concluida?null:usuario.erpRef};return p?editarCRM('integracao_marketing_progresso',p.id,data):criarCRM('integracao_marketing_progresso',{...data,projeto_id:aberto,etapa_id:e.id});})}>{p?.concluida?'Reabrir':'Concluir'}</button></article>;})}</section>)}</section>}
 </div>;
}
