import {SelecaoComerciais} from './ComerciaisLead.jsx';
import {CampoBusca} from './BuscaClientes.jsx';
import {normalizarCRM} from './crm-regras.js';
import {useState} from 'react';
import {CampoCRM} from './modulo-ui.jsx';
import {rpcCRM,listarCRM} from './crm-api.js';
import {useModulo,EstadoModulo} from './modulo-ui.jsx';
import {invalidarIndiceClientes} from './dados-compartilhados.js';
import {CAMPOS_NEGOCIACAO} from './crm-negociacao.js';
export function CadastrarLead({salvar,cancelar,ocupado,comerciais,usuario,erro}){
 const m=useModulo(()=>listarCRM('fin_receb_municipios','&order=nome.asc'),[],['clientes']);
 const [buscaMunicipio,setBuscaMunicipio]=useState('');
 const [id]=useState(()=>crypto.randomUUID()),[nome,setNome]=useState(''),[telefone,setTelefone]=useState(''),[municipio,setMunicipio]=useState(''),[responsaveis,setResponsaveis]=useState(()=>comerciais.some(u=>u.erpRef===usuario.erpRef)?[usuario.erpRef]:[]);
 return <form className="crm-form" onSubmit={e=>{e.preventDefault();salvar({p_id:id,p_nome:nome.trim(),p_telefone:telefone.trim(),p_municipio:municipio,p_responsaveis:responsaveis});}}><h2>Cadastrar lead</h2>{erro&&<p role="alert" className="crm-erro">{erro}</p>}<EstadoModulo modulo={m}/><CampoCRM nome="Nome do lead"><input className="inp" autoFocus disabled={ocupado} required minLength={2} value={nome} onChange={e=>setNome(e.target.value)}/></CampoCRM><CampoCRM nome="Telefone"><input className="inp" disabled={ocupado} type="tel" required pattern="[+()0-9 .-]{10,25}" value={telefone} onChange={e=>setTelefone(e.target.value)} placeholder="(48) 99999-9999"/></CampoCRM><CampoBusca aria-label="Filtrar municípios" placeholder="Buscar município ou UF" disabled={ocupado} value={buscaMunicipio} onChange={e=>setBuscaMunicipio(e.target.value)}/><CampoCRM nome="Município do lead"><select disabled={ocupado} className="inp" required value={municipio} onChange={e=>setMunicipio(e.target.value)}><option value="">Selecione o município</option>{m.dados?.filter(x=>x.id===municipio||normalizarCRM(`${x.nome} ${x.uf}`).includes(normalizarCRM(buscaMunicipio))).map(x=><option key={x.id} value={x.id}>{x.nome} / {x.uf}</option>)}</select></CampoCRM><SelecaoComerciais comerciais={comerciais} selecionados={responsaveis} alterar={setResponsaveis} ocupado={ocupado}/><p className="ajuda">O lead ficará como Cliente novo, sob responsabilidade dos comerciais selecionados. Ao fechar o contrato, confirme a remessa para criar o cadastro do cliente.</p><div className="crm-acoes"><button className="btn btn-primario" disabled={ocupado||!responsaveis.length}>Salvar lead</button><button type="button" className="btn" onClick={cancelar} disabled={ocupado}>Cancelar</button></div></form>;
}
export function RemessaLead({card,municipio,setMunicipio,remessa,setRemessa}){
 const m=useModulo(async()=>{const [municipios,remessas]=await Promise.all([listarCRM('fin_receb_municipios','&order=nome.asc'),municipio?listarCRM('fin_receb_remessas',`&municipio_id=eq.${encodeURIComponent(municipio)}&ativo=eq.true&order=created_at.desc,id.desc`):Promise.resolve([])]);return {municipios,remessas};},[municipio],['clientes']);
 return <section className="crm-painel"><h3>Confirmar cadastro no município</h3><EstadoModulo modulo={m}/><CampoCRM nome="Município do contrato"><select className="inp" required disabled={!!card.lead_municipio_id} value={municipio} onChange={e=>{setMunicipio(e.target.value);setRemessa('');}}><option value="">Selecione</option>{m.dados?.municipios.map(x=><option key={x.id} value={x.id}>{x.nome} / {x.uf}</option>)}</select></CampoCRM><CampoCRM nome="Remessa do contrato"><select className="inp" required value={remessa} onChange={e=>setRemessa(e.target.value)}><option value="">Confirme a remessa</option>{m.dados?.remessas.map((x,i)=><option key={x.id} value={x.id}>{x.codigo} · {x.nome||'Sem título'}{i===0?' — mais recente':''}</option>)}</select></CampoCRM>{m.dados?.remessas[0]&&<button className="btn btn-sm" type="button" onClick={()=>setRemessa(m.dados.remessas[0].id)}>Usar remessa mais recente: {m.dados.remessas[0].codigo}</button>}{municipio&&m.dados&&!m.dados.remessas.length&&<p>Este município não possui remessa ativa. Solicite o cadastro de uma remessa à administração antes de confirmar.</p>}<p className="ajuda">Ao salvar, o lead vira cliente desta remessa. Os documentos poderão ser cadastrados depois em Abrir cadastro.</p></section>;
}
export const converterLead=async(card,dados,anterior,municipio,remessa)=>{const resultado=await rpcCRM('integracao_crm_converter_lead',{p_card:card.id,p_municipio:municipio,p_remessa:remessa,p_dados:dados,p_anterior:Object.fromEntries(['status',...CAMPOS_NEGOCIACAO].map(k=>[k,anterior[k]??null]))});invalidarIndiceClientes();return resultado;};
