import {useEffect,useRef,useState} from 'react';
import {ScanText,Upload,Check} from 'lucide-react';
import {analisarMatriculaNUI} from './dados-compartilhados.js';
import {sugestoesDaLeitura} from './leitor-nui.js';
export default function LeitorMatriculaNUI({secao,pode,renderCampos,onConfirmar}){
 const input=useRef(null),[arquivo,setArquivo]=useState(null),[resultado,setResultado]=useState(null),[itens,setItens]=useState([]),[selecionados,setSelecionados]=useState([]),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(''),[revisado,setRevisado]=useState(false);
 const [urlArquivo,setUrlArquivo]=useState('');
 useEffect(()=>{if(!arquivo){setUrlArquivo('');return;}const url=URL.createObjectURL(arquivo);setUrlArquivo(url);return()=>URL.revokeObjectURL(url);},[arquivo]);
 const analisar=async()=>{if(!arquivo||ocupado||!pode)return;setOcupado(true);setErro('');setResultado(null);setRevisado(false);try{const r=await analisarMatriculaNUI(arquivo);setResultado(r);const novos=sugestoesDaLeitura(r.dados,secao);setItens(novos);setSelecionados([]);}catch(e){setErro(e.message);}finally{setOcupado(false);}};
 return <section className="nui-lista" aria-label="Leitor de Matrículas IA"><h3><ScanText size={20}/> Leitor de Matrículas IA</h3><p className="ajuda">Envie a matrícula em PDF, PNG ou JPG (até 3 MB). A IA propõe dados; o técnico de Projetos confere o documento, corrige os campos e confirma o que deve entrar no cadastro.</p>{!pode?<p>Leitura e confirmação disponíveis para Projetos e administradores.</p>:<><input ref={input} type="file" accept="application/pdf,image/png,image/jpeg" aria-label="Matrícula para análise IA" disabled={ocupado} onChange={e=>{setArquivo(e.target.files?.[0]||null);setResultado(null);setErro('');}}/><button className="btn" disabled={!arquivo||ocupado} onClick={analisar}><Upload size={16}/>{ocupado?'Analisando matrícula…':'Analisar matrícula'}</button>{urlArquivo&&<a className="btn" href={urlArquivo} target="_blank" rel="noreferrer">Abrir arquivo original</a>}{resultado&&<><p><strong>Sugestões ainda não confirmadas — {resultado.arquivo}</strong></p>{(resultado.dados?.alertas||[]).map((a,i)=><p className="nui-aviso" key={i}>{typeof a==='string'?a:JSON.stringify(a)}</p>)}<details><summary>Conferir trechos de origem e atos extraídos</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:320,overflow:'auto'}}>{JSON.stringify({matricula:resultado.dados.matricula,historico_registro:resultado.dados.historico_registro,evidencias:resultado.dados.evidencias},null,2)}</pre></details>{!itens.length&&<p>Nenhum ato correspondente a esta seção foi identificado com segurança. Preencha manualmente se o documento comprovar a informação.</p>}{itens.map((item,i)=><div className="nui-item" key={i}><label><input type="checkbox" checked={selecionados.includes(i)} onChange={e=>setSelecionados(a=>e.target.checked?[...a,i]:a.filter(x=>x!==i))}/> Incluir registro {i+1}</label>{renderCampos(item,v=>{setItens(xs=>xs.map((x,j)=>j===i?v:x));setRevisado(false);})}</div>)}{!!itens.length&&<><label style={{display:'block',margin:'16px 0'}}><input type="checkbox" checked={revisado} onChange={e=>setRevisado(e.target.checked)}/> Conferi as sugestões com a matrícula e revisei os registros selecionados.</label><button className="btn btn-primario" disabled={!revisado||!selecionados.length||ocupado} onClick={()=>{try{onConfirmar(resultado,itens.filter((_,i)=>selecionados.includes(i)));setResultado(null);setArquivo(null);if(input.current)input.current.value='';}catch(e){setErro(e.message);}}}><Check size={16}/>Confirmar e incluir no formulário</button><p className="ajuda">Os registros atuais serão preservados. Após incluir, use Salvar Dados NUI para gravar.</p></>}</>}</>}{erro&&<p role="alert" className="crm-erro">{erro}</p>}</section>;
}
