export const KEY='integracao-mailing-caixas-v1';
export const uid=()=>crypto.randomUUID();
export const emptyMailing=()=>({messages:[],drafts:[],folders:[],labels:['Projetos','Documentação','Equipe'],settings:{},audit:[]});
export function recipients(m){return [...new Set([...m.to,...m.cc,...m.bcc])];}
export function accessible(m,user){return m.mailbox===user;}
export function flags(m,user){return m.flags?.[user]||{};}
export function visible(m,user,folder,now=Date.now()) {if(!accessible(m,user))return false; const f=flags(m,user); if(f.permanent)return false; if(folder==='trash')return !!f.trash;if(f.trash)return false;if(folder==='spam')return !!f.spam;if(f.spam)return false;if(folder==='scheduled')return m.from===user&&m.status==='scheduled';if(m.status!=='sent')return false;if(folder.startsWith('folder:'))return f.folder===folder.slice(7);if(folder==='sent')return m.copy==='outgoing'||m.copy==='both';if(folder==='starred')return !!f.star;if(folder==='snoozed')return new Date(f.snooze||0).getTime()>now;if(folder==='all')return true;if(folder.startsWith('label:'))return (f.labels||[]).includes(folder.slice(6));return (m.copy==='incoming'||m.copy==='both')&&!f.archive&&!f.folder&&!(new Date(f.snooze||0).getTime()>now);}
export function deliverDue(state,now=Date.now()){return {...state,messages:state.messages.map(m=>m.status==='scheduled'&&new Date(m.scheduled).getTime()<=now?{...m,status:'sent',date:new Date(now).toISOString()}:m)};}
export function validate(d,users){const active=new Set(users.filter(u=>u.ativo!==false).map(u=>u.id));if(!d.to.length)throw Error('Selecione pelo menos um destinatário.');if([...d.to,...d.cc,...d.bcc].some(id=>!active.has(id)))throw Error('Destinatário interno inválido.');if(!d.subject.trim())throw Error('Preencha o assunto.');if(!d.body.trim()&&!d.attachments.length)throw Error('Escreva uma mensagem ou adicione um anexo.');if(d.scheduled&&new Date(d.scheduled).getTime()<=Date.now())throw Error('Escolha uma data futura.');return true;}
export function redact(m,user){if(!accessible(m,user))throw Error('Mensagem não acessível.');return {...m,bcc:m.from===user?m.bcc:[]};}
export function localAssistant(action,text,name){if(action==='summary')return 'Resumo local: '+text.split('\n').filter(Boolean).slice(0,3).join(' ').slice(0,500);if(action==='reply')return `Olá!\n\nRecebi sua mensagem sobre “${text.split('\n')[0]}”. Vou conferir as informações e retorno com os próximos passos.\n\nAtenciosamente,\n${name}`;if(action==='formal')return `Olá, equipe.\n\n${text.trim()}\n\nAtenciosamente,\n${name}`;return text.trim().replace(/\s+$/gm,'');}

export function replyRecipients(message,user,all=false){return [...new Set([...(message.from===user?message.to:[message.from]),...(all?[...message.to,...message.cc]:[])])].filter(id=>id!==user);}
