import React,{useState,useRef} from 'react';
import {X,Users,User} from 'lucide-react';
import {suggestions,addRecipients} from './mailing-recipients.js';
export default function MailingRecipients({field,value,users,onChange,extraToggle,disabled=false}){
 const [query,setQuery]=useState(''),[focused,setFocused]=useState(false),[index,setIndex]=useState(0);const input=useRef();const options=suggestions(users,query,value),open=focused&&query.trim().length>0;
 const label={to:'Para',cc:'Cc',bcc:'Cco'}[field],listId='ml-recipients-'+field;
 const choose=option=>{onChange(addRecipients(value,option.ids,users));setQuery('');setIndex(0);input.current?.focus()};
 const remove=id=>onChange(value.filter(x=>x!==id));
 return <div className="ml-recipient"><label htmlFor={listId+'-input'}>{label}</label><div className="ml-recipient-control" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false)}}><div className="ml-recipient-chips">{value.map(id=><span key={id} className="ml-recipient-chip">{users.find(u=>u.id===id)?.nome||'Usuário indisponível'}<button disabled={disabled} type="button" aria-label={'Remover '+(users.find(u=>u.id===id)?.nome||'destinatário')} onClick={()=>remove(id)}><X size={13}/></button></span>)}<input disabled={disabled} id={listId+'-input'} ref={input} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={listId} aria-activedescendant={open&&options[index]?listId+'-'+index:undefined} autoComplete="off" placeholder={value.length?'Adicionar pessoa ou setor…':'Digite um nome ou setor…'} value={query} onFocus={()=>setFocused(true)} onChange={e=>{setQuery(e.target.value);setIndex(0);setFocused(true)}} onKeyDown={e=>{if(e.key==='ArrowDown'&&options.length){e.preventDefault();setIndex((index+1)%options.length)}else if(e.key==='ArrowUp'&&options.length){e.preventDefault();setIndex((index-1+options.length)%options.length)}else if(e.key==='Enter'&&open&&options[index]){e.preventDefault();choose(options[index])}else if(e.key==='Escape'){e.preventDefault();setFocused(false)}else if(e.key==='Backspace'&&!query&&value.length){remove(value[value.length-1])}}}/></div>{open&&<div className="ml-recipient-suggestions" role="listbox" id={listId} aria-label={'Sugestões para '+label}>{options.map((option,i)=><button disabled={disabled} type="button" role="option" aria-selected={i===index} id={listId+'-'+i} key={option.key} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(option)} className={i===index?'active':''}>{option.type==='sector'?<Users size={17}/>:<User size={17}/>}<span><strong>{option.label}</strong><small>{option.type==='sector'?`Setor inteiro • ${option.ids.length} usuário${option.ids.length===1?'':'s'}`:option.detail}</small></span></button>)}{!options.length&&<p>Nenhuma pessoa ou setor encontrado.</p>}</div>}</div>{extraToggle&&<button disabled={disabled} type="button" onClick={extraToggle}>Cc / Cco</button>}</div>
}
