import {useState,useEffect} from 'react';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {rpcCRM,criarCRM} from './crm-api.js';
import {requisicao} from './dados-compartilhados.js';
import {podeUsarAgentes,SETORES} from './permissoes.js';
import {hojeVendas,progressoVenda,exibirVenda,periodoVenda} from './crm-metas.js';
import './metas-vendas.css';
const br=d=>d.split('-').reverse().join('/');
function Medidor({meta,hoje}) {
 const p=progressoVenda(meta,hoje);
 return <><div className="vendas-numeros"><strong>{exibirVenda(p.realizado,meta.unidade)} / {exibirVenda(meta.alvo,meta.unidade)}</strong><span>{Math.round(p.percentual)}%</span></div><meter aria-label={`Progresso de ${meta.titulo}`} min="0" max={Number(meta.alvo)} value={Math.min(Number(meta.alvo),p.realizado)}/><p className={p.alerta?'vendas-alerta':'ajuda'} role={p.alerta?'status':undefined}>{p.situacao} · Prazo {br(meta.fim)}</p><small>Período: {br(meta.inicio)} a {br(meta.fim)} · {Math.round(p.tempo)}% do tempo decorrido</small>{Number(meta.sem_valor)>0&&meta.unidade==='valor'&&<p className="ajuda">{meta.sem_valor} venda(s) sem valor cadastrado não somam ao valor realizado.</p>}</>;
}
export default function MetasVendas({usuario,db,resumo=false}) {
 const diretor=podeUsarAgentes(usuario),[hoje,setHoje]=useState(hojeVendas),[form,setForm]=useState(null),[historico,setHistorico]=useState(false),[filtro,setFiltro]=useState('');
 const m=useModulo(()=>rpcCRM('integracao_crm_metas_painel',{}),[usuario.id],['crm','usuarios']);
 useEffect(()=>{const t=setInterval(()=>{setHoje(hojeVendas());m.atualizar();},60000);return()=>clearInterval(t);},[usuario.id]);
 const uid=usuario.erpRef||usuario.id;
 const metas=(m.dados||[]).filter(x=>(!resumo||x.participantes.includes(uid))&&(historico||x.status==='ativa')&&(!filtro||x.setor===filtro));
 const novo=()=>setForm({titulo:'',escopo:'usuario',setor:'comercial',participantes:[],unidade:'quantidade',alvo:1,inicio:hoje,fim:periodoVenda('mensal',hoje),periodo:'mensal'});
 const mudar=(k,v)=>setForm(f=>({...f,[k]:v}));
 const pessoas=(db.usuarios||[]).filter(u=>u.ativo!==false&&(u.erpRef||/^[0-9a-f-]{36}$/i.test(u.id)));
 const salvar=async e=>{e.preventDefault();const {periodo,id,versao,...dados}=form; if(await m.executar(async()=>{if(!id)return criarCRM('integracao_crm_metas',{...dados,alvo:Number(dados.alvo)});const r=await requisicao(`integracao_crm_metas?id=eq.${id}&versao=eq.${versao}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...dados,alvo:Number(dados.alvo)})});if(!r?.length)throw new Error('A meta mudou. Atualize e reabra antes de editar.');}))setForm(null);};
 const cancelar=meta=>m.executar(async()=>{const r=await requisicao(`integracao_crm_metas?id=eq.${meta.id}&versao=eq.${meta.versao}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'cancelada'})});if(!r?.length)throw new Error('A meta mudou. Atualize antes de cancelar.');});
 return <section className="crm-painel metas-vendas"><header><div><h2>{resumo?'Suas metas de vendas':'Metas de vendas'}</h2><p className="ajuda">Vendas que passaram de Contrato para Cliente ativo, descontando as desfeitas. Cada venda conta para o responsável principal registrado na ativação. Registros antigos sem comprovação dessa passagem não são contabilizados.</p></div>{diretor&&!resumo&&<button className="btn btn-primario" onClick={novo}>Nova meta de vendas</button>}</header>
 <EstadoModulo modulo={m}/>{!resumo&&<div className="crm-acoes"><label>Setor<select className="inp" value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="">Todos</option>{[...new Set((m.dados||[]).map(x=>x.setor))].map(s=><option key={s} value={s}>{SETORES[s]?.nome||s}</option>)}</select></label><label><input type="checkbox" checked={historico} onChange={e=>setHistorico(e.target.checked)}/> Incluir canceladas</label><button className="btn" onClick={m.atualizar}>Atualizar medidores</button></div>}
 {form&&<form className="crm-form" onSubmit={salvar}><h3>{form.id?'Editar meta':'Nova meta'}</h3><CampoCRM nome="Título"><input className="inp" required minLength={3} maxLength={120} value={form.titulo} onChange={e=>mudar('titulo',e.target.value)}/></CampoCRM><CampoCRM nome="Atribuir a"><select className="inp" value={form.escopo} onChange={e=>setForm(f=>({...f,escopo:e.target.value,participantes:[]}))}><option value="usuario">Vendedor</option><option value="setor">Setor / equipe</option></select></CampoCRM><CampoCRM nome="Setor"><select className="inp" value={form.setor} onChange={e=>setForm(f=>({...f,setor:e.target.value,participantes:[]}))}>{Object.entries(SETORES).map(([k,s])=><option key={k} value={k}>{s.nome}</option>)}</select></CampoCRM>
 {form.escopo==='usuario'?<CampoCRM nome="Vendedor"><select required className="inp" value={form.participantes[0]||''} onChange={e=>mudar('participantes',[e.target.value])}><option value="">Selecione</option>{pessoas.filter(u=>u.setor===form.setor).map(u=><option key={u.id} value={u.erpRef||u.id}>{u.nome}</option>)}</select></CampoCRM>:<fieldset><legend>Participantes do setor</legend><p className="ajuda">A equipe fica registrada nesta meta; mudanças futuras no cadastro não alteram o histórico.</p>{pessoas.filter(u=>u.setor===form.setor).map(u=>{const id=u.erpRef||u.id;return <label key={id} style={{display:'block'}}><input type="checkbox" checked={form.participantes.includes(id)} onChange={e=>mudar('participantes',e.target.checked?[...form.participantes,id]:form.participantes.filter(x=>x!==id))}/>{u.nome}</label>;})}</fieldset>}
 <CampoCRM nome="Medir por"><select className="inp" value={form.unidade} onChange={e=>mudar('unidade',e.target.value)}><option value="quantidade">Quantidade de vendas</option><option value="valor">Valor das vendas (R$)</option></select></CampoCRM><CampoCRM nome="Meta mínima"><input className="inp" type="number" min={form.unidade==='valor'?'0.01':'1'} step={form.unidade==='valor'?'0.01':'1'} required value={form.alvo} onChange={e=>mudar('alvo',e.target.value)}/></CampoCRM>
 <CampoCRM nome="Período"><select className="inp" value={form.periodo} onChange={e=>setForm(f=>({...f,periodo:e.target.value,fim:e.target.value==='personalizado'?f.fim:periodoVenda(e.target.value,f.inicio)}))}>{[['semanal','Semanal'],['mensal','Mensal'],['trimestral','Trimestral'],['semestral','Semestral'],['anual','Anual'],['personalizado','Personalizado']].map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></CampoCRM><CampoCRM nome="Início"><input className="inp" type="date" required value={form.inicio} onChange={e=>setForm(f=>({...f,inicio:e.target.value,fim:f.periodo==='personalizado'?f.fim:periodoVenda(f.periodo,e.target.value)}))}/></CampoCRM><CampoCRM nome="Prazo final"><input className="inp" type="date" required min={form.inicio} value={form.fim} onChange={e=>setForm(f=>({...f,fim:e.target.value,periodo:'personalizado'}))}/></CampoCRM><p className="ajuda">O período é inclusivo. Para um novo ciclo, cadastre outra meta. Metas do setor não são divididas automaticamente entre vendedores.</p><div className="crm-acoes"><button className="btn btn-primario" disabled={m.ocupado||!form.participantes.length}>Salvar meta</button><button type="button" className="btn" onClick={()=>setForm(null)}>Cancelar</button></div></form>}
 {m.dados&&!metas.length&&<p>Nenhuma meta de vendas atribuída neste filtro.</p>}<div className="vendas-grade">{metas.map(meta=><article className="vendas-meta" key={meta.id}><h3>{meta.titulo}</h3><p>{meta.escopo==='setor'?'Equipe':'Vendedor'} · {SETORES[meta.setor]?.nome||meta.setor}{meta.escopo==='usuario'?` · ${db.usuarios.find(u=>(u.erpRef||u.id)===meta.participantes[0])?.nome||'Usuário'}`:''}</p><Medidor meta={meta} hoje={hoje}/>{diretor&&!resumo&&meta.escopo==='setor'&&<details><summary>Contribuição de cada participante</summary>{(meta.por_usuario||[]).map(u=><div key={u.id}><strong>{u.nome}</strong><meter aria-label={`Contribuição de ${u.nome} para a meta do setor`} min="0" max={Number(meta.alvo)} value={Math.min(Number(meta.alvo),Number(u.realizado))}/><span>{exibirVenda(u.realizado,meta.unidade)} para a meta coletiva</span></div>)}</details>}{diretor&&!resumo&&meta.status==='ativa'&&<div className="crm-acoes"><button className="btn btn-sm" onClick={()=>setForm({id:meta.id,versao:meta.versao,titulo:meta.titulo,escopo:meta.escopo,setor:meta.setor,participantes:meta.participantes,unidade:meta.unidade,alvo:meta.alvo,inicio:meta.inicio,fim:meta.fim,periodo:'personalizado'})}>Editar meta</button><button className="btn btn-sm" disabled={m.ocupado} onClick={()=>cancelar(meta)}>Cancelar meta</button></div>}</article>)}</div></section>;
}
