import {useEffect,useRef,useState} from 'react';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {podeEditarOficios} from './oficios-permissoes.js';
import GeradorOficio from './GeradorOficio.jsx';
import {idPonto,diaPonto} from './ponto-api.js';
import {listarOficios,prepararOficio,enviarOficio,analisarOficio,registrarOficio,salvarResumoOficio,abrirOficio} from './oficios-api.js';
import './oficios.css';
export function IconeOficios({size=18}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M14 3H5a1 1 0 0 0-1 1v15a1 1 0 0 0 1 1h6M14 3v5h5M14 3l5 5v4M8 8h2M8 12h5M8 16h2"/><rect x="13" y="14" width="9" height="7" rx="1.5"/><path d="m14 15 3.5 2.5L21 15"/></svg>;}
const rotulo=(n,a)=>`${String(n).padStart(3,'0')}/${a}`;
function CadastroOficio({usuario,anoInicial,fechar,salvo}){
 const chave=`integracao-oficio-rascunho-v1:${idPonto(usuario)}`;
 const [form,setForm]=useState(()=>{try{return JSON.parse(localStorage.getItem(chave))||{data_envio:anoInicial===Number(diaPonto().slice(0,4))?diaPonto():`${anoInicial}-01-01`,numero:1,prefeitura:'',assunto:'',resumo:''};}catch{return {data_envio:diaPonto(),numero:1,prefeitura:'',assunto:'',resumo:''};}}),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false),[aviso,setAviso]=useState(''),[confirmacao,setConfirmacao]=useState('');
 const ano=Number(form.data_envio.slice(0,4)),seq=useModulo(()=>listarOficios(ano),[ano],['metas']),trava=useRef(false);
 useEffect(()=>{try{localStorage.setItem(chave,JSON.stringify(form));}catch{setAviso('Não foi possível guardar o rascunho neste navegador. Mantenha esta tela aberta até salvar.');}},[form,chave]);
 const campo=(k,v)=>setForm(f=>({...f,[k]:v}));
 const numero=seq.dados?.ultimo?seq.dados.ultimo+1:Number(form.numero);
 const analisar=async(meta)=>{try{const ia=await analisarOficio(meta.caminho);setForm(f=>({...f,ia,resumo:ia.resumo,prefeitura:f.prefeitura||ia.prefeitura,assunto:f.assunto||ia.assunto,numero:ia.numero||f.numero}));setAviso('Resumo gerado por IA. Confira os dados antes de registrar.');}catch(e){setAviso(e.message);}};
 const arquivo=async file=>{if(!file||trava.current)return;trava.current=true;setOcupado(true);setErro('');setAviso('Enviando arquivo…');setConfirmacao('');try{const meta=await prepararOficio(file,idPonto(usuario),crypto.randomUUID());await enviarOficio(file,meta);setForm(f=>({...f,meta,ia:null,resumo:''}));setAviso('Arquivo enviado. Analisando com IA…');await analisar(meta);}catch(e){setErro(e.message);setAviso('');}finally{trava.current=false;setOcupado(false);}};
 const divergencia=form.ia&&(form.ia.numero&&form.ia.numero!==numero||form.ia.ano&&form.ia.ano!==ano);
 return <section className="card oficio-cadastro"><h3>Registrar ofício enviado</h3><p>Informe a data do envio à prefeitura. O primeiro cadastro define o número inicial do ano; os seguintes usam a sequência automaticamente.</p>
 <form className="ponto-form" data-edicao-pendente="true" onSubmit={async e=>{e.preventDefault();if(trava.current||!form.meta||confirmacao!==`${numero}/${ano}`)return;trava.current=true;setOcupado(true);setErro('');try{const r=await registrarOficio({...form,...form.meta,numero,resumo_status:!form.resumo?'pendente':form.resumo===form.ia?.resumo?'ia':'revisado'});localStorage.removeItem(chave);salvo(r.ano);}catch(e){setErro(e.message);seq.atualizar();}finally{trava.current=false;setOcupado(false);}}}>
 <CampoCRM nome="Arquivo do ofício"><input className="inp" type="file" accept=".pdf,.docx,.txt" disabled={ocupado} onChange={e=>arquivo(e.target.files?.[0])}/></CampoCRM><small>PDF, DOCX ou TXT · até 10 MB. Arquivos .doc antigos devem ser exportados como PDF ou DOCX.</small>
 {form.meta&&<p>Arquivo enviado: <strong>{form.meta.nome_arquivo}</strong></p>}
 <div className="ponto-campos"><CampoCRM nome="Data de envio"><input className="inp" required type="date" min="2000-01-01" max={diaPonto()} value={form.data_envio} disabled={ocupado} onChange={e=>campo('data_envio',e.target.value)}/></CampoCRM><CampoCRM nome="Número do ofício"><input className="inp" type="number" min="1" max="999999" required disabled={ocupado||!seq.dados||!!seq.dados?.ultimo} value={numero||''} onChange={e=>campo('numero',e.target.value)}/></CampoCRM><div><strong>Ano: {ano||'—'}</strong><p>{seq.dados?.ultimo?`Próximo: ${rotulo(numero,ano)}`:'Primeiro ofício do ano: confirme o número que consta no documento.'}</p></div></div>
 <EstadoModulo modulo={seq}/>
 <CampoCRM nome="Prefeitura / Município"><input className="inp" required minLength={2} maxLength={200} disabled={ocupado} value={form.prefeitura} onChange={e=>campo('prefeitura',e.target.value)}/></CampoCRM>
 <CampoCRM nome="Assunto"><input className="inp" required minLength={3} maxLength={300} disabled={ocupado} value={form.assunto} onChange={e=>campo('assunto',e.target.value)}/></CampoCRM>
 <CampoCRM nome="Resumo"><textarea className="inp" rows={4} maxLength={2000} disabled={ocupado} value={form.resumo} onChange={e=>campo('resumo',e.target.value)}/></CampoCRM>
 {divergencia&&<p role="alert">A IA identificou {form.ia.numero||'número não identificado'}/{form.ia.ano||'ano não identificado'}, diferente do cadastro. Confira o documento e a data. A numeração do arquivo original não é alterada pelo sistema.</p>}
 <label className="oficio-confirmacao"><input type="checkbox" required checked={confirmacao===`${numero}/${ano}`} onChange={e=>setConfirmacao(e.target.checked?`${numero}/${ano}`:'')}/>Conferi o arquivo e confirmo a numeração {rotulo(numero||1,ano)}.</label>
 {aviso&&<p role="status">{aviso}</p>}{erro&&<p role="alert">{erro}</p>}
 <div className="flex flex-wrap gap-2"><button className="btn btn-primario" disabled={ocupado||!form.meta||!seq.dados||confirmacao!==`${numero}/${ano}`}>{ocupado?'Processando…':form.resumo?'Registrar ofício':'Registrar sem resumo de IA'}</button>{form.meta&&<button type="button" className="btn" disabled={ocupado} onClick={async()=>{setOcupado(true);await analisar(form.meta);setOcupado(false);}}>Gerar resumo com IA</button>}<button className="btn" type="button" disabled={ocupado} onClick={fechar}>Fechar e guardar rascunho</button></div>
 </form></section>;
}
export default function Oficios({usuario,modelo,timbrado}){
 const [gerando,setGerando]=useState(false);
 const anoAtual=Number(diaPonto().slice(0,4)),[ano,setAno]=useState(anoAtual),[cadastro,setCadastro]=useState(false),[busca,setBusca]=useState(''),[erro,setErro]=useState(''),[analisando,setAnalisando]=useState(null);
 const m=useModulo(()=>listarOficios(ano),[ano],['metas']),pode=podeEditarOficios(usuario),itens=m.dados?.itens||[],visiveis=itens.filter(o=>`${o.prefeitura} ${o.assunto} ${o.numero} ${o.resumo}`.toLocaleLowerCase('pt-BR').includes(busca.toLocaleLowerCase('pt-BR')));
 return <section className="oficios"><header><h2><IconeOficios size={26}/>Ofícios enviados</h2><p>Arquivo, resumo e numeração anual dos ofícios enviados às prefeituras.</p></header><div className="ponto-campos"><CampoCRM nome="Ano dos ofícios"><select className="inp" value={ano} onChange={e=>setAno(Number(e.target.value))}>{Array.from({length:anoAtual-1999},(_,i)=>anoAtual-i).map(a=><option key={a}>{a}</option>)}</select></CampoCRM><CampoCRM nome="Buscar ofício"><input className="inp" placeholder="Prefeitura, assunto ou número" value={busca} onChange={e=>setBusca(e.target.value)}/></CampoCRM><button className="btn" onClick={m.atualizar}>Atualizar</button>{pode&&<button className="btn" onClick={()=>setGerando(true)}>Gerar ofício</button>}{pode&&<button className="btn btn-primario" onClick={()=>setCadastro(true)}>Adicionar ofício</button>}</div>
 <div className="ponto-resumo"><div className="card"><span>Cadastrados em {ano}</span><strong>{m.dados?itens.length:'—'}</strong></div><div className="card"><span>Último número</span><strong>{m.dados?.ultimo?rotulo(m.dados.ultimo,ano):'—'}</strong></div><div className="card"><span>Próximo número</span><strong>{m.dados?.ultimo?rotulo(m.dados.ultimo+1,ano):'Definir no primeiro ofício'}</strong></div></div>
 {gerando&&pode&&<GeradorOficio usuario={usuario} modelo={modelo} timbrado={timbrado} proximo={ano===anoAtual&&m.dados?.ultimo?m.dados.ultimo+1:null} fechar={()=>setGerando(false)}/>}
 {cadastro&&pode&&<CadastroOficio usuario={usuario} anoInicial={ano} fechar={()=>setCadastro(false)} salvo={a=>{setCadastro(false);setAno(a);m.atualizar();}}/>}
 <EstadoModulo modulo={m}/>{erro&&<p role="alert">{erro}</p>}
 <div className="oficios-lista">{visiveis.map(o=><article className="card oficio-item" key={o.id}><div className="oficio-numero"><IconeOficios size={24}/><strong>{rotulo(o.numero,o.ano)}</strong></div><div className="oficio-conteudo"><h3>{o.assunto}</h3><p>{o.prefeitura} · Enviado em {o.data_envio.split('-').reverse().join('/')}</p><p>{o.resumo||'Resumo ainda não gerado.'}</p><small>{o.resumo_status==='ia'?'Resumo gerado por IA':o.resumo_status==='revisado'?'Resumo conferido no cadastro':'Análise pendente'} · {o.nome_arquivo}</small></div><div className="oficio-acoes"><button className="btn" onClick={async()=>{setErro('');const janela=window.open('about:blank','_blank');if(janela)janela.opener=null;try{const url=await abrirOficio(o.caminho);if(janela)janela.location=url;else throw Error('Permita abrir uma nova aba para visualizar o arquivo.');}catch(e){janela?.close();setErro(e.message);}}}>Abrir arquivo</button>{pode&&<button className="btn" disabled={!!analisando} onClick={async()=>{setAnalisando(o.id);setErro('');try{const ia=await analisarOficio(o.caminho);await salvarResumoOficio(o.id,ia.resumo);m.atualizar();}catch(e){setErro(e.message);}finally{setAnalisando(null);}}}>{analisando===o.id?'Analisando…':o.resumo?'Atualizar resumo com IA':'Gerar resumo com IA'}</button>}</div></article>)}</div>
 {m.dados&&!visiveis.length&&<p className="card oficio-cadastro">{itens.length?'Nenhum ofício encontrado nesta busca.':'Nenhum ofício cadastrado neste ano.'}</p>}
 </section>;
}
