import {useState} from 'react';
import {Plus,CalendarDays,Clock,User,CheckSquare,Pencil,Trash2,Archive,RotateCcw} from 'lucide-react';
import {listarCRM,criarCRM,editarCRM} from './crm-api.js';
import {normalizarCRM} from './crm-regras.js';
import {useModulo,EstadoModulo,CampoCRM} from './modulo-ui.jsx';
import {JanelaMarketing,MunicipioMarketing,RemoverMarketing,MESES_MARKETING,nomeMunicipio,dataMarketing} from './marketing-ui.jsx';
const STATUS=['A fazer','Em andamento','Concluído'];
export default function RotinaMarketing({db,usuario}) {
 const hoje=new Date(),[mes,setMes]=useState(hoje.getMonth()+1),[ano,setAno]=useState(hoje.getFullYear()),[busca,setBusca]=useState(''),[form,setForm]=useState(null),[aberto,setAberto]=useState(null),[remover,setRemover]=useState(null),[arquivados,setArquivados]=useState(false);
 const m=useModulo(async()=>({cards:await listarCRM('integracao_marketing_rotina',`&ano=eq.${ano}&mes=eq.${mes}`)}),[usuario.id,ano,mes]);
 const equipe=db.usuarios.filter(u=>u.ativo!==false&&u.erpRef);
 const cards=(m.dados?.cards||[]).filter(c=>Boolean(c.ativo)!==arquivados&&normalizarCRM(`${c.titulo} ${c.descricao}`).includes(normalizarCRM(busca)));
 const atual=m.dados?.cards.find(c=>c.id===aberto);
 const novo=semana=>setForm({ano,mes,semana,titulo:'',descricao:'',municipio_id:'',responsavel_id:usuario.erpRef||'',prazo:'',prioridade:'Normal',status:'A fazer',checklist:[]});
 const editar=c=>{setAberto(null);setForm(Object.fromEntries(['id','ano','mes','semana','titulo','descricao','municipio_id','responsavel_id','prazo','prioridade','status','checklist'].map(k=>[k,c[k]??''])));};
 const responsavel=id=>db.usuarios.find(u=>u.erpRef===id)?.nome||'Sem responsável';
 const campo=(k,v)=>setForm({...form,[k]:v});
 const item=(i,alteracao)=>campo('checklist',form.checklist.map((x,j)=>j===i?{...x,...alteracao}:x));
 const concluidas=cards.filter(c=>c.status==='Concluído').length;
 return <section className="mkt-area"><div className="mkt-section-head"><div><h2>Rotina mensal do marketing</h2><p>Planeje, acompanhe e conclua as entregas de cada semana.</p></div><button className="btn btn-primario" onClick={()=>novo(1)}><Plus size={17}/> Novo card</button></div>
 <div className="mkt-toolbar mkt-rotina-filtros"><CampoCRM nome="Mês"><select className="inp" value={mes} onChange={e=>{setAberto(null);setMes(Number(e.target.value));}}>{MESES_MARKETING.map((n,i)=><option value={i+1} key={n}>{n}</option>)}</select></CampoCRM><CampoCRM nome="Ano"><select className="inp" value={ano} onChange={e=>{setAberto(null);setAno(Number(e.target.value));}}>{Array.from({length:9},(_,i)=>hoje.getFullYear()-4+i).map(a=><option key={a}>{a}</option>)}</select></CampoCRM><input className="inp" type="search" aria-label="Buscar card da rotina" placeholder="Buscar atividade…" value={busca} onChange={e=>setBusca(e.target.value)}/><button className={`btn ${arquivados?'btn-primario':''}`} onClick={()=>setArquivados(!arquivados)}><Archive size={16}/>{arquivados?'Ver cards ativos':'Removidos'}</button><button className="btn" onClick={m.atualizar}>Atualizar</button></div>
 <div className="mkt-resumo-rotina"><span><CalendarDays size={17}/> {cards.length} atividade(s)</span><span><CheckSquare size={17}/> {concluidas} concluída(s)</span><span>{cards.length-concluidas} em aberto</span></div><EstadoModulo modulo={m}/>
 <div className="mkt-kanban mkt-rotina-quadro">{[1,2,3,4].map(semana=><section className={`mkt-coluna mkt-semana-${semana}`} key={semana}><header><div><span className="mkt-eyebrow">{MESES_MARKETING[mes-1]} / {ano}</span><h3>Semana {semana}</h3></div><span className="mkt-contagem">{cards.filter(c=>c.semana===semana).length}</span></header><div className="mkt-coluna-corpo">{cards.filter(c=>c.semana===semana).sort((a,b)=>(a.prazo||'9999').localeCompare(b.prazo||'9999')).map(c=><article className={`mkt-rotina-card ${c.status==='Concluído'?'concluido':''}`} key={c.id}><div className="mkt-card-badges"><span className={`mkt-badge ${c.prioridade==='Alta'?'rosa':'cinza'}`}>{c.prioridade}</span><span className={`mkt-badge ${c.status==='Concluído'?'verde':c.status==='Em andamento'?'azul':'ambar'}`}>{c.status}</span></div><button className="mkt-card-titulo" onClick={()=>setAberto(c.id)}>{c.titulo}</button>{c.municipio_id&&<p className="mkt-mini">{nomeMunicipio(db,c.municipio_id)}</p>}<p className="mkt-descricao">{c.descricao}</p><div className="mkt-card-meta"><span><Clock size={14}/>{dataMarketing(c.prazo)}</span><span><User size={14}/>{responsavel(c.responsavel_id)}</span></div>{c.checklist.length>0&&<div className="mkt-checklist-resumo"><span>Checklist {c.checklist.filter(i=>i.concluido).length}/{c.checklist.length}</span><progress max={c.checklist.length} value={c.checklist.filter(i=>i.concluido).length}/></div>}<button className="btn mkt-card-abrir" onClick={()=>setAberto(c.id)}>Abrir atividade</button>{arquivados&&<button className="btn" disabled={m.ocupado} onClick={()=>m.executar(()=>editarCRM('integracao_marketing_rotina',c.id,{ativo:true}))}><RotateCcw size={15}/> Restaurar card</button>}</article>)}{!arquivados&&<button className="mkt-adicionar" onClick={()=>novo(semana)}><Plus size={16}/> Adicionar card</button>}</div></section>)}</div>
 {form&&<JanelaMarketing titulo={form.id?'Editar atividade':'Nova atividade de marketing'} fechar={()=>setForm(null)}><EstadoModulo modulo={m}/><form className="mkt-form" onSubmit={async e=>{e.preventDefault();const {id,...dados}=form;dados.titulo=dados.titulo.trim();for(const k of ['municipio_id','responsavel_id','prazo'])dados[k]||=null;if(await m.executar(()=>id?editarCRM('integracao_marketing_rotina',id,dados):criarCRM('integracao_marketing_rotina',dados)))setForm(null);}}>
 <CampoCRM nome="Título"><input className="inp" required maxLength={180} value={form.titulo} onChange={e=>campo('titulo',e.target.value)}/></CampoCRM><CampoCRM nome="Descrição da atividade"><textarea className="inp" rows={3} value={form.descricao} onChange={e=>campo('descricao',e.target.value)}/></CampoCRM><div className="mkt-form-grid"><CampoCRM nome="Semana"><select className="inp" value={form.semana} onChange={e=>campo('semana',Number(e.target.value))}>{[1,2,3,4].map(s=><option key={s} value={s}>Semana {s}</option>)}</select></CampoCRM><CampoCRM nome="Prazo"><input className="inp" type="date" value={form.prazo} onChange={e=>campo('prazo',e.target.value)}/></CampoCRM><CampoCRM nome="Responsável"><select className="inp" value={form.responsavel_id} onChange={e=>campo('responsavel_id',e.target.value)}><option value="">Sem responsável</option>{equipe.map(u=><option key={u.erpRef} value={u.erpRef}>{u.nome}</option>)}</select></CampoCRM><CampoCRM nome="Prioridade"><select className="inp" value={form.prioridade} onChange={e=>campo('prioridade',e.target.value)}>{['Baixa','Normal','Alta'].map(v=><option key={v}>{v}</option>)}</select></CampoCRM><CampoCRM nome="Status da atividade"><select className="inp" value={form.status} onChange={e=>campo('status',e.target.value)}>{STATUS.map(v=><option key={v}>{v}</option>)}</select></CampoCRM><MunicipioMarketing db={db} value={form.municipio_id} opcional onChange={v=>campo('municipio_id',v)}/></div>
 <fieldset className="mkt-checklist-edicao"><legend>Checklist</legend>{form.checklist.map((x,i)=><div className="mkt-checklist-linha" key={x.id||i}><input aria-label={`Concluído: item ${i+1}`} type="checkbox" checked={x.concluido} onChange={e=>item(i,{concluido:e.target.checked})}/><input className="inp" aria-label={`Item ${i+1}`} required value={x.texto} onChange={e=>item(i,{texto:e.target.value})}/><button type="button" className="btn mkt-icon-button" aria-label={`Remover item ${i+1}`} onClick={()=>campo('checklist',form.checklist.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}<button type="button" className="btn" onClick={()=>campo('checklist',[...form.checklist,{id:crypto.randomUUID(),texto:'',concluido:false}])}><Plus size={15}/> Adicionar item</button></fieldset><div className="mkt-form-acoes"><button className="btn" type="button" onClick={()=>setForm(null)}>Cancelar</button><button className="btn btn-primario" disabled={m.ocupado}>Salvar atividade</button></div></form></JanelaMarketing>}
 {atual&&<JanelaMarketing titulo={atual.titulo} fechar={()=>setAberto(null)}><EstadoModulo modulo={m}/><p className="mkt-eyebrow">{MESES_MARKETING[atual.mes-1]} / {atual.ano} · Semana {atual.semana}</p><p className="mkt-relato">{atual.descricao}</p><div className="mkt-resumo-rotina"><span><User size={16}/>{responsavel(atual.responsavel_id)}</span><span><Clock size={16}/>{dataMarketing(atual.prazo)}</span><span>{atual.prioridade}</span></div>{atual.municipio_id&&<p>{nomeMunicipio(db,atual.municipio_id)}</p>}<h3>Checklist</h3>{atual.checklist.map((x,i)=><label className="mkt-check" key={x.id||i}><input type="checkbox" disabled={!atual.ativo||m.ocupado||atual.status==='Concluído'} checked={x.concluido} onChange={e=>m.executar(()=>editarCRM('integracao_marketing_rotina',atual.id,{checklist:atual.checklist.map((v,j)=>j===i?{...v,concluido:e.target.checked}:v)}))}/>{x.texto}</label>)}{!atual.checklist.length&&<p className="ajuda">Sem itens de checklist.</p>}{atual.ativo&&<><CampoCRM nome="Status da atividade"><select className="inp" disabled={m.ocupado} value={atual.status} onChange={e=>m.executar(()=>editarCRM('integracao_marketing_rotina',atual.id,{status:e.target.value}))}>{STATUS.map(v=><option key={v} disabled={v==='Concluído'&&atual.checklist.some(i=>!i.concluido)}>{v}</option>)}</select></CampoCRM><div className="mkt-form-acoes"><button className="btn" onClick={()=>editar(atual)}><Pencil size={16}/> Editar atividade</button><button className="btn btn-perigo" onClick={()=>{setAberto(null);setRemover(atual);}}><Trash2 size={16}/> Remover card</button></div></>}</JanelaMarketing>}
 {remover&&<RemoverMarketing titulo="atividade" modulo={m} fechar={()=>setRemover(null)} confirmar={()=>editarCRM('integracao_marketing_rotina',remover.id,{ativo:false})}/>}
 </section>;
}
