const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){
const p=await b.newPage({viewport:{width,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
await p.goto('http://127.0.0.1:5178/tests/browser.html?crm&financeiroTeste=Administrador');
await p.evaluate(()=>{const hoje=new Date();hoje.setDate(hoje.getDate()-((hoje.getDay()+6)%7));window.baseFixture.metas[0].semana_inicio=hoje.toISOString().slice(0,10);window.baseFixture.metas[0].prazo=new Date().toISOString().slice(0,10);window.baseFixture.metas[0].status='Aguardando aprovação';const original=window.fetch;window.cargasMunicipios=[];window.fetch=async(u,o={})=>{if(String(u).includes('/rpc/integracao_moradores_carga'))window.cargasMunicipios.push(JSON.parse(o.body).municipio);return original(u,o);};});
await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();
const nav=async(name)=>{if(width<600)await p.getByRole('button',{name:'Abrir menu',exact:true}).click();await p.getByRole('navigation').getByRole('button',{name,exact:true}).click();if(width<600)await p.waitForFunction(()=>document.querySelector('nav.nav').getBoundingClientRect().right<=0);};
await nav('Clientes');const row=p.getByRole('row').filter({hasText:'Município teste'});await row.getByRole('button',{name:'Carregar pendências do município',exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.cargasMunicipios.length),0);
await row.getByRole('button',{name:'Carregar pendências do município',exact:true}).click();await row.getByText(/moradores com pendências/).waitFor();assert.equal(await p.evaluate(()=>window.cargasMunicipios.length),1);assert.equal(await row.locator('.barra-etapas').count(),1);assert.equal(await p.getByRole('button',{name:'Carregar pendências do município',exact:true}).count(),1);
await nav('Financeiro');const competence=p.getByLabel('Competência'),municipios=p.getByRole('button',{name:'Municípios',exact:true});const a=await competence.boundingBox(),c=await municipios.boundingBox();assert.ok(Math.abs(a.y+a.height-c.y-c.height)<2,'botão Municípios alinhado');
await p.getByRole('button',{name:'Buscar',exact:true}).click();await p.getByLabel('Buscar no financeiro',{exact:true}).fill('Morador Teste');await p.locator('.fin-busca-resultados button').filter({hasText:'Morador Teste'}).click();await p.getByRole('heading',{name:'Financeiro do cliente'}).waitFor();await p.getByText('Parcela 1',{exact:true}).waitFor();
await p.evaluate(()=>document.querySelector('.rb').classList.add('escuro'));await p.waitForTimeout(250);await p.screenshot({path:`/tmp/financeiro-escuro-${width}.png`});
await nav('CRM');await p.getByRole('button',{name:'Cadastrar lead',exact:true}).click();const d=p.getByRole('dialog',{name:'Cadastrar lead'});await d.getByLabel('Filtrar municípios').fill('segundo');await p.waitForFunction(()=>document.querySelector('dialog select').options.length===2);await d.locator('select').first().selectOption({label:'Segundo município / SC'});await d.getByLabel('Filtrar municípios').fill('não existe');assert.equal(await d.locator('select').first().inputValue(),'00000000-0000-4000-8000-000000000102');
const colors=await d.evaluate(el=>({bg:getComputedStyle(el).backgroundColor,text:getComputedStyle(el).color}));assert.notEqual(colors.bg,'rgb(255, 255, 255)');assert.notEqual(colors.bg,colors.text);await d.screenshot({path:`/tmp/lead-escuro-${width}.png`});await p.getByRole('button',{name:'Fechar cadastro'}).click();
await nav('Metas');assert.equal(await p.locator('.meta-card .ponto-acao').count(),0);await p.locator('.meta-card').first().waitFor();await p.screenshot({path:`/tmp/metas-escuro-${width}.png`});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);await p.close();}console.log('Desktop/mobile: busca financeira, município pesquisável, carregamento sob demanda, alinhamento e tema escuro OK');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
