const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){
 const p=await b.newPage({viewport:{width,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
 await p.goto('http://127.0.0.1:5194/tests/browser.html?crm&mobile');await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();if(width<600)await p.getByRole('button',{name:'Abrir menu'}).click();await p.getByRole('navigation').getByRole('button',{name:'CRM',exact:true}).click();await p.locator('.crm-cliente-card').filter({hasText:'Morador Teste'}).waitFor();assert.equal(await p.getByText('column integracao_crm_chatwoot_resumo.id does not exist').count(),0);
 const antes=await p.evaluate(()=>window.baseFixture.fin_receb_clientes.length);
 await p.getByRole('button',{name:'Clientes institucionais',exact:true}).click();await p.getByRole('button',{name:'Cadastrar institucional',exact:true}).click();let d=p.getByRole('dialog');await d.getByLabel('Nome do cliente',{exact:true}).fill('Prefeitura de Teste');await d.getByLabel('Contato',{exact:true}).fill('Maria, Secretaria de Obras — 47 99999-0000');await d.getByLabel('Produto ou serviço',{exact:true}).fill('Levantamento topográfico');await d.getByLabel('Valor (R$)',{exact:true}).fill('12500.50');await d.getByLabel('Comercial responsável',{exact:true}).selectOption({label:'Ana Comercial'});await d.getByLabel('Prazo inicial de FollowUp',{exact:true}).selectOption('1');await d.getByRole('button',{name:'Cadastrar cliente institucional',exact:true}).click();await p.getByText('Negócio institucional salvo.',{exact:true}).waitFor();
 const card=p.locator('.crm-institucional-card');await card.getByRole('heading',{name:'Prefeitura de Teste'}).waitFor();assert.equal(await p.evaluate(()=>window.baseFixture.fin_receb_clientes.length),antes);
 await card.getByRole('button',{name:'Registrar FollowUp feito',exact:true}).click();d=p.getByRole('dialog');await d.getByLabel('Novo prazo de FollowUp',{exact:true}).selectOption('4');await d.getByRole('checkbox',{name:'Confirmo que este FollowUp foi feito'}).check();assert.ok(await d.getByRole('button',{name:'Concluir e agendar próximo',exact:true}).isDisabled());await d.getByLabel('Resumo do último FollowUp').fill('Secretaria solicitou proposta com prazo de entrega.');await d.getByRole('button',{name:'Concluir e agendar próximo',exact:true}).click();await d.getByText('FollowUp concluído e próximo prazo agendado.',{exact:true}).waitFor();
 await d.getByLabel('Status do negócio',{exact:true}).selectOption('Perdido');await d.getByRole('button',{name:'Salvar negócio',exact:true}).click();assert.equal(await d.count(),1);await d.getByLabel('Motivo da perda',{exact:true}).fill('Prefeitura sem orçamento neste exercício.');await d.getByRole('button',{name:'Salvar negócio',exact:true}).click();await card.getByText('Institucional · Perdido',{exact:true}).waitFor();await card.getByText('Prefeitura sem orçamento neste exercício.',{exact:false}).waitFor();assert.equal(await p.evaluate(()=>window.baseFixture.integracao_crm_institucionais_followups.filter(f=>f.status==='pendente').length),0);
 await card.getByRole('button',{name:'Abrir negócio',exact:true}).click();d=p.getByRole('dialog');await d.getByText('Histórico de FollowUp (2)',{exact:true}).click();await d.getByText('Secretaria solicitou proposta com prazo de entrega.',{exact:true}).waitFor();assert.equal(await d.getByRole('button',{name:'Agendar FollowUp',exact:true}).count(),0);await d.getByRole('button',{name:'Fechar ficha institucional'}).click();await p.evaluate(()=>document.querySelector('.rb').classList.add('escuro'));await p.locator('.crm-institucionais').scrollIntoViewIfNeeded();await p.screenshot({path:`/tmp/crm-institucionais-${width}.png`,fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await p.close();console.log('PASS',width,'CRM carrega, institucional cadastra, não cria cliente, followup 1/4 dias, perda obrigatória e histórico');
 }}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
