const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 for(const width of [1440,390]){
 const p=await b.newPage({viewport:{width,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
 await p.goto('http://127.0.0.1:5194/tests/browser.html?crm&mobile');await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();if(width<600)await p.getByRole('button',{name:'Abrir menu'}).click();await p.getByRole('navigation').getByRole('button',{name:'CRM',exact:true}).click();
 const card=p.locator('.crm-cliente-card').filter({hasText:'Morador Teste'});await card.getByText('2 conversa(s) · 12 mensagem(ns) registradas',{exact:true}).waitFor();
 await card.getByRole('button',{name:'Agendar FollowUp',exact:true}).click();let d=p.getByRole('dialog');await d.getByLabel('Prazo de FollowUp',{exact:true}).selectOption('1');await d.getByRole('button',{name:'Agendar FollowUp',exact:true}).click();await d.getByText('FollowUp agendado.',{exact:true}).waitFor();await d.getByRole('button',{name:'Fechar ficha',exact:true}).click();
 await card.getByRole('button',{name:'Registrar FollowUp feito',exact:true}).click();d=p.getByRole('dialog');await d.getByLabel('Novo prazo de FollowUp',{exact:true}).selectOption('4');assert.ok(await d.getByRole('button',{name:'Concluir e agendar próximo',exact:true}).isDisabled());await d.getByRole('checkbox',{name:'Confirmo que este FollowUp foi feito'}).check();assert.ok(await d.getByRole('button',{name:'Concluir e agendar próximo',exact:true}).isDisabled());await d.getByLabel('Resumo do último FollowUp').fill('Cliente confirmou interesse e solicitou uma proposta atualizada.');await d.getByRole('button',{name:'Concluir e agendar próximo',exact:true}).click();await d.getByText('FollowUp concluído e próximo prazo agendado.',{exact:true}).waitFor();await d.getByText('Histórico de FollowUp (1)',{exact:true}).click();await d.getByText('Cliente confirmou interesse e solicitou uma proposta atualizada.',{exact:true}).waitFor();
 assert.equal(await p.evaluate(()=>window.baseFixture.integracao_crm_followups.filter(x=>x.status==='pendente').length),1);assert.equal(await p.evaluate(()=>window.baseFixture.integracao_crm_followups.find(x=>x.status==='pendente').prazo_dias),4);
 await d.locator('.crm-followup').scrollIntoViewIfNeeded();await p.screenshot({path:`/tmp/crm-followup-${width}.png`});assert.ok((await d.boundingBox()).width<=width);await d.getByRole('button',{name:'Fechar ficha',exact:true}).click();
 await p.getByRole('button',{name:'Dashboard comercial',exact:true}).click();await p.locator('.crm-dashboard-agente').filter({hasText:'Ana Comercial'}).waitFor();await p.getByLabel('Comercial do dashboard').selectOption({label:'Bia Comercial'});assert.equal(await p.locator('.crm-dashboard-agente').count(),1);await p.getByLabel('Comercial do dashboard').selectOption('');await p.evaluate(()=>document.querySelector('.rb').classList.add('escuro'));await p.locator('.crm-dashboard').scrollIntoViewIfNeeded();await p.screenshot({path:`/tmp/crm-dashboard-${width}.png`,fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await p.close();console.log('PASS',width,'agendar, concluir com resumo, reagendar 4 dias, histórico, métricas, filtro e tema escuro');
 }
 const p=await b.newPage();await p.goto('http://127.0.0.1:5194/tests/browser.html?crm&financeiroTeste=Comercial');await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();await p.getByRole('navigation').getByRole('button',{name:'CRM',exact:true}).click();await p.getByRole('button',{name:'Cadastrar lead',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Dashboard comercial',exact:true}).count(),0);await p.close();console.log('PASS dashboard não aparece para comercial');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
