import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {prepararBanco} from './crm-schema.test.js';import {csvArquivo} from '../src/crm-arquivo.js';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const read=p=>readFileSync(new URL('../supabase/'+p,import.meta.url),'utf8');
async function preparar(){const db=await prepararBanco();await db.exec(`alter table fin_receb_remessas add column codigo text,add column ativo boolean default true,add column created_at timestamptz default now();alter table integracao_moradores add column referencia_tabela text,add column criado_por uuid;alter table integracao_moradores add primary key(colecao,registro_id);insert into profiles values('${id(7)}','Inativo','Comercial',false);`);for(const f of ['crm-leads.sql','crm-lead-responsavel.sql','crm-carregamento.sql'])await db.exec(read('operacoes/'+f));await db.exec(read('migrations/20260922162925_crm_multiplos_comerciais.sql'));await db.exec(read('migrations/20260919182005_chatwoot_ia_conexao.sql'));await db.exec(read('migrations/20260923122108_crm_followup_dashboard.sql'));await db.exec(`insert into integracao_crm_cards(id,lead_nome,responsavel_id,comerciais_adicionais) values('${id(80)}','Lead Ana','${id(2)}',array['${id(3)}']::uuid[]),('${id(81)}','Lead Bia','${id(3)}','{}');`);return db;}
async function como(db,n,sql,args=[]){await db.exec(`set role authenticated;set request.jwt.claim.sub='${id(n)}'`);try{return(await db.query(sql,args)).rows;}finally{await db.exec('reset role;reset request.jwt.claim.sub');}}
const operar=(db,n,card,pedido,anterior,dias,resumo='')=>como(db,n,'select integracao_crm_followup($1,$2,$3,$4,$5) id',[id(card),id(pedido),anterior,dias,resumo]);

test('arquivo de leads: preserva dados, restringe leitura, encerra followup, restaura e mantém histórico',async()=>{const db=await preparar();try{
 await db.exec(read('migrations/20260923160000_crm_arquivo_leads.sql'));
 await db.exec(`insert into integracao_crm_cards(id,cliente_id,responsavel_id) values('${id(82)}','${id(20)}','${id(2)}');`);
 const arquivar=(n,card=80,sim=true,motivo='Sem interesse no momento',responsavel=null)=>como(db,n,'select integracao_crm_arquivar_lead($1,$2,$3,$4)',[id(card),sim,motivo,responsavel&&id(responsavel)]);
 const primeiro=(await operar(db,2,80,90,null,1))[0].id;await operar(db,2,80,91,primeiro,2,'Solicitou retomar no próximo semestre.');
 await como(db,2,`insert into integracao_crm_atendimentos(card_id,autor_id,relato,data) values('${id(80)}','${id(2)}','Contato preservado',now());`);await como(db,2,`insert into integracao_crm_tarefas(card_id,titulo,prazo) values('${id(80)}','Telefonar',current_date);`);
 await assert.rejects(()=>arquivar(4),/Sem permissão/);await assert.rejects(()=>arquivar(2,81),/sem permissão/);await assert.rejects(()=>arquivar(2,82),/exclusiva para leads/);await assert.rejects(()=>arquivar(2,80,true,''),/motivo/);
 await arquivar(3); // Shared owner can archive.
 for(const u of [2,3]){assert.equal((await como(db,u,`select * from integracao_crm_cards where id='${id(80)}'`)).length,0);assert.equal((await como(db,u,'select * from integracao_crm_arquivo')).length,0);assert.equal((await como(db,u,`select * from integracao_crm_followups where card_id='${id(80)}'`)).length,0);}
 assert.equal((await como(db,1,`select * from integracao_crm_funil where id='${id(80)}'`)).length,0);assert.equal((await como(db,1,`select * from integracao_crm_tarefas where card_id='${id(80)}'`)).length,0);
 const arquivo=(await como(db,1,'select * from integracao_crm_arquivo'))[0];assert.equal(arquivo.arquivado_por,id(3));assert.equal(arquivo.dados.lead_nome,'Lead Ana');assert.equal(arquivo.dados.followups.length,2);assert.equal(arquivo.dados.tarefas.length,1);
 assert.equal((await como(db,1,`select * from integracao_crm_followups where card_id='${id(80)}' and status='pendente'`)).length,0);assert.equal((await como(db,1,`select * from integracao_crm_atendimentos where card_id='${id(80)}'`)).length,1);
 await assert.rejects(()=>operar(db,1,80,92,null,1),/indisponível/);
 await assert.rejects(()=>como(db,1,`update integracao_crm_cards set status='Perdido' where id='${id(80)}'`),/Restaure/);
 await assert.rejects(()=>como(db,1,`update integracao_crm_cards set arquivado_em=null where id='${id(80)}'`),/permission denied/);
 await assert.rejects(()=>arquivar(2,80,false,'',2),/sem permissão/);await assert.rejects(()=>arquivar(1,80,false,'',7),/ativos/);await arquivar(1,80,false,'',3);
 assert.equal((await como(db,3,`select * from integracao_crm_funil where id='${id(80)}'`))[0].status,'Cliente novo');assert.equal((await como(db,1,'select * from integracao_crm_arquivo'))[0].restaurado_por,id(1));assert.equal((await como(db,2,`select * from integracao_crm_cards where id='${id(80)}'`)).length,0);
 await operar(db,3,80,93,null,4);await arquivar(3);assert.equal((await como(db,1,'select * from integracao_crm_arquivo')).length,2);
 assert.equal((await db.query('select count(*) n from fin_receb_clientes')).rows[0].n,1);
 await db.exec('set role anon');await assert.rejects(()=>db.query('select * from integracao_crm_arquivo'),/permission denied/);await db.exec('reset role');
 }finally{await db.close();}});
test('CSV preserva acentos, aspas e neutraliza fórmulas de planilhas',()=>{const texto=csvArquivo([{dados:{lead_nome:'=CMD()',lead_telefone:'+55479999',municipio:'São José',status:'Perdido',followups:[{concluido_em:'2026-09-23',resumo:'Cliente pediu "prazo"'}]},motivo:'Sem orçamento',arquivado_em:'2026-09-23'}],()=> 'Diretor');assert.ok(texto.startsWith('\ufeff'));assert.ok(texto.includes('"\'=CMD()"'));assert.ok(texto.includes('"\'+55479999"'));assert.ok(texto.includes('São José'));assert.ok(texto.includes('""prazo""'));});
