import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
async function banco(){const db=new PGlite();await db.exec(`create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;create table profiles(id uuid primary key,tipo text,ativo boolean);create table planos_trabalho(id uuid primary key);create table etapas_plano(id uuid primary key,plano_id uuid references planos_trabalho);create table etapa_responsaveis(etapa_id uuid references etapas_plano,usuario_id uuid references profiles,primary key(etapa_id,usuario_id));insert into profiles values('${id(1)}','Diretor de Projetos',true),('${id(2)}','Projetos',true),('${id(3)}','Diretor Técnico',true),('${id(4)}','Diretor de Projetos',false);insert into planos_trabalho values('${id(10)}');insert into etapas_plano values('${id(11)}','${id(10)}');grant select on profiles to authenticated;grant select,insert,update,delete on planos_trabalho,etapas_plano,etapa_responsaveis to authenticated;`);await db.exec(readFileSync(new URL('./fixtures/planos-diretoria-producao.sql',import.meta.url),'utf8'));await db.exec(`alter table planos_trabalho enable row level security;alter table etapas_plano enable row level security;alter table etapa_responsaveis enable row level security;create policy plano_leitura on planos_trabalho for select to authenticated using(can_access_plan(id));create policy etapa_leitura on etapas_plano for select to authenticated using(can_access_plan(plano_id));create policy etapa_gravar on etapas_plano for insert to authenticated with check(is_tech_director());create policy responsavel_gravar on etapa_responsaveis for insert to authenticated with check(is_tech_director());create policy responsavel_leitura on etapa_responsaveis for select to authenticated using(exists(select 1 from etapas_plano ep where ep.id=etapa_responsaveis.etapa_id and can_access_plan(ep.plano_id)));`);return db;}
async function como(db,u,sql){await db.exec(`set role authenticated;set request.jwt.claim.sub='${id(u)}';`);try{return (await db.query(sql)).rows;}finally{await db.exec('reset role');}}
const inserir=db=>como(db,1,`insert into etapa_responsaveis values('${id(11)}','${id(2)}')`);
test('Diretor de Projetos lê planos, cria etapa e atribui/remove responsáveis; perfil comum permanece restrito',async()=>{const db=await banco();try{
 await assert.rejects(()=>inserir(db),/row-level security/);assert.equal((await como(db,1,'select * from planos_trabalho')).length,0);
 await db.exec(readFileSync(new URL('../supabase/migrations/20260930151102_diretoria_projetos_planos.sql',import.meta.url),'utf8'));
 assert.equal((await como(db,1,'select * from planos_trabalho')).length,1);await inserir(db);assert.equal((await como(db,1,'select * from etapa_responsaveis')).length,1);
 await como(db,1,`insert into etapas_plano values('${id(12)}','${id(10)}')`);assert.equal((await como(db,1,`select is_stage_assignee('${id(12)}') ok`))[0].ok,true);
 await como(db,1,`delete from etapa_responsaveis where etapa_id='${id(11)}'`);assert.equal((await db.query('select * from etapa_responsaveis')).rows.length,0);
 for(const u of [2,4]){await assert.rejects(()=>como(db,u,`insert into etapa_responsaveis values('${id(11)}','${id(2)}')`),/row-level security/);assert.equal((await como(db,u,'select * from planos_trabalho')).length,0);}
 assert.equal((await como(db,3,'select * from planos_trabalho')).length,1);await como(db,3,`insert into etapa_responsaveis values('${id(11)}','${id(2)}')`);
 await db.exec(readFileSync(new URL('../supabase/operacoes/reverter-diretoria-projetos-20260930.sql',import.meta.url),'utf8'));assert.equal((await como(db,1,'select * from planos_trabalho')).length,0);
 }finally{await db.close();}});
