const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});try{const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5178/tests/geojson-fluxo.html');
const data={type:'FeatureCollection',crs:{properties:{name:'EPSG:31982'}},features:[{type:'Feature',properties:{Q_L:'Q01_L01',Codigo:'TST01_0001'},geometry:{type:'Polygon',coordinates:[[[500000,7000000],[500020,7000000],[500020,7000010],[500000,7000010],[500000,7000000]]]}}]};
await p.getByLabel('Arquivo GeoJSON').setInputFiles({name:'lotes.geojson',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await p.getByRole('button',{name:'Conferir lotes e vértices'}).click();await p.getByRole('button',{name:'Confirmar importação de 1 feições'}).click();
await p.getByRole('button',{name:'Sugerir vínculos pelos códigos'}).click();const state=async()=>JSON.parse(await p.locator('#resultado').innerText());assert.equal((await state()).processos[0].unidades[0].memorial,undefined);
await p.getByLabel('Confirmar Q01_L01',{exact:true}).check();await p.getByRole('button',{name:'Confirmar e salvar 1 vínculos selecionados'}).click();assert((await state()).processos[0].unidades[0].memorial);
await p.getByRole('button',{name:'Conferir Q01_L01'}).click();await p.getByRole('button',{name:'Revogar memorial e liberar vínculo'}).click();assert((await state()).processos[0].unidades[0].memorial);await p.getByLabel('Motivo da revogação').fill('Revisão de destino');await p.getByRole('button',{name:'Confirmar revogação',exact:true}).click();assert.equal((await state()).processos[0].unidades[0].memorial,'');assert.equal((await state()).nucleos[0].memoriaisRevogados.length,1);
await p.getByLabel('Vincular Q01_L01 a').selectOption('unidade:["p","u"]');await p.getByRole('button',{name:'Salvar vínculo — revisar e confirmar'}).click();await p.getByRole('button',{name:'Confirmar vínculo e preencher memorial'}).click();assert((await state()).processos[0].unidades[0].memorial);assert.deepEqual(errors,[]);console.log('Importação, sugestão, confirmação, revogação e novo vínculo manual: OK');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
