const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
const url=process.env.TEST_URL||'http://127.0.0.1:5187';
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 for(const mobile of [false,true]){
 const p=await b.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1100}});p.setDefaultTimeout(15000);const errors=[];p.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});
 await p.goto(url+'/tests/browser.html?oficios&financeiroTeste=Projetos');await p.getByLabel('E-mail',{exact:true}).waitFor();
 await p.evaluate(()=>{const base=window.baseFixture;base.integracao_configuracoes.push({colecao:'config',registro_id:'modelosDoc',referencia_tabela:'integracao_config',dados:{valor:{oficio:{introducao:'Introdução aprovada para teste.',encerramento:'Atenciosamente,'}}}});const original=window.fetch;window.fetch=(input,options)=>String(input)==='/api/oficios-gerar'?Promise.resolve(Response.json({conteudo:'Solicitamos os documentos do processo informado, para continuidade da análise técnica.'})):original(input,options);});
 await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();
 if(mobile)await p.getByRole('button',{name:'Abrir menu'}).click();await p.getByRole('navigation').getByRole('button',{name:'Metas',exact:true}).click();await p.getByRole('button',{name:'Ofícios',exact:true}).click();
 await p.getByRole('button',{name:'Adicionar ofício',exact:true}).waitFor();await p.getByRole('button',{name:'Gerar ofício',exact:true}).click();await p.getByLabel('Introdução do ofício',{exact:true}).waitFor().catch(async e=>{console.log(await p.locator('body').innerText());throw e;});assert.equal(await p.getByLabel('Introdução do ofício',{exact:true}).inputValue(),'Introdução aprovada para teste.');
 await p.getByLabel('Destinatário / Prefeitura',{exact:true}).fill('À Prefeitura de Teste\nSecretaria de Urbanismo');await p.getByLabel('Assunto do novo ofício',{exact:true}).fill('Solicitação de documentos');await p.getByLabel('Conteúdo do ofício',{exact:true}).fill('Conteúdo manual preservado.');
 await p.getByText('Escrever com auxílio da IA',{exact:true}).click();await p.getByLabel('Orientação para a IA',{exact:true}).fill('Solicitar documentos para continuidade da análise.');await p.getByRole('button',{name:'Gerar sugestão de conteúdo',exact:true}).click();await p.getByLabel('Sugestão da IA para revisão',{exact:true}).waitFor();assert.equal(await p.getByLabel('Conteúdo do ofício',{exact:true}).inputValue(),'Conteúdo manual preservado.');await p.getByRole('button',{name:'Usar sugestão no conteúdo',exact:true}).click();
 assert.equal(await p.getByLabel('Introdução do ofício',{exact:true}).inputValue(),'Introdução aprovada para teste.');
 for(const format of ['PDF','Word']){const wait=p.waitForEvent('download');await p.getByRole('button',{name:`Baixar ofício em ${format}`,exact:true}).click();const dl=await wait;await dl.saveAs(`/tmp/oficio-equipe-${mobile?'mobile':'desktop'}.${format==='PDF'?'pdf':'docx'}`);}
 assert.equal(await p.evaluate(()=>window.oficiosTeste.length),0);await p.screenshot({path:`/tmp/oficio-equipe-${mobile?'mobile':'desktop'}.png`,fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await p.close();console.log('PASS geração Projeto',mobile?'mobile':'desktop','modelo, revisão IA, PDF e Word sem consumir sequência');
 }
 const p=await b.newPage({viewport:{width:1440,height:1100}});p.setDefaultTimeout(15000);
 await p.goto(url+'/tests/browser.html?oficios&financeiroTeste=Projetos');await p.getByLabel('E-mail',{exact:true}).waitFor();
 await p.evaluate(async()=>{
 const base=window.baseFixture,m=base.metas[0];m.associacao_tipo='processo';m.associacao_id=base.processos_kanban[0].id;m.titulo='Devolutiva da técnica';m.semana_inicio=new Date().toISOString().slice(0,10);m.prazo='2026-12-31';
 base.meta_arquivos.push({id:'00000000-0000-4000-8000-000000000099',meta_id:m.id,nome:'Original.pdf',mime_type:'application/pdf',tamanho_bytes:100,caminho_storage:'original-teste.pdf',enviado_por:base.profiles[0].id});
 base.integracao_metas.push({colecao:'metas',registro_id:m.id,referencia_tabela:'metas',referencia_id:m.id,dados:{devolutiva:{origem:'Prefeitura',chegada:'2026-09-20',prazo:'2026-12-31'}}});
 const {gerarPdf}=await import('/src/documento-pdf.js'),blob=await gerarPdf('<p>Corrigir a área do lote para 200 metros quadrados.</p>','Original',{ativo:false});window.pdfTeste=Array.from(new Uint8Array(await blob.arrayBuffer()));
 const original=window.fetch;window.analisesTeste=[];
 window.fetch=async(input,options={})=>{
 const u=String(input);if(u.includes('/storage/v1/object/documentos/')&&options.method==='POST')return Response.json({});if(u.includes('/storage/v1/object/authenticated/documentos/'))return new Response(new Uint8Array(window.pdfTeste),{headers:{'Content-Type':'application/pdf'}});
 if(u==='/api/ia'){const body=JSON.parse(options.body);window.analisesTeste.push(body);const etapa2=body.messages[0].content.some(x=>x.text?.includes('TRABALHO CORRIGIDO'));return Response.json({content:[{type:'text',text:JSON.stringify(etapa2?{resumo:'Área conferida.',pronto:true,itens:[{id:'1',status:'corrigido',observacao:'Área adequada.'}],pendencias:[],naoIdentificado:[]}:{resumo:'Revisar área.',itens:[{categoria:'areas',descricao:'Corrigir área para 200 m².',statusEsperado:'Área correta.'}],naoIdentificado:[]})}]});}
 return original(input,options);
 };
 });
 await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();await p.getByRole('navigation').getByRole('button',{name:'Metas',exact:true}).click();
 await p.getByRole('button',{name:'Metas Ativas',exact:true}).click();await p.locator('.meta-card-corpo').filter({hasText:'Devolutiva da técnica'}).first().click();await p.getByRole('button',{name:'Analisar devolutiva',exact:true}).click();let modal=p.getByRole('dialog',{name:/Análise de Devolutivas/});assert.ok(await modal.getByLabel('Prazo final (opcional)').isDisabled());await modal.getByLabel('Arquivos do trabalho corrigido (PDF ou imagem)').waitFor();assert.ok(await modal.getByRole('button',{name:'Conferir se ainda falta algo',exact:true}).isDisabled());await modal.getByRole('heading',{name:'3. Relatório da comparação',exact:true}).waitFor();await modal.getByRole('button',{name:'Analisar teor da devolutiva',exact:true}).click();await modal.getByText('Revisar área.',{exact:true}).waitFor();
 assert.equal(await p.evaluate(()=>window.analisesTeste[0].messages[0].content.filter(x=>x.type==='document').length),1);
 const bytes=await p.evaluate(()=>window.pdfTeste);await modal.getByLabel('Arquivos do trabalho corrigido (PDF ou imagem)').setInputFiles({name:'Corrigido.pdf',mimeType:'application/pdf',buffer:Buffer.from(bytes)});await modal.getByRole('button',{name:'Conferir se ainda falta algo',exact:true}).click();await modal.getByText('Área conferida.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.analisesTeste[1].messages[0].content.filter(x=>x.type==='document').length),2);
 await modal.getByRole('button',{name:'Salvar',exact:true}).click();await p.waitForFunction(()=>window.baseFixture.integracao_metas[0].dados.devolutiva.analiseIA?.etapa2?.resumo==='Área conferida.').catch(async e=>{console.log(await p.locator('body').innerText());throw e;});
 await p.getByRole('button',{name:'Conferir de novo',exact:true}).click();modal=p.getByRole('dialog',{name:/Análise de Devolutivas/});await modal.getByText('Área conferida.',{exact:true}).waitFor();await modal.getByRole('button',{name:'Analisar teor da devolutiva',exact:true}).click();await p.waitForFunction(()=>window.analisesTeste.length===3);assert.equal(await p.evaluate(()=>window.analisesTeste[2].messages[0].content.filter(x=>x.type==='document').length),1);await p.screenshot({path:'/tmp/devolutiva-tecnica.png',fullPage:true});console.log('PASS técnico responsável: original armazenado, análise, correções, comparação, persistência e reabertura');await p.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
