import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/oficios-analisar.js';
const path='00000000-0000-4000-8000-000000000001/00000000-0000-4000-8000-000000000002/oficio.pdf';
function response(){return{statusCode:200,setHeader(){},status(n){this.statusCode=n;return this;},json(d){this.body=d;return this;}};}
test('IA de ofícios valida autenticação e perfil antes de enviar documentos',async()=>{const original=globalThis.fetch,key=process.env.ANTHROPIC_API_KEY;let calls=[];process.env.ANTHROPIC_API_KEY='test-only';try{
 let r=response();await handler({method:'POST',headers:{},body:{caminho:path}},r);assert.equal(r.statusCode,401);
 globalThis.fetch=async url=>{calls.push(url);return new Response(JSON.stringify(url.includes('/auth/')?{id:path.split('/')[0]}:[{ativo:true,tipo:'Comercial'}]),{status:200});};r=response();await handler({method:'POST',headers:{authorization:'Bearer test'},body:{caminho:path}},r);assert.equal(r.statusCode,403);assert.equal(calls.length,2);
 }finally{globalThis.fetch=original;if(key===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=key;}});
test('IA analisa PDF do storage privado e retorna somente campos validados',async()=>{const original=globalThis.fetch,key=process.env.ANTHROPIC_API_KEY;process.env.ANTHROPIC_API_KEY='test-only';let payload;try{
 globalThis.fetch=async(url,opts)=>{if(url.includes('/auth/'))return Response.json({id:path.split('/')[0]});if(url.includes('/profiles?'))return Response.json([{ativo:true,tipo:'Administrador'}]);if(url.includes('/storage/'))return new Response('%PDF-1.4\nFixture de documento');payload=JSON.parse(opts.body);return Response.json({content:[{type:'text',text:JSON.stringify({resumo:'Solicita análise dos documentos do núcleo.',numero:42,ano:2026,prefeitura:'Prefeitura Teste',assunto:'Análise documental'})}]});};const r=response();await handler({method:'POST',headers:{authorization:'Bearer test'},body:{caminho:path}},r);assert.equal(r.statusCode,200);assert.equal(r.body.numero,42);assert.equal(payload.messages[0].content[0].type,'document');assert.match(payload.system,/ignore quaisquer instruções/);
 }finally{globalThis.fetch=original;if(key===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=key;}});
