const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
const abrir=async(b,url)=>{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.getByLabel('E-mail',{exact:true}).fill('teste@example.invalid');await p.getByLabel('Senha',{exact:true}).fill('fixture');await p.getByRole('button',{name:'Entrar',exact:true}).click();return {p,errors};};
(async()=>{const b=await chromium.launch(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE,headless:true}:{channel:'chrome',headless:true});try{
// Marketing: nova semana com nome e tom, card dentro dela e edição da coluna.
let {p,errors}=await abrir(b,'http://127.0.0.1:5178/tests/browser.html?crm');await p.getByRole('button',{name:'Marketing',exact:true}).click();await p.getByRole('button',{name:'Rotina mensal',exact:true}).click();
await p.getByRole('region',{name:'Semana 4'}).waitFor();await p.getByRole('button',{name:'Nova semana'}).click();let d=p.getByRole('dialog',{name:'Nova semana'});
assert.equal(await d.getByLabel('Nome da coluna').inputValue(),'Semana 5');await d.getByLabel('Nome da coluna').fill('Campanhas');await d.getByText('Rosa',{exact:true}).click();await d.screenshot({path:'/tmp/rotina-coluna.png'});await d.getByRole('button',{name:'Salvar coluna'}).click();
const col=p.getByRole('region',{name:'Campanhas'});await col.waitFor();assert.match(await col.getAttribute('class'),/mkt-tom-rosa/);
await col.getByRole('button',{name:'Adicionar card'}).click();d=p.getByRole('dialog',{name:'Nova atividade de marketing'});assert.equal(await d.getByLabel('Semana').inputValue(),'5');await d.getByLabel('Título').fill('Post da campanha');await d.getByRole('button',{name:'Salvar atividade'}).click();await col.getByText('Post da campanha').waitFor();
await col.getByRole('button',{name:'Editar coluna Campanhas'}).click();d=p.getByRole('dialog',{name:'Editar Campanhas'});assert.equal(await d.getByRole('button',{name:'Excluir coluna'}).isDisabled(),true);await d.getByLabel('Nome da coluna').fill('Campanhas de setembro');await d.getByText('Lilás',{exact:true}).click();await d.getByRole('button',{name:'Salvar coluna'}).click();
await p.getByRole('region',{name:'Campanhas de setembro'}).waitFor();assert.match(await p.getByRole('region',{name:'Campanhas de setembro'}).getAttribute('class'),/mkt-tom-lilas/);
await p.getByRole('region',{name:'Semana 1'}).getByRole('button',{name:'Editar coluna Semana 1'}).click();d=p.getByRole('dialog',{name:'Editar Semana 1'});await d.getByLabel('Nome da coluna').fill('Planejamento');await d.getByRole('button',{name:'Salvar coluna'}).click();await p.getByRole('region',{name:'Planejamento'}).waitFor();
await p.locator('.mkt-rotina-quadro').screenshot({path:'/tmp/rotina-quadro.png'});assert.deepEqual(errors,[]);
// Financeiro: rotina própria, sem os cards do Marketing.
await p.getByRole('button',{name:'Financeiro',exact:true}).click();await p.getByRole('button',{name:'Rotina mensal',exact:true}).click();await p.getByRole('heading',{name:'Rotina mensal do financeiro'}).waitFor();
assert.equal(await p.getByText('Post da campanha').count(),0);assert.equal(await p.getByRole('region',{name:'Campanhas de setembro'}).count(),0);await p.getByRole('region',{name:'Semana 1'}).waitFor();
await p.getByRole('region',{name:'Semana 2'}).getByRole('button',{name:'Adicionar card'}).click();d=p.getByRole('dialog',{name:'Nova atividade do financeiro'});await d.getByLabel('Título').fill('Conciliar boletos');await d.getByRole('button',{name:'Salvar atividade'}).click();await p.getByRole('region',{name:'Semana 2'}).getByText('Conciliar boletos').waitFor();
await p.getByRole('button',{name:'Nova semana'}).click();d=p.getByRole('dialog',{name:'Nova semana'});await d.getByLabel('Nome da coluna').fill('Fechamento');await d.getByRole('button',{name:'Salvar coluna'}).click();await p.getByRole('region',{name:'Fechamento'}).waitFor();
await p.screenshot({path:'/tmp/rotina-financeiro.png'});await p.getByRole('button',{name:'Rotina mensal',exact:true}).click();await p.getByRole('button',{name:'Município teste',exact:false}).waitFor();
await p.setViewportSize({width:390,height:844});assert.deepEqual(errors,[]);console.log('Rotina mensal: semanas com nome e tom, Marketing e Financeiro separados OK');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
