import {ErroIA} from './openai.js';
export const INSTRUCAO_MATRICULA=`Leia a matrícula imobiliária brasileira anexada e retorne somente JSON, sem Markdown, neste formato:
{"matricula":{"numero":"","cartorio":"","comarca":""},"proprietario":{"nome":"","cpf":"","cnpj":""},"imovel":{"area_registral":null,"unidade_area":"","descricao":""},"situacao_matricula":{"texto_origem":""},"historico_registro":[{"ato":"","tipo":"","de":"","para":"","data":"","descricao":""}],"evidencias":[{"campo":"","trecho":"","pagina":1}],"alertas":[]}
Extraia somente fatos legíveis, sem inventar dados, titularidade, transmissão ou usucapião. Campos ausentes ficam vazios; área ausente fica null. Área é número com unidade expressamente indicada no documento; não converta nem estime. Datas DD/MM/AAAA somente quando completas. Preserve a ordem e a identificação dos atos R/AV, incluindo cancelamentos. Preencha de/para somente quando o ato expressamente comprovar transmissão; não transforme penhora ou ônus em transmissão. Nome do proprietário atual somente quando comprovado pela sequência dos atos; se houver vários titulares, liste os nomes no campo nome, sem associar um CPF único ao conjunto. Para cada fato extraído inclua trecho literal curto e página em evidencias. Registre em alertas ilegibilidade, páginas ausentes, contradições, copropriedade e dúvidas de titularidade. Se não for matrícula ou não houver conteúdo legível, retorne os objetos vazios conforme o formato, listas vazias e um alerta explicativo. Esta extração é uma sugestão sujeita à conferência humana, nunca confirmação jurídica.`;
export function validarLeituraMatricula(texto){
 let d;try{d=JSON.parse(texto.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));}catch{throw new ErroIA('A leitura retornou dados inválidos. Tente novamente ou preencha manualmente.',422);}
 const objeto=v=>v&&typeof v==='object'&&!Array.isArray(v);
 const campos=(v,keys)=>objeto(v)&&keys.every(k=>typeof v[k]==='string'&&v[k].length<=30000);
 const valido=campos(d?.matricula,['numero','cartorio','comarca'])&&campos(d?.proprietario,['nome','cpf','cnpj'])&&campos(d?.imovel,['unidade_area','descricao'])&&(d.imovel.area_registral===null||(Number.isFinite(d.imovel.area_registral)&&d.imovel.area_registral>=0))&&campos(d?.situacao_matricula,['texto_origem'])&&Array.isArray(d.historico_registro)&&d.historico_registro.length<=500&&d.historico_registro.every(a=>campos(a,['ato','tipo','de','para','data','descricao']))&&Array.isArray(d.evidencias)&&d.evidencias.length<=1000&&d.evidencias.every(e=>campos(e,['campo','trecho'])&&Number.isInteger(e.pagina)&&e.pagina>0)&&Array.isArray(d.alertas)&&d.alertas.every(a=>typeof a==='string');
 if(!valido)throw new ErroIA('A leitura ficou inconsistente. Tente novamente ou preencha manualmente.',422);
 return d;
}
